### ISSUE TITLE
Fuzzing is Broken

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/cosign#1003]
The fuzzing check for the password is broken. 

https://github.com/sigstore/cosign/blob/9b9cd94fe0be63b7c40086a78d6ad5bae1dee13a/test/fuzz.go#L30

```
/home/sammy/go/src/github.com/naveensrinivasan/cosign/test/fuzz.go:30:18: cannot use (func() func() ([]byte, error) literal) (value of type func() func() ([]byte, error)) as func(confirm bool) func() ([]byte, error) value in assignment
-: no required module provides package github.com/dvyukov/go-fuzz/go-fuzz-dep; to add it:
	go get github.com/dvyukov/go-fuzz/go-fuzz-dep
typechecking of ./test/ failed
```

 I was able to check out this SHA 38e0cae and it is working as expected. This was the commit which 

From then to now there are a few things that are an issue.
- a mod reference to this is missing  `github.com/dvyukov/go-fuzz v0.0.0-20210914135545-4980593459a1`
-  The `func` signature had to be changed. 
```
  generate.Read = func(bool) func() ([]byte, error) {
      return func() ([]byte, error) {
               return data, nil
           }
       }
```
I was able to make some fixes https://github.com/sigstore/cosign/compare/main...naveensrinivasan:naveen/feat/fuzzing
but it is not compiling.

```
go-fuzz-build -libfuzzer ./test/
failed to execute go build: exit status 1
/run/user/1000/go-fuzz-build4093939785/gopath/src/github.com/sigstore/cosign/pkg/cosign/tuf/client.go:55:12: pattern repository/*.json: no matching files found
```

**Comment by naveensrinivasan** [comment]
cc @priyawadhwa

**Comment by naveensrinivasan** [comment]
This is the reason it is broken https://github.com/dvyukov/go-fuzz/issues/326

**Comment by priyawadhwa** [comment]
Yah it seems like this has been an issue for a few months with no plans for a fix in go-fuzz (https://github.com/dvyukov/go-fuzz/issues/326#issuecomment-884605930)

Since we need the `go:embed` directive, it might make sense to remove fuzzing for now? 😞

**Comment by naveensrinivasan** [comment]
I agree, probably do it when `go 1.18` which has built-in support for fuzzing.

**Comment by naveensrinivasan** [comment]
Fixed by https://github.com/sigstore/cosign/pull/1020
