### ISSUE TITLE
Change the verify attestation implementation

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1012]
Right now when using the verify-attestation command, only the predicate is passed to the verification policy. This is nice, but has a few issues:

* It loses the predicate type itself. This is in the attestation header, but could be useful in policy.
* It makes the commands hard to use separately cosign verify-attestation with just a key will output the full attestation to stdout. This should be usable directly with "cue vet" and the same policy.

**Comment by dlorenc** [comment]
Cc @developer-guy @Dentrax what do you think?

**Comment by Dentrax** [comment]
IIUC, we are currently _unmarshal_ ing the [predicate body](https://github.com/sigstore/cosign/blob/7066f122b8288e5621cf7e3dca600075bb70cd47/cmd/cosign/cli/verify/verify_attestation.go#L168) to pass into [validation steps](https://github.com/sigstore/cosign/blob/7066f122b8288e5621cf7e3dca600075bb70cd47/cmd/cosign/cli/verify/verify_attestation.go#L208-L216), which we do not check the attestation header in current implementation. What we want to here is to validate the entire attestation in policy validation step?

**Comment by developer-guy** [comment]
Yes, @dlorenc, it makes sense. Actually, in the beginning, we (w/@dentrax) were aware of that, but we didn't think that this header might be a valuable thing to validate, so we didn't care about it much. Okay, then, we can pass the Attestation as a whole (body + header) to the validation steps and revise the logic according to that. Is it okay for you, too, @dlorenc? 😋

**Comment by dlorenc** [comment]
Yeah! I think that would be good. I went back and forth on this one too but I think being able to pass the entire thing directly into "cue vet" is the big win.
