### ISSUE TITLE
Cosign "save" and "load" commands

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1015]
We should add some commands to save an image and it's "attachments" to disk in some kind of bundle on disk, and then load that into a remote registry from disk. See this thread: https://twitter.com/sudo_bmitch/status/1457794784135761920

**Comment by dlorenc** [comment]
cc @developer-guy this could be a fun one :)

**Comment by priyawadhwa** [comment]
chatted with @developer-guy, i might give this a go! :)

**Comment by developer-guy** [comment]
I assigned it to you @priyawadhwa. Thank you so much for asking it me first, that was very kind! Good luck with it. We can't wait to see the results! 🚀

**Comment by dlorenc** [comment]
What's left here @priyawadhwa? This one would be great for the next release.

**Comment by priyawadhwa** [comment]
hoping to have a PR open by tmrw! just have to hook up the commands to the `layout` package (currently seeing a bug with writing to a remote repo tho so just have to get to the bottom of that)

**Comment by priyawadhwa** [comment]
it might be useful to add support for the layout on disk to `cosign verify` -- maybe something like `cosign verify -key [KEY] [path to image directory]`?

**Comment by haydentherapper** [comment]
Chatted with @priyawadhwa about working on https://github.com/sigstore/cosign/issues/1015#issuecomment-975734697 to add support for verification from disk. I'll be taking a look at adding this!
