### ISSUE TITLE
Secrets should not be stored in the git repository

### ISSUE THREAD

**Issue by hickey** [sigstore/cosign#1023]
**Description**

Currently the secret key used to sign the binaries for a release is stored in `.github/workflows/cosign.key`. This allows a bad agent access to the key and could be used to brute force the password or attempt to recover the password through other means. Once the password is recovered any malicious binary could be replaced and the signature could be regenerated to make it appear that the malicious binary is valid. 

The secret key **should not be** committed to the repository. The contents of the file should created as a secret in the repository settings and then reconstituted as a file during the signing process. Once the signing process is complete the file should be destroyed to prevent the secret from remaining on any of the runner machines. 

Since the key has the potential of being compromised, it is necessary to generate a new key pair to use for all future releases. It would also be advisable to rebuild, resign and re-release all binaries from a reasonable point in time (I would say from the v1.0.0 release).

**Comment by dekkagaijin** [comment]
That key (`.github/workflows/cosign.key`) hasn't been used for any recent release. The current actual signing key lives in GCP KMS: https://github.com/sigstore/cosign/pull/427

**Comment by hickey** [comment]
Oh, that makes me feel a lot better! Thanks for clarifying.
