### ISSUE TITLE
More information about the certificate during verify operations

### ISSUE THREAD

**Issue by shibumi** [sigstore/cosign#1046]
**Description**

Right now, cosign prints the following information when invoking `verify-blob`:
```
❯ COSIGN_EXPERIMENTAL=1  cosign verify-blob mnemonic-0.3.1.tar.gz --signature mnemonic-0.3.1.tar.gz.sig
Certificate is trusted by Fulcio Root CA
Email: []
Verified OK
tlog entry verified with uuid: "228527476f82c59641e27b8fb9b32f5fadbe47cf42c544ea97dc798490c4c14e" index: 853327
```

The Email entry is empty, because this signature got created via a workload identity.
The only way to validate  the workload identity is to retrieve the public certificate via rekor, storing it on disk and examining it with openssl:

```
❯ rekor-cli get --uuid 228527476f82c59641e27b8fb9b32f5fadbe47cf42c544ea97dc798490c4c14e --format json | jq -r '.Body.RekordObj.signature.publicKey.content' | base64 -d > pub.crt
❯ openssl x509 -noout -text -in pub.crt
```

This behavior is way to complicated. I suggest adding more information to the cosign output. The most interesting fields are these two, IMO:

```
            X509v3 Subject Alternative Name: critical
                URI:https://github.com/shibumi/mnemonic/.github/workflows/goreleaser.yml@refs/tags/v0.3.1
            1.3.6.1.4.1.57264.1.1:
                https://token.actions.githubusercontent.com
```

**Comment by asraa** [comment]
Happy to take this! The `1.1` suffixed OID extension will always contain the issuer for any of the OIDC providers. This would be great to output with cosign verification. I think for the URI, maybe cosign should check `EmailAddresses` and then `URI`s if not present.
https://github.com/sigstore/fulcio/blob/60a53fb9423cd03c10d5537619ff86c1c9f688e9/pkg/ca/x509ca/x509ca.go#L105-L126

I think for maintenance in the future we should keep

**Comment by shibumi** [comment]
Hey @asraa sorry for the late reply, this issue is already done with #1047. I just realized that you might want a few changes.
Is the  merged PR sufficient or do we want to compile a new issue with your adjustments? :)

**Comment by asraa** [comment]
It's perfect!
