### ISSUE TITLE
cosigned: Key store support for Cosigned Admission Webhook

### ISSUE THREAD

**Issue by adubey8** [sigstore/cosign#1069]
Cosigned Admission Webhook can be used with generated keys and potentially with K8s secret.
```
# generate a key-pair in Kubernetes Secret
cosign generate-key-pair k8s://[NAMESPACE]/[NAME]
```
but cosigned webhook can't use keys from persisted sources. 
Please add functionality to support keys from other sources like Azure Key Vault, AWS KMS, Google Cloud KMS, Hashicorp Vault. Thanks!

**Comment by dlorenc** [comment]
This makes sense to me!

**Comment by developer-guy** [comment]
Hello @adubey8, thank you for this issue. We did a similar effort in the Kyverno project, please [see](https://github.com/kyverno/kyverno/pull/2607/). But, this leads us to an error when we try to run Kyverno in GKE and use GCP KMS, please [see](https://github.com/sigstore/sigstore/issues/138).  I think we have to consider this before adding this support to cosigned project too. WDYT @dlorenc @hectorj2f?

cc: @JimBugwadia

**Comment by hectorj2f** [comment]
Yes, I like the idea and makes sense to support KMS references.
@developer-guy I believe we could benefit from adding support for the other KMS services, Vault, etc., and add a note in the release notes about known issues. In the meantime, we could investigate a solution for GKE and GCP KMS.
