### ISSUE TITLE
cosigned: Validation failed for imported keys from AKV

### ISSUE THREAD

**Issue by adubey8** [sigstore/cosign#1070]
Since I can't use AKV for cosigned webhook directly as per this request: https://github.com/sigstore/cosign/issues/1069 

I worked around by exporting keys from AKV manually
`az keyvault key download --vault-name $KVNAME -n cosignkey -e PEM -f cosign-akv.pem`

Then I used the public key value in the `cosign-akv.pem` to create the cosigned webhook:
```
helm install cosigned -n cosigned-ns sigstore/cosigned --devel --set cosign.cosignKey=<obtained from AKV> --set cosign.cosignPassword=<dummy value> --set cosign.cosignPub=<dummy value>
```
So helm chart gets installed. (Note: Also reported https://github.com/sigstore/helm-charts/issues/41)
Then I update the label: `k label ns cosigned-ns cosigned.sigstore.dev/include="true" --overwrite`

Finally I apply the deployment yaml with the signed image. But if I do so I keep getting:
```
Error from server (BadRequest): error when creating "nginx-deployment.yaml": admission webhook "cosigned.sigstore.dev" denied the request: validation failed: invalid image signature: spec.template.spec.containers[0].image
```
As per my understanding this should have worked. Let me know if my assumption is wrong or you need more details. Thanks!

**Comment by dlorenc** [comment]
Ah! Which version of cosigned are you running? There was a bug in azure KMS verification with exported keys but we fixed it in the 1.3.1 release.

**Comment by dlorenc** [comment]
Actually - the cosigned version shouldn't matter here. Which version of cosign did you use to sign the images?

**Comment by hectorj2f** [comment]
@adubey8 I noticed you used `helm install cosigned -n cosigned-ns sigstore/cosigned --devel  --set cosign.cosignPub=<dummy value>` the You only need to set the public key. 

Question: Did you use `cosign verify ` to validate the cosignPub was valid ?

**Comment by dlorenc** [comment]
Closing, please reopen if you can repro!
