### ISSUE TITLE
download sbom error MANIFEST_UNKNOWN

### ISSUE THREAD

**Issue by tuananh** [sigstore/cosign#1097]
I'm new to cosign and i'm reading the src code at the moment and trying things out

i want to test download sbom with `cosign download sbom gcr.io/distroless/static-debian11` and i got the following error

looks like the distroless image is signed and i can verified it. however, i can not download sbom. 

```
cosign download sbom gcr.io/distroless/static-debian11 Error: GET https://gcr.io/v2/distroless/static-debian11/manifests/sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom: MANIFEST_UNKNOWN: Failed to fetch "sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom" from request "/v2/distroless/static-debian11/manifests/sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom". main.go:46: error during command execution: GET https://gcr.io/v2/distroless/static-debian11/manifests/sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom: MANIFEST_UNKNOWN: Failed to fetch "sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom" from request "/v2/distroless/static-debian11/manifests/sha256-1cc74da80bbf80d89c94e0c7fe22830aa617f47643f2db73f66c8bd5bf510b25.sbom"
```

**Comment by dlorenc** [comment]
I don't think there is an SBOM for the distroless images right now. cc @loosebazooka

**Comment by tuananh** [comment]
> I don't think there is an SBOM for the distroless images right now. cc @loosebazooka 

Is there any image i could try?

**Comment by loosebazooka** [comment]
Correct. Injecting sbom information via bazel is something we have to figure out

**Comment by dlorenc** [comment]
Closing, this was just an issue with distroless.
