### ISSUE TITLE
 Transfer of ownership of cosign-gatekeeper-provider

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1099]
**Description**

As you might see from the Tweets[^1], we (w/@sozercan @dentrax) developed a new provider[^2] to adapt cosign to OPA Gatekeeper's new feature called ExternalData to make cosign available to Gatekeeper users to verify container image signatures. Furthermore, [@LachlanEvenson](https://twitter.com/LachlanEvenson) already wrote a blog post[^3] about this provider 🤩

Let's move and maintain this repository under the `sigstore` organization if you accept this, WDYT @cpanato @hectorj2f @dlorenc?

[^1]: 🐦 https://twitter.com/developerguyba/status/1463403309394497537?s=20
[^2]: 🐙 https://github.com/developer-guy/cosign-gatekeeper-provider
[^3]: ✍️ https://medium.com/@LachlanEvenson/verifying-container-signatures-on-kubernetes-with-gatekeeper-19a4519c3016

**Comment by dlorenc** [comment]
+1! Do you need your own repo for this or do you want it to be in the same repo here?

**Comment by developer-guy** [comment]
let me try to move this to the sigstore foundation because maybe I've enough permissions to do that, is that ok for you?

**Comment by dlorenc** [comment]
I think you probably have to request it and then someone on the org approves.

**Comment by developer-guy** [comment]
I couldn't find any request page for it, I just hit the transfer ownership button, and it happened. Can you please remove it unless you accept this, I couldn't re-transfer it to me. @dlorenc 

https://github.com/sigstore/cosign-gatekeeper-provider

**Comment by developer-guy** [comment]
The next thing is that maybe we could improve its CI/CD maintenance with @cpanato, would you mind helping me to figure this out 🤩🥳 But, I really want to do the hard work to learn more about maintaining an opensource project😋🙏
