### ISSUE TITLE
how do i automate the keyless signing process in CI?

### ISSUE THREAD

**Issue by tuananh** [sigstore/cosign#1108]
I'm using Dex sitting infront of our corp ldap. i'm trying the experiment keyless feature and wondering how do i automate the keyless signing process in CI? when i do it locally on my machine, i need to sign in via browser.

Thank you in advance

**Comment by dlorenc** [comment]
cc @bobcallaway for Dex. I'm not sure it can be automated fully. What CI provider do you use?

**Comment by tuananh** [comment]
we have Dex set up with our corporate LDAP active directory
