### ISSUE TITLE
Documenting pitfalls of registry usage in `cosign policy init` and `cosign policy sign`

### ISSUE THREAD

**Issue by imjasonh** [sigstore/cosign#1130]
### Background

`cosign policy init` allows users to define a policy around how many signatures and from whom should be considered necessary to consider an artifact as "trustworthy" -- e.g., two or more of [`alice`, `bob`, `carla`] must sign the policy before the signed thing is okay to run in prod. This policy is stored in a content-addressed blob in the registry, referenced by a manifest with a mutable tag.

`cosign policy sign` allows a user to add their signature to the list -- e.g., `alice` has signed the policy, and now only one of `bob` or `carla` needs to sign for the artifact to be used in prod. It does this by reading the policy config blob, adding the new signature details, and writing it back, referenced by the same original mutable tag.

### Problem

Because the policy (who can sign, how many are needed) and the signatures (who has signed so far) are stored in the same blob in the same repository in the same registry, all of `alice`, `bob` and `carla` must have push access to the registry. Other users might have access, either because they're other contributors to the project (e.g., `dave`) or an attacker who's merely gained push access to the registry (`ernest`). In this example, even though his signature isn't necessary to meet the threshold of the policy, `dave` can run `cosign policy sign`, or even just perform registry operations to modify the policy that's referenced by the mutable tag, to add their signatures.

Because the policy config and the signatures are in the same object in the registry, any user that can contribute their signature can _also_ modify the policy config, either to change the set of required maintainers (now [`alice`, `bob`, `dave`]) or lower the threshold of require maintainers. This means an attacker with push access to the repo can change the policy from "two or more of [`alice`, `bob`, `carla`] must sign" to "one of [`ernest`] must sign; here's `ernest`'s signature😈 ". In theory they could also change the `threshold` to `0`, effectively disabling the policy, regardless of who's signed so far. They could also remove other maintainers' signatures.

Without registry push audit logs, it would be impossible to know whether this policy was changed, if those pushes aren't also published to Rekor (which presumably a malicious actor just wouldn't do)

### Proposal 

We should document these pitfalls, and recommend some safeguards against these scenarios:

1. Clients verifying policies should lookup changes to the policy in Rekor, and fail if the latest version seen by Rekor is not the same as the current policy in the registry -- this guards against untracked modifications to the policy in the registry, and keeps Rekor as a transparent source of truth about the history of the policy.
2. Clients verifying policies should lookup changes to the policy in Rekor, and fail* if any change modified the policy config, and didn't just add a signature -- that is, all versions of the policy seen by Rekor have the same `signed` section.
    - *We might _want_ to let users change their policy over time -- e.g., "oh whoops I forgot `dave` should also be allowed to sign; sorry `dave`" -- how can a verifying client detect in general whether the policy edit was not malicious? Was adding `dave` malicious? 🤷 

Thoughts? Is there anything else I'm missing? Where's the best place to document this?

cc @lukehinds @jyotsna-penumaka (for sget side) @asraa

**Comment by lukehinds** [comment]
Thanks @imjasonh good to go over this topic. 

It's vital that we reject anything not in rekor, I have a section in the proposal document about this.

![image](https://user-images.githubusercontent.com/7058938/144663843-3134b3ad-b1be-47fb-aa0d-3a934b431b9b.png)

The other option outlined is a kind of spin on known_hosts, but this is less useful as many sget operations will run within an unattended environment (CI) which is ephemeral. 

I do wonder if there are other TUF principles we can leverage here to provide a more robust policy management.
