### ISSUE TITLE
use pinned SHA of GitHub Actions instead of branch name or version

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1134]
**Description**

 In GitHub Actions (GA) there is a security consideration related to 3rd party GA, so, GitHub recommends using Pinned SHA of the 3rd party GA instead of using branch name or version of GA.

There are already side projects that ensure that like the following:

* https://michaelheap.com/ensure-github-actions-pinned-sha
* https://michaelheap.com/improve-your-github-actions-security/

**Comment by haydentherapper** [comment]
This is done.
