### ISSUE TITLE
Add support for syft SBOMs to cosign

### ISSUE THREAD

**Issue by samj1912** [sigstore/cosign#1136]
**Description**

syft is a popular SBOM scanner/creator. It has it's own SBOM format that is used with Grype which is an open source vuln scanner. We should also support syft as a format apart from cyclonedx/spdx.

**Comment by caarlos0** [comment]
fwiw, this is happening in goreleaser, so you could probably integrate it to the release process (I can open a PR once its shipped on goreleaser)

https://github.com/goreleaser/goreleaser/pull/2648
