### ISSUE TITLE
Messaging around key storage

### ISSUE THREAD

**Issue by lukehinds** [sigstore/cosign#1152]
I think we should evaluate our messaging around key storage and encourage users away from questionable practises such as storing long term private keys in secrets / on disc and alike. We should instead start to pivot towards recommending folks use Keyless or a KMS, HSM etc.

Looking at the [github blog yesterday](https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/#so-how-does-container-signing-with-github-actions-work), the first example outlined storing a private key (with no passphrase) in a SECRET. In many ways sigstore was started to address this sort of situation, and keyless was / is the killer feature to address the hazards with key management and the risks of key compromise of long term keys.

No fingers being pointed here, we are still a young project in the greater scheme of things,  but as keyless starts to make its first steps out of experimental, I recommend we amend documentation to carry warnings about the possible risks of storing private keys in such manner and when we can, encourage & educate developers / users onto a different and perhaps safer path.

cc @dlorenc @mattmoor @bobcallaway @dekkagaijin et al

**Comment by mattmoor** [comment]
A somewhat orthogonal, but similar thing we have been discussing (on/off for a while) is allowing folks to sign tags (vs requiring digests).

I believe at a minimum using tags should carry a warning, but eventually we may even want to require an additional flag to support them.

**Comment by dlorenc** [comment]
Something else to keep in mind is that even when fulcio/rekor come out of EXPERIMENTAL, we still don't have a great story for using them with private repos and artifacts. We'll need to be very clear on that messaging too - we don't want surprises for people using our tooling to then find out what data has been "leaked" into the logs.
