### ISSUE TITLE
Cosign crashes when password input is requested from terminal in Windows

### ISSUE THREAD

**Issue by gjirm** [sigstore/cosign#1153]
On Windows when password should be read from terminal, application immediately crashes with the following error:

```
Enter password for private key:
Error: The handle is invalid.
main.go:46: error during command execution: The handle is invalid.
```
For example when running these commands:

```
cosign generate-key-pair
cosign sign --key cosign.key ...
```

I think it is related to the bug #862 I previously reported.

### My environment

- Windows 11 (21H2 - build 22000.318), Windows 10 (21H2 - build 19044.1348)
- cosign v1.4.0
- Window Terminal  v1.11.2921.0
  - native cmd.exe
  - PowerShell 7.2.0

**Comment by dekkagaijin** [comment]
@gjirm I wasn't able to reproduce the issue. Would you be able to add a test case to https://github.com/sigstore/cosign/blob/main/test/e2e_test.ps1 that provokes the bug?

**Comment by gjirm** [comment]
> @gjirm I wasn't able to reproduce the issue. Would you be able to add a test case to https://github.com/sigstore/cosign/blob/main/test/e2e_test.ps1 that provokes the bug?

@dekkagaijin Unfortunately, I don't know how to add a test case, because it only happens to me if I run the command without entering a password (via a environment variable or via a pipe). See example below for `cosign generate-key-pair`:

![cosign_bug_1153](https://user-images.githubusercontent.com/32864045/145793598-b490904e-69eb-41f8-9727-b858dc88401a.gif)

**Comment by jowko** [comment]
I also have similar issue. I use Windows 10 Pro. I downloaded v1.5.1 version of cosign.
When I run `cosign generate-key-pair` in PowerShell/cmd i get such thing:
```
Enter password for private key: Error: The handle is invalid.
main.go:46: error during command execution: The handle is invalid.
```
When I run the same command in git bash, then bash hangs and I need to kill this command:
{code}
$ cosign generate-key-pair -d

{code}
Providing password via environment variable resolves this issue.
