### ISSUE TITLE
Log verification for expired roots/frozen logs

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#1155]
After rotating the Fulcio signing certificate or freezing a Rekor shard, we need to consider how we will handle verification of old entries in the logs.

To consider:
* Discovery of expired targets
* UX around verification with expired targets
* Offline entry verification
* Verifying >1 year old entries/packages

cc @asraa

**Comment by dlorenc** [comment]
I think ideally we'd somehow start treating the fulcio roots the same way we treat intermediate and leaf certificates today. They "chain" back up to the TUF root, so we'd need to pack the fulcio root cert into the "bundle" alongside the timestamp. As long as we can verify that the certificate was valid at the point the signature was created, we're good. We could do this by checking the time on the TUF root, or by checking the validity on the cert itself (we could make sure this matches the TUF root at TUF signing time).

Does this make any sense?

So a sign would look like:

* generate a key pair
* get it signed by the Fulcio root in a cert
* package that cert and the fulcio root together into the bundle
* get all of that timestamped and put into the log

For verification:

* extract the root cert and timestamp from the bundle
* make sure these were valid at the time of the signature using the TUF root
* check the leaf cert (again making sure things were valid at the time of the signature)
* check the signature itself

done!

**Comment by asraa** [comment]
> make sure these were valid at the time of the signature using the TUF root

How do we do this though? TUF gives us a picture of the chained previous `x.root.json` and a view of the current `targets.json`, snapshotted and timestamped. I think we would need to pull the versions of `targets.json`, `snapshot.json` and `timestamp.json` that were valid at the time of signature creation.

That is, unless, a TUF targets contained *all* the previous root certificates we've ever used.

**Comment by dlorenc** [comment]
> Maybe I'm missing something: maybe you mean we package the cert, fulcio root, and targets.json. Then we make sure that an `x.root.json` signed off on the targets.json in the bundle.

Ah I wasn't smart enough to suggest this, but I think that would work too!

Yeah I assumed for old entries we'd need to walk back and find the correct TUF root for that time. I kinda thought we had to do that already though - to validate that the current TUF root is actually correct I though we needed to walk the chain back to the initial root.

**Comment by haydentherapper** [comment]
> package that cert and the fulcio root together into the bundle
> get all of that timestamped and put into the log

To save some space, can we put just the fulcio root SKID in the log? When we fetch the signature from the OCI registry, this should contain the cert chain, and we can compare SKID.

> find the correct TUF root for that time

Would this need to be a set of roots, since I assume their validities will overlap?

**Comment by znewman01** [comment]
Hey Hayden can you update status here? I think there's been a bunch of work

**Comment by haydentherapper** [comment]
I'm good with closing this.

* We have some warnings when using verification keys/certs that are marked as non-active.
* When we delete a shard at some point in the future, there's no client work needed - We'll just remove the file from the TUF targets. If we need to do any work to deprecate a target, we can file a new issue in the future, as we aren't going to remove a frozen shard for at least a few years I imagine.
