### ISSUE TITLE
Update wording for experimental flag for github starter workflow

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#1156]
Currently, we warn users in the cosign repo that the experimental features are not yet production ready, for example we may clear the Rekor log without warning and we have no SLO for the managed instances of fulcio and rekor. We should add this warning to the github starter workflow, which uses the experimental flag to enable keyless signing.

Starter Workflow - https://github.com/actions/starter-workflows/pull/1255

**Comment by mehran-sayyah** [comment]
Help me making website

**Comment by mehran-sayyah** [comment]
ci/docker-publish.yml

**Comment by cpanato** [comment]
@haydentherapper i did not quite understand, do we have plans to clear rekor/fulcio logs?

**Comment by znewman01** [comment]
I believe this is obsolete after https://github.com/sigstore/cosign/issues/1384
