### ISSUE TITLE
`tuf_leveldbstore.FileLocalStore()` causes memory leaks

### ISSUE THREAD

**Issue by dekkagaijin** [sigstore/cosign#1160]
https://github.com/sigstore/cosign/blob/9394f855034282711b571604989b85ddfe126b24/pkg/cosign/tuf/client.go#L171

It opens Files which need to be `Close()`'d, but returns an interface which doesn't implement it: https://github.com/theupdateframework/go-tuf/blob/7ded50136bf99d4da098895fb336993abffc9892/client/leveldbstore/leveldbstore.go#L47-L56

**Comment by dlorenc** [comment]
I think this is fixed now.
