### ISSUE TITLE
Kms ux

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#117]
Can we make the string shorter?

Default project, location to global, default key in keyring

**Comment by dekkagaijin** [comment]
probably not :/

The rough UX is common, though. Would probably be worthwhile deciding on a common config format for storing these values, e.g. `~/.gcloud/kms/config.json`

**Comment by dlorenc** [comment]
+1 to piggybacking on gcloud or other configs where we can. There's just way too much mandatory typing right now to be acceptable IMO.

**Comment by dlorenc** [comment]
Closing this, the flags have been unified into -key
