### ISSUE TITLE
"cosign initialize" doesn't work

### ISSUE THREAD

**Issue by rgerganov** [sigstore/cosign#1179]
I am trying to run `cosign` with a local TUF root. My understanding is that I should use the `initialize` command like this:
```
cosign initialize --root /local/tuf/repo/root.json
```
However this fails with:
```
Error: initializing root client: updating from remote TUF repository: updating tuf metadata: tuf: failed to decode timestamp.json: expired at 2021-12-02 15:41:56 +0000 UTC
main.go:46: error during command execution: initializing root client: updating from remote TUF repository: updating tuf metadata: tuf: failed to decode timestamp.json: expired at 2021-12-02 15:41:56 +0000 UTC
```
Running without `--root`:
```
cosign initialize    
Error: updating local metadata and targets: updating tuf metadata: tuf: failed to decode timestamp.json: expired at 2021-12-02 15:41:56 +0000 UTC
main.go:46: error during command execution: updating local metadata and targets: updating tuf metadata: tuf: failed to decode timestamp.json: expired at 2021-12-02 15:41:56 +0000 UTC
```

It appears it always fetch stuff from GCS which has an expired timestamp. I know there is a `--mirror` flag which can override the default GCS location but I don't want to put my stuff of GCS.

**Comment by priyawadhwa** [comment]
cc @asraa might know more about this?

**Comment by asraa** [comment]
Fixed now -- cosigns updated with the latest root, but GCS isn't synced. I'll make a fix PR to auto-update it and tag you

**Comment by rgerganov** [comment]
But why do we need GCS in the first place? Why it's not possible to use local TUF root?

**Comment by asraa** [comment]
> But why do we need GCS in the first place? Why it's not possible to use local TUF root?

`cosign initialize` is a manual fetch. You don't have to run it at all, you use the local TUF root during a cosign verification. `cosign initialize` is just our system of allowing users to manually updating/downloading in case they want to verify with a remote.

**Comment by rgerganov** [comment]
I am not sure I understand, so I will describe what I am trying to achieve.
I have a local instance of Fulcio and CT log. When I experiment with keyless signing, I am getting an error which says that SCT signature received from Fulcio cannot be verified. This is because cosign is using `ctfe.pub` from its embedded TUF repo. I want to change the TUF repo and provide my own `ctfe.pub`. I thought the way to do this is with `cosign initialize`. Is this correct?

**Comment by asraa** [comment]
Ah, sorry, didn't realize you wanted your entire own root!

Yes, you are correct in using `cosign initialize`. You actually need to provide you own entire TUF root -- that would mean 
`cosing initialize --root $YOUR_ROOT --mirror $YOUR_MIRROR`

where your_root is your own trusted root.json and mirror is the corresponding TUF repository, a collection of metadata. It is expecting a `timestamp.json`, `snapshot.json`, `targets.json` and `root.json` and the target files. 

>  I know there is a --mirror flag which can override the default GCS location but I don't want to put my stuff of GCS.

No one else has asked me to do this which is why I haven't but I can update this so `mirror` can also point to a local filesystem or can fetch from a server through HTTP. That will be a fairly quick fix (expect by end of day tomorrow). 

On the other hand, are you comfortable setting up your own TUF repository? You may also need to include a rekor.pub by the way, but I can also make it so that if there's no rekor.pub in your repo, we use the embedded rekor.pub target.

**Comment by rgerganov** [comment]
> No one else has asked me to do this which is why I haven't but I can update this so `mirror` can also point to a local filesystem or can fetch from a server through HTTP. That will be a fairly quick fix (expect by end of day tomorrow).
> 
That would be great, thanks!

> On the other hand, are you comfortable setting up your own TUF repository? You may also need to include a rekor.pub by the way, but I can also make it so that if there's no rekor.pub in your repo, we use the embedded rekor.pub target.

Not really, but I am trying :) My end goal is to have local instances of Fulcio, Rekor and CT log and make `cosign` work with them.

**Comment by asraa** [comment]
> Not really, but I am trying :) My end goal is to have local instances of Fulcio, Rekor and CT log and make cosign work with them.

I would be happy to help! I use the go-tuf CLI but the python one's a lot more expressive. Please feel free to ping me on slack and I'll be happy to walk through examples and speak to limitations/ways to do stuff.

**Comment by rgerganov** [comment]
I have added support for fetching TUF root over HTTP with PR #1185. With this I have been able to initialize cosign without using GCS and make it work with my local instances of Fulcio and CT log.
