### ISSUE TITLE
Better docs for cosigned

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1192]
It's kind of hard to discover the usage information for `cosigned`, or even that it exists. I think we should get a page up over at https://github.com/sigstore/sigstore-website and a small quickstart here in this readme.

**Comment by dlorenc** [comment]
The chart and any other installation methods should be on sigstore-website too!

**Comment by dlorenc** [comment]
Oh, and we should link out to all the other policy mechanisms that work (Kyverno, the experimental OPA data provider stuff), anything else too.

**Comment by developer-guy** [comment]
We (w/@dentrax) can take care of that, we always have been loved the documentation issues, so we can create one and send it to you for review.

**Comment by developer-guy** [comment]
Also, the cosigned project is one of the projects that we want to learn more about, so this issue would be a good starting point for us.

**Comment by dlorenc** [comment]
You're the best!

**Comment by dlorenc** [comment]
The page should contain something like:

* a quickstart
* installation (helm and non-helm)
* full detailed usage

We should maintain a separate page (linked from here) that compares cosigned to the other policy engines, including:

* OPA
* Kyverno
* Connaiseur
* any others that work!

If the other engines don't have their own docs, we can host our own too. I think OPA is probably the only one right now - since they require you to run an external data provider thing.

**Comment by hectorj2f** [comment]
@dlorenc I believe we could move what we have from https://github.com/sigstore/helm-charts/tree/main/charts/cosigned. We are currently designing some changes to cosigned as part of the WG action items, so I believe it'd be great to have that page (at least as min action items).

**Comment by hectorj2f** [comment]
@Dentrax @developer-guy Please, let me know if you're already working on this documentation.

**Comment by dlorenc** [comment]
I added a bit more here since filing this: https://docs.sigstore.dev/cosign/kubernetes#cosigned-admission-controller

**Comment by hectorj2f** [comment]
Awesome, thanks @dlorenc.

**Comment by dlorenc** [comment]
I think we can close this one out!
