### ISSUE TITLE
Enforce image signing on AWS ECS

### ISSUE THREAD

**Issue by ckingbailey** [sigstore/cosign#1212]
We have a requirement to enforce image signing on AWS ECR. Any AWS service that tries to run a container should be prevented from doing so if the image does not pass signature verification. All of our container run on ECS. Per [the suggestion on issue 383](https://github.com/sigstore/cosign/issues/383#issuecomment-865957513), I'm trying to run a program that listens for ECS events, verifies the image signature, and kills the container if verification fails. I've been trying to prototype this on Lambda, but I've run into two problems that I believe are deal breakers for using Lambda for this:

- The only way I could figure to run Cosign on Lambda was in a Docker container Lambda, which begs the question, what verifies the signature of the container that the Lambda runs?
- I've found no way to run Docker-in-Docker on a Lambda container, meaning the Lambda can't do `docker login <ecr-repo>` and Cosign can't access the image.

A similar solution I thought of is to run Cosign as a Go package inside a Go lambda. That would still present the problem of how to authenticate the Lambda to ECR. I'm not sure it's possible to run Cosign as a package in Go. Even if it is, no one in the company is a Go developer, and we're not keen to maintain a lone Go function for this purpose. That said, I wouldn't reject the solution out of hand if there was one.
I'm wondering if anyone in the Cosign community has seen image signing enforced on ECS done with Cosign before, and what the architecture looked like. Mainly I'm thinking about where to run the program that will run `cosign verify`, and how it listens for events.

**Comment by dlorenc** [comment]
We finally got something working here! Check out this blog post and code:

https://blog.chainguard.dev/cosign-verify-ecs/
https://github.com/chainguard-dev/cosign-ecs-verify

**Comment by dlorenc** [comment]
Closing since we published a sample.
