### ISSUE TITLE
Support vault transit mounts named something other than 'transit'

### ISSUE THREAD

**Issue by sudermanjr** [sigstore/cosign#1223]
We use multiple transit mounts in our vault, and I would love to be able to tell cosign to use that. I can't seem to find a way to do that, but maybe I'm missing something. 

So essentially supporting the path:
```
v1/<MOUNT NAME>/sign/<KEY NAME>/sha2-256
```

**Comment by dlorenc** [comment]
I think we might already support this with an env var: https://github.com/sigstore/sigstore/blob/587d504f4dc16b2bc55eb7100658149de417eb30/pkg/signature/kms/hashivault/client.go#L115

Does that work for you?

**Comment by dlorenc** [comment]
Going to close this one out, pretty sure the feature is implemented there and documented here: https://docs.sigstore.dev/cosign/kms_support#hashicorp-vault

**Comment by sudermanjr** [comment]
I'll try it out, just got back from vacation. Thanks! I don't know how I didn't find those docs, but now I know where to look. Thanks again!
