### ISSUE TITLE
Do not require multiple Fulcio certs in the TUF root

### ISSUE THREAD

**Issue by rgerganov** [sigstore/cosign#1229]
`cosign` requires both `fulcio.crt.pem` and `fulcio_v1.crt.pem` in the TUF root which doesn't make sense when using local TUF. `fulcio_v1.crt.pem` was added in the embedded TUF in order to support Fulcio v1 but it shouldn't be required when users initialize `cosign` with their own TUF repo.

I will submit a patch which will make `fulcio_v1.crt.pem` optional.

/cc @asraa

**Comment by asraa** [comment]
I suppose this would also be fixed by https://github.com/sigstore/cosign/issues/1224
