### ISSUE TITLE
`cosign verify-attestation --policy` docs don't have working examples

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#1231]
**Description**

I was trying to play with this: https://docs.sigstore.dev/cosign/attestation/#cosign-custom-predicate-type-and-cue-policy

However, I noticed a few things:
1. A mix of `-foo` and `--bar` flags (we should shift to `--bar` exclusively).
2. The given example doesn't work!

Here is an example I was able to get working:
```cue
import "time"

before: time.Parse(time.RFC3339, "2021-10-09T17:10:27Z")

// The predicateType field must match this string
predicateType: "cosign.sigstore.dev/attestation/v1"

// The predicate must match the following constraints.
predicate: {
    Timestamp: <before
}
```

Perhaps things changed from passing the `predicate` to the statement itself?  Regardless, opening this to track.

cc @dlorenc to route to the best person to update

**Comment by dlorenc** [comment]
cc @developer-guy @Dentrax !
