### ISSUE TITLE
What should I expect from the --output-file option?

### ISSUE THREAD

**Issue by Rozzii** [sigstore/cosign#1235]
Hi all!

So I was testing cosing for my use case in a Ubuntu 20 environment. Everything seem to work except that lately I have noticed that there is this option called --output-file and my understanding is that if I would provide a payload name for the --output-file  option then my payload would be generated with the provided name without using the redirection operator.

I have found the original PR that introduced this feature and the motivation noted in the PR seems to support my use-case:
https://github.com/sigstore/cosign/pull/261. 

So my assumption is that this:
`
cosign --output-file="payload" generate localhost:5000/myimage:latest`

would produce the same payload as this:

`cosign generate localhost:5000/myimage:latest > payload`

Output of the "cosign version" command:
GitVersion:    v1.3.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.16.7
Compiler:      gc
Platform:      linux/amd64

But my payload file is empty if I use the --output-file but when I use the redirection then everything looks just fine.

So do I expect incorrect behavior from the --output-file option or should I configure something beforehand ?

Thanks for the answer in advance !

**Comment by dlorenc** [comment]
This is weird! I'm looking into it now.

**Comment by dlorenc** [comment]
This should be fixed now with #1264!

**Comment by Rozzii** [comment]
Thank you @dlorenc !
