### ISSUE TITLE
[cosigned] add image tag as an annotation to a pod

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1239]
**Description**

Once you resolve the digest of an image tag, people might want to know which image I'm actually deploying because when they run `kubectl get pods <pod> -oyaml`, they'll see a digest of an image, so, they might want to know what is the tag equivalent of the digest we resolved. So, let's add an annotation to a Pod to show the tag of an image before resolving its digest.

**Comment by hectorj2f** [comment]
Question: do you want to add an annotation to show the tag associated to the image deployed by a pod ? Shouldn't it be something already ingested by the deployed app e.g.  In Helm you could know that with the chartVersion, appVersion? I feel we want users to stop using tags and rely more on digests.

**Comment by developer-guy** [comment]
I totally agree with you about enforcing people to rely more on digests but TBH people want to see the tag equivalent of a digest when they do troubleshooting via the describe or get -oyaml functionalities.

**Comment by haydentherapper** [comment]
Cleaning up old issues: Cosigned has been moved
