### ISSUE TITLE
Support other Public keys than ecdsa when verifying SCT

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1240]
**Description**

For verifying the SCT cosign seems to assume that public keys are always going to be Elliptical. I also verified that if I spin up an instance of CT Log here:
https://github.com/google/certificate-transparency-go/blob/master/trillian/docs/ManualDeployment.md#key-generation

With RSA keys, then cosign is unable to verify the SCT produced by the CT Log.

The assumption seems to be here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go#L57

And with some debugging magic enabled, it fails:
```
getting signer: getting key from Fulcio: verifying SCT: cannot verify RSA signature with *ecdsa.PublicKey key
```

So, I was planning to add other public key types supported for verification.

**Comment by vaikas** [comment]
I can't assign to myself, but I'll be happy to work on this.

**Comment by dlorenc** [comment]
+1!
