### ISSUE TITLE
Signature and Certificate Files Overwritten During signing when recursive option chosen

### ISSUE THREAD

**Issue by sabre1041** [sigstore/cosign#1257]
When specifying `--output-signature` or `--output-certificate` as part of `cosign sign`, contents are overwritten when specifying `-r`/`--recursive` for signing mutiarch images

Separate files would need to be created for each image being signed

**Comment by sabre1041** [comment]
Putting some thoughts on how this might want to be implemented.

* For non recursive signatures, use parameters provided by the user
* For recursive signatures
    * manifest list image uses the parameters provided by the user
    * Each resulting image appends the architecture and platform as follows
        `<user_provided_input>-<platform>-<architecture>

thoughts?

**Comment by dlorenc** [comment]
That sounds good to me!
