### ISSUE TITLE
OIDC-Issuer flag ignored (Github Actions)

### ISSUE THREAD

**Issue by ckotzbauer** [sigstore/cosign#1258]
**Description**

Hi folks,

I had a strange behaviour while trying to sign a blob via GitHub Actions with keyless-signing. The command seems to ignore the `--oidc-issuer` flag which was set to the GitHub-OIDC-Endpoint and uses the default Sigstore-Issuer instead. I then did the verification-login to sigstore manually. The verification for the received token then failed with the message, that the token-issuer (sigstore) was not the expected one (github).

Cosign-Version: 1.4.1

```
$ COSIGN_EXPERIMENTAL="1" cosign sign-blob --oidc-issuer=https://token.actions.githubusercontent.com --output-signature provenance.json.sig provenance.json

Using payload from: provenance.json
Generating ephemeral keys...
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code SNMG-GQNG in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=SNMG-GQNG
Code will be valid for 300 seconds
Token received!
Error: signing provenance.json: getting key from Fulcio: retrieving cert: oidc: id token issued by a different provider, expected "https://token.actions.githubusercontent.com" got "https://oauth2.sigstore.dev/auth"
main.go:46: error during command execution: signing provenance.json: getting key from Fulcio: retrieving cert: oidc: id token issued by a different provider, expected "https://token.actions.githubusercontent.com" got "https://oauth2.sigstore.dev/auth"
```

When someone needs more information for this issue, please reach out to me!

Thank you all!!

**Comment by bobcallaway** [comment]
If you're running this in the context of a GitHub Action workflow run, you shouldn't have to specify `--oidc-issuer` to leverage the GitHub OIDC Token that is available for the scope of the particular run.

Did you set the correct permission on your workflow definition to make sure the ID token would be made available?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings

**Comment by ckotzbauer** [comment]
okay, so maybe I can omit the `--oidc-issuer` flag, as it runs within GitHub. However, it seems to be ignored even its explicitly set.

The environment is the following:
- GitHub-Action with correct permissions (id-token) calls a workflow via nektos/act and sets the GITHUB_TOKEN as secret.
- The "inner" workflow runs an action with the cosign command, specified above.

I think the Github-Context is lost in this scenario, but the outer GITHUB_TOKEN is reused in the act-workflow.

**Comment by Namanl2001** [comment]
do we have to manually click on the link generated to enter the verification code, for each workflow run? 

if we don't, we're getting this error https://github.com/kyverno/kyverno/runs/4729805789?check_suite_focus=true#step:10:16

**Comment by haydentherapper** [comment]
For anyone who runs into this issue, use the `--oidc-provider` flag to set which provider you want to use.
