### ISSUE TITLE
Consider one-to-one mapping of an invocation to scan result

### ISSUE THREAD

**Issue by marshall007** [sigstore/cosign#1262]
The recent addition of the [`COSIGN_VULN_ATTESTATION_SPEC`](https://github.com/sigstore/cosign/blob/3dd690ea18cd65adbcea2e9ae9686cbb4b2ee428/specs/COSIGN_VULN_ATTESTATION_SPEC.md) supports storing multiple scan results originating from a single invocation. I think it would be more intuitive if we encouraged folks to map a single invocation to a single scan result.

This would not only make it easier to construct the payload, but easier to write and evaluate policy against as well. I think we should discourage concatenating the outputs from multiple scans in a single invocation. Doing so would be inconsistent with what `invocation` is intended to represent as far as I can tell.

Constructing separate vulnerability attestations for different types of scanners makes it easier to write a process that evaluates one or more policies against them. For example, you would download a single, named vulnerability attestation and have some guarantee (or at least a reasonable expectation) that it will contain a result set of a particular schema.

Slack thread for reference: https://sigstore.slack.com/archives/C01PZKDL4DP/p1640878335099100

**Comment by dlorenc** [comment]
cc @developer-guy @Dentrax what do you think?

**Comment by Dentrax** [comment]
+1, that makes sense! It would be better if the the spec mapped single invocation to single scanner. In this case `scanner` field should not an array?

**Comment by dlorenc** [comment]
Yeah I think that's right!

**Comment by jdolitsky** [comment]
Hello all, attempted to resolve this in https://github.com/sigstore/cosign/pull/1268
