### ISSUE TITLE
Refactor into using crypto.Signer interface

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#127]
We have three key types now:

- Certs
- Fixed keys
- KMS

If we add Yubikey support (#108) we'll be up to 4. It's probably time to refactor these out into crypto.Signers.

**Comment by ahmetb** [comment]
Agred. Right now 4 commands ({sign,verify}{,-blob}) accept the same set of key type flags (`-key`, `-kms`).

If we were to have more types e.g. 

- `-google-auth`, `-github-auth`, `-microsoft-auth` (or more generally `-oidc google`)
- `-yubikey` (or `-fido2`?)
- `-hsm`

these flags will appear on all these commands, crowding the space quite a bit. But I guess that's acceptable (and we might be able to group these options together as "KEY TYPES").

Although, I'm inclined to remove `-key STRING_LITERAL` option (ref #71).

**Comment by dlorenc** [comment]
+1, drop the key literal.

**Comment by dlorenc** [comment]
cc @ahmetb - you're working on this right?

**Comment by ahmetb** [comment]
Yeah. Got distracted with pre-refactoring code reading yesterday.

**Comment by dekkagaijin** [comment]
Oof, didn't realize you'd already started working in it :x

**Comment by dlorenc** [comment]
@dekkagaijin I think this is done and can be closed now right?

**Comment by dekkagaijin** [comment]
yup!
