### ISSUE TITLE
TUF: Using custom meta for target identification

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#1291]
**Description**

Right now, we hardcode the name of the TUF targets used for verification, e.g. `fulcio.crt.pem` etc. For users who BYO their own root for sigstore, they must name the target files exactly as we expect.

Instead, I wonder if it's better to use custom meta attached to target names e.g. "sigstore: fulcio" on the targets to indicate that this target should be used for the fulcio root CA in Sigstore

cc @haydentherapper @trishankatdatadog

**Comment by dlorenc** [comment]
I think this was done in https://github.com/sigstore/cosign/pull/1423
