### ISSUE TITLE
TUF: Root status output

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#1297]
**Description**

I'd like to add a command like `tuf root info` that outputs what cosign *thinks* the current root is/should be used for gathering targets, and what the expiration for the timestamp is.

e.g.

```
$ tuf root info

Cosign TUF root status:
* local: <cache path>/embedded root
* remote: default remote (don't have any way to save state otherwise for this field)
* timestamp expiration: YYYY-MM-DD
* targets signed:
  - fulcio.crt.pem
  - rekor.pub
  - ctfe.pub
```

**Comment by asraa** [comment]
cc @haydentherapper @dlorenc @bobcallaway WDYT?

**Comment by haydentherapper** [comment]
This seems useful to help with debugging TUF! Maybe instead of `tuf root`, this could be a part of a debug command? This could also be useful in the future if we add more state and need to help users, like `brew doctor`.
