### ISSUE TITLE
cosign verify doesn't properly validate when Vault used as KMS

### ISSUE THREAD

**Issue by brianluong** [sigstore/cosign#1301]
Hey team!

* I created 2 different keys in Vault. 
* I only used one to sign the image using cosign. 
* However, I'm able to use cosign verify using the other key. 

```
➜  docker-trust-playground git:(main) ✗ cosign sign --key hashivault://my-key bluong/test-image               
➜  docker-trust-playground git:(main) ✗ cosign verify --key hashivault://my-key2 bluong/test-image     

Verification for bluong/test-image:latest --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"bluong/test-image"},"image":{"docker-manifest-digest":"sha256:cf902f10bbaf57e67641e8fbf73dc437afb7f1fb51bb8f9839a46ff7c84f6cae"},"type":"cosign container image signature"},"optional":null}]
➜  docker-trust-playground git:(main) ✗ echo $?
0
```

Interestingly, when I export the public key, verification fails
```
➜  docker-trust-playground git:(main) ✗ cosign public-key --key hashivault://my-key2 > my-key2.pub                               
➜  docker-trust-playground git:(main) ✗ cosign verify --key my-key2.pub bluong/test-image         
Error: no matching signatures:
failed to verify signature
main.go:48: error during command execution: no matching signatures:
failed to verify signature
```

### Other Info
* Key type: ecdsa-p256
* Cosign: 1.4.1
* Vault: 1.9.1

**Comment by dlorenc** [comment]
Cc @developer-guy any guesses here?

**Comment by hectorj2f** [comment]
Okay, I have the feeling the verification has been broken because based on vault verification endpoint "valid=true" should be what we expect as a successful verification

**Comment by blz-ea** [comment]
If replace line [here](https://github.com/sigstore/sigstore/blob/b1a36a4771f1d3abaf40befde88e0cdb6ccffbaa/pkg/signature/kms/hashivault/client.go#L224) with
```go
if isValid, ok := valid.(bool); ok && !isValid {
```

and add `"prehashed":  alg != crypto.Hash(0),` to the request [here](https://github.com/sigstore/sigstore/blob/b1a36a4771f1d3abaf40befde88e0cdb6ccffbaa/pkg/signature/kms/hashivault/client.go#L212)

It does seem to be able verify 

Plus solved issue with `verify-blob` where it verifies all files as `Verified Ok`
to reproduce

```
cosign verify-blob --key=hashivault://my-key --signature=file.sig ./<any arbitrary file>
Verified OK
```

**Comment by hectorj2f** [comment]
@blz-ea Great! I was working on a PR but I saw your PR. Yes, it looks good to me and works.

**Comment by blz-ea** [comment]
@hectorj2f Thank you for the review
Sorry if I cut you with PR. Didn't mean to 😄

**Comment by hectorj2f** [comment]
@blz-ea All good 👍🏻 ! Actually I was about to remove the `prehashed` in sign to fix it.
