### ISSUE TITLE
Attaching SBOMs "--sbom" flag uploads literal filepath if file does not exist

### ISSUE THREAD

**Issue by jdolitsky** [sigstore/cosign#1307]
If I run something like the following:
```
cosign attach sbom "${REMOTE_IMAGE}" --sbom=./sbom.txt
```

and the file `sbom.txt` does not yet exist, the blob uploaded contains the literal string contents `./sbom.txt`.

Ability to upload raw string should be supported (and is via STDIN/`--sbom=-`), but I would expect an error if I'm attempting to load a file and it doesn't exist.

Source seems to be https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/attach/sbom.go#L63

**Comment by hectorj2f** [comment]
@jdolitsky This behavior also happens to `--signature=` parameter for the attach signature command. I am not sure if it should be limited to stdin and files only.

**Comment by jkremser** [comment]
> I am not sure if it should be limited to stdin and files only

imho it should, how would you distinguish between the case where one wants to pass a literal "abcd" and a file called abcd. It only opens a new attack vector as it is implemented right now. This overloaded wannabe smart functionality doesn't do what it is expected if the file is not there.
