### ISSUE TITLE
OIDC client secret is not used

### ISSUE THREAD

**Issue by rgerganov** [sigstore/cosign#1309]
There is command line argument for OIDC client secret (`--oidc-client-secret`) but it is not used. This prevents using `cosign` with OIDC providers (such as Auth0) which require a non-empty secret.

I will submit a PR which fixes this.

**Comment by dlorenc** [comment]
@bobcallaway - can you double check this?

**Comment by bobcallaway** [comment]
We don't require/use a client credentials flow in the `oauth2.sigstore.dev` endpoint because we could not keep the client secret as an actual secret... however if folks are using different providers on their own instances of fulcio, this seems reasonable to me.

**Comment by asraa** [comment]
@rgerganov Does this actually work? This option is confusing because on the sigstore/sigstore side, it is unused. 

related https://github.com/sigstore/cosign/issues/1739

**Comment by hectorj2f** [comment]
@asraa I have recently used and it worked for me.

**Comment by asraa** [comment]
Interesting, thanks! I must be missing something then within the oauth2 libraries for usage.

Mostly trying to figure out how to detect whether it was used or not. Perhaps I solve my related issue in cosign.
