### ISSUE TITLE
Support for other KMS systems

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#131]
AWS, Azure, more!

**Comment by dlorenc** [comment]
Help wanted: anyone who has credentials or billing accounts for these!

**Comment by dlorenc** [comment]
From https://github.com/smallstep/certificates/tree/master/kms

**Comment by RichiCoder1** [comment]
I might be interested in taking on either AWS KMS or Vault (have access to both)

**Comment by lukehinds** [comment]
vault would be awesome @RichiCoder1 !

**Comment by dlorenc** [comment]
Yes! Let me know if I can help. The code has actually been refactored over to here now: https://github.com/sigstore/sigstore/tree/main/pkg/kms

**Comment by RichiCoder1** [comment]
Took a swing at vault, luckily not too bad: sigtore/sigstore#44

**Comment by dlorenc** [comment]
Vault is done now. @RichiCoder1 are you still thinking of adding AWS support?

**Comment by RichiCoder1** [comment]
I am! Should be reasonably simple, just might take me a bit longer to get to it.

**Comment by cpanato** [comment]
will implement for Azure -> https://github.com/sigstore/cosign/issues/399

**Comment by codysoyland** [comment]
I am almost finished implementing AWS KMS support -- should have a PR in sigstore by EOD.

**Comment by joelapatatechaude** [comment]
Hey guys, just checking. Is AWS KMS support working at this stage (I am testing with 1.2.1). The documentation (KMS.md) seems to indicate it should, but I am not having much success so far. Just checking before opening some issues.

**Comment by codysoyland** [comment]
@joelapatatechaude AWS KMS support should be working as of v0.6.0. Please file a bug and tag me if it is broken.

**Comment by dmeibusch** [comment]
Created #1194

**Comment by dlorenc** [comment]
Closing since we have a bunch now and separate bugs for individual ones remaining!
