### ISSUE TITLE
enable CodeQL on all PRs, not just code on main

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/cosign#1324]
Tracking issue for:
- [ ] https://github.com/sigstore/cosign/security/code-scanning/67

**Comment by dlorenc** [comment]
I'm going to push back a bit here. In my experience this isn't useful enough as a presubmit to justify the time it takes to run, at least for Golang. 

A few minutes here and there doesn't sound like a lot, but they do add up over time. I'm personally fine running this check after merges. I'd feel differently if the check caught more issues, but we just haven't seen any real value from it here.
