### ISSUE TITLE
GitHub OIDC CI test panic: error retrieving CT public key

### ISSUE THREAD

**Issue by imjasonh** [sigstore/cosign#1331]
**Description**

```
retrieving trusted root; local cache may be corrupt: updating from remote TUF repository: updating tuf metadata: tuf: unexpected file size: snapshot.json (expected 1656 bytes, got 1657 bytes)
121
panic: error retrieving CT public key
```

Full log: https://github.com/sigstore/cosign/runs/4829926117?check_suite_focus=true

This workflow runs nightly, and just started failing today: https://github.com/sigstore/cosign/actions/workflows/github-oidc.yaml

**Comment by dlorenc** [comment]
Maybe a flake? It passed after that: https://github.com/sigstore/cosign/actions/runs/1705932783

**Comment by imjasonh** [comment]
Maybe. It also failed in my fork, which is how I found out about it: https://github.com/imjasonh/cosign/actions/runs/1703121145

I'd love to understand better how that happens, at least. If anybody has any ideas that'd be helpful.

**Comment by dlorenc** [comment]
The error appears to be:
![image](https://user-images.githubusercontent.com/1714486/149777857-36fcbf9a-339f-4e02-b934-e4bef60e03c9.png)


The only time I've seen that "off-by-one" style thing is on windows where `\r\n` characters were getting auto-swapped in for `\n`s...

cc @asraa @haydentherapper any ideas here?

**Comment by jbpratt** [comment]
I also saw this a few minutes ago https://github.com/ContainerCraft/kmi/runs/4907414391?check_suite_focus=true
```
  cosign sign --recursive docker.io/containercraft/${FLAVOR//-/:}
  shell: /usr/bin/bash -e {0}
  env:
    FLAVOR: debian-11
    COSIGN_EXPERIMENTAL: 1
    REGISTRY_AUTH_FILE: /tmp/podman-run-1001/containers/auth.json
Generating ephemeral keys...
Retrieving signed certificate...
retrieving trusted root; local cache may be corrupt: updating from remote TUF repository: updating tuf metadata: tuf: unexpected file size: snapshot.json (expected 1657 bytes, got 1659 bytes)
panic: error retrieving CT public key

goroutine 1 [running]:
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.getCTPub()
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:47 +0x13a
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.verifySCT({0xc0003ae000, 0x490, 0x7c0}, {0xc000d7aff0, 0xe6, 0xe7})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:57 +0x45
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.NewSigner({0x2a6a1b0, 0xc00005e0d0}, {0xc000810680, 0xc0003b7658}, {0x25c55dc, 0xc00000e020}, {0x258984f, 0x1}, {0x2a24060, 0xc0003c71f0})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:79 +0x8d
github.com/sigstore/cosign/cmd/cosign/cli/sign.keylessSigner({0x2a6a1b0, 0xc00005e0d0}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:402 +0x1ab
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignerFromKeyOpts({0x2a6a1b0, 0xc00005e0d0}, {0x0, 0x203000}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, ...}, ...})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:425 +0x128
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignCmd({_, _}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...}, ...)
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:117 +0x245
github.com/sigstore/cosign/cmd/cosign/cli.Sign.func1(0xc000924500, {0xc00090dd40, 0x1, 0x2})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign.go:92 +0x3d6
github.com/spf13/cobra.(*Command).execute(0xc000924500, {0xc00090dd20, 0x2, 0x2})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000918000)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/main.go:45 +0x4c
Error: Process completed with exit code 2.
```

**Comment by asraa** [comment]
Huh, looking into this right now. Very odd to me that it would be flakey

**Comment by dlorenc** [comment]
Have we seen this again since? I've seen some flakes but they're all in the Windows unit test filesystem stuff.

**Comment by jbpratt** [comment]
I haven't seen this again looking back at the last ~30 jobs (within 7 days).

**Comment by dlorenc** [comment]
Oof, oh well :( I'll close for now.

**Comment by madchap** [comment]
Sorry for necroposting here, but might still be seeing this.. simply followed the edx course for sigstore, and got that same error message at https://github.com/madchap/django-keyless-signing/actions/runs/3756664075/jobs/6384663529#step:7:35

**Comment by znewman01** [comment]
@madchap: IIUC you're pinning to Cosign 1.4.1: https://github.com/madchap/django-keyless-signing/blob/c0ab14477ad10a6fae8e04c7efadbc693143fff8/.github/workflows/docker-publish.yml#L29


Do you see this if you use a newer version, like 1.13.1?

**Comment by madchap** [comment]
Thanks @znewman01, works [well](https://github.com/madchap/django-keyless-signing/actions/runs/3763861090/jobs/6397742264) then :)
