### ISSUE TITLE
Add native Linux package manager support for releases

### ISSUE THREAD

**Issue by strongjz** [sigstore/cosign#1337]
**Description**

Add native packages for installs of cosign, etc. On build systems like AWS CodeBuild and others, instead of having users install Golang then cosign or curl releases from GitHub it would be helpful to install packages native package managers.  

Example: https://netdevops.me/2021/building-and-publishing-deb/rpm-packages-with-goreleaser-and-gemfury/

Goreleaser supports this functionality and even uses it to release [packages of goreleaser](https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L169)

**Comment by dlorenc** [comment]
Nice! Feel free to grab this one @strongjz!
