### ISSUE TITLE
TUF: Use custom metadata to identify TUF target usage

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#1342]
**Description**

Currently, we hardcode TUF targets by name, e.g. `fulcio.crt.pem`. As we rotate logs year by year, we will want to annotate custom metadata about these targets. This will also help users make their own TUF targets without relying on fixed file names.

We should probably include:
* the component the target is used for: (fulcio, rekor, ctfe)
* the dates the target will be valid for or some usage information

c/f this comment https://github.com/sigstore/cosign/issues/1273#issuecomment-1006116223

cc @haydentherapper

**Comment by haydentherapper** [comment]
Taking a look at this as part of #1273.
