### ISSUE TITLE
What are you wondering about?

### ISSUE THREAD

**Issue by Knibbaz** [sigstore/cosign#1344]
**Question**
For my school project I need to show how the verifying process flows from the public key to checking if it matches the .sig in the registry. I use a key-pair generated by cosign for signing images.

I tried to read and understand the cosign code but it didn’t make me wiser. I saw that it took the raw public key and then used UnmarshalPEMToPublicKey(). I found a [link](https://go.dev/play/p/m32BfYEr85) that does the same (didn't check if it comes to the same result). After that I'm getting stuck, I found out that it uses the ECDSAVerifier but couldn't found a tool to manually do this. What's next/after this?

Further questions:
- What is an PEM-encoded standard PKIX format?
- I saw that default cosign generated keys are ECDSA, is this true?
- I know that something is using sha256, but I don’t know what is it. Is it the original digest, the signed checked digest?

I want to know step by step how to go from a public key to checking if this matches with what is stored in the .sig file

**Comment by dlorenc** [comment]
Hey @Knibbaz!

I made a graphviz to try to help here:
![image](https://user-images.githubusercontent.com/1714486/150449672-cb24ef38-7766-4d35-8adc-89ea75811d6a.png)

Does that help?

We do use ECDSA P256, with the sha256 hash algorithm by default.

For the PEM-encoding, this blog post explains it a bit: https://smallstep.com/blog/everything-pki/

In short, a public key pem file is:
* A public key is represented in ASN.1, and encoded into a DER bytestream
* base64 encoded into a string, with some basic line wrapping
* Wrapped in a header `-----BEGIN PUBLIC KEY-----` and footer `-----END PUBLIC KEY-----`

Here's an example:
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEm7o4k/Hef3rGKxe0zl90u5qlidna
LhtjVlqQEAlLKSFTDC1yB8uzsCJeG0S6wwCcXOTQ1T+f29FuLP0MY8Zlgg==
-----END PUBLIC KEY-----
```

To decode this, you'd do the reverse process:

* parse the pem "block", which strips the header and footer and base64 decodes the inner bytes.
* Decode the der bytes into an asn1 object, and unmarshal that to a PKIX type.
* The PKIX type contains an algorithm (ed25519, ecdsa-p256, RSA, etc.) and the raw public key bytes which can be used for verification.

Does that help?
