### ISSUE TITLE
Improve the way PKCE is determined/disable check

### ISSUE THREAD

**Issue by jw-s** [sigstore/cosign#1354]
**Description**

I would like to use `cosign` in `keyless mode` with a custom token issuer - i.e Azure

Azure oauth v1 and v2 endpoints both support PCKE based on Azure documentation but unfortunately as of now doesn't return the required [claim](https://github.com/sigstore/sigstore/blob/main/pkg/oauthflow/pkce.go#L42) mentioned by [rfc8414](https://datatracker.ietf.org/doc/html/rfc8414) which `cosign` relies on in order to continue the auth flow. Based on this RFC, the client should assume that the identity doesn't support PCKE if this claim is ommited.

I understand that PKCE is recommended and will be enforced in oauth 2.1 but i see this being an issue with multiple Identities and was wondering if we could either provide a flag to disable the PKCE check? Open to other ideas and discussions.

**Comment by jw-s** [comment]
cc: @bobcallaway

**Comment by bobcallaway** [comment]
i wrote a quick check to check the provider auth URL against the ones listed in the Azure docs which should be sufficient to bypass the claim check on the discovery JSON (note: it still requires that PKCE is actually utilized in the interactions with the provider)

we still need to bump `go.mod` in cosign to consume a release of `sigstore/sigstore` that includes sigstore/sigstore#246 in order for this to be totally fixed
