### ISSUE TITLE
Considering higher level API vs importing `cmd/cosign/cli`

### ISSUE THREAD

**Issue by saschagrunert** [sigstore/cosign#1380]
**Description**

Right now we're importing the `cmd/cosign/cli` bits of this project into the kuberntes-sigs/release-sdk:
https://github.com/kubernetes-sigs/release-sdk/blob/main/sign/sign.go#L26-L27

I feel a bit uncomfortable with that, because I would expect an API somewhere in `pkg`. Is this the desired intention to use this project or do you think it would make sense to move the logic from the `cli` into something like a higher level API?

In general the code from the `cli` package contains everything we need and provides enough configuration flexibility because it maps the CLI.

**Comment by cpanato** [comment]
cc @dlorenc @mattmoor

**Comment by mattmoor** [comment]
Totally agree.  This is what @dekkagaijin has been working towards, but I think we'd love help if folks are willing/able to pitch in!

**Comment by haydentherapper** [comment]
This is the goal of the ongoing sigstore-go project. We welcome small refactors but won't take on any large refactors of the API at this point.
