### ISSUE TITLE
Windows Unit Test Flake

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1389]
This has been failing about 30% of the time for a week or so now and passing on re-runs: https://github.com/sigstore/cosign/runs/5035173302?check_suite_focus=true

```
--- FAIL: TestReadWrite (0.06s)
    write_test.go:36: appending signatures: error writing layer: rename C:\Users\RUNNER~1\AppData\Local\Temp\TestReadWrite1396159366\001\blobs\sha256\e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8553085564288 C:\Users\RUNNER~1\AppData\Local\Temp\TestReadWrite1396159366\001\blobs\sha256\e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: Access is denied.
```

**Comment by haydentherapper** [comment]
Is there any parallelization with the tests? Could one be removing a file while another tries to read/rename that deleted file?

**Comment by dekkagaijin** [comment]
I remember Windows not playing nice with atomic writes (i.e. file renames). It may not be possible in a friendly way, though in this case we may be able to succeed on failure

**Comment by dlorenc** [comment]
I don't think it's parallelism, and I don't have a Windows machine to test with available. It looks like the error is actually coming from ggcr's test registry. I propose we just open the bug over there and skip this test in Windows untill it's narrowed down in the dependency.
