### ISSUE TITLE
Code coverage metric in CI

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#140]
Hi!

I was peering around CI (yay at signing CI builds!), and wondering whether a code coverage metric would be useful per push/PR to detect coverage regressions on new code. 
https://github.com/sigstore/cosign/blob/ca5a8aa06525cc6a732812aef243eaa7f6bff6ac/.github/workflows/tests.yaml#L3

I'm very new to Go so don't know its extend of coverage profiling (how easy it is to filter files/generate reports), but this would be cool to have!

**Comment by dlorenc** [comment]
Yes! It's actually pretty easy to add coverage, but every continuous reporting system I've seen has been incredibly flaky/problematic. The one in Tekton never seems to work.

I'd be up for trying another one though if anyone has recommendations!

To do it in cosign now, you can run:

```
$ go test -tags=e2e -coverpkg=./... -coverprofile=cover.out ./...
$ go tool cover -html=cover.out
```

**Comment by dlorenc** [comment]
![image](https://user-images.githubusercontent.com/1714486/116797523-3e39bc00-aaac-11eb-9219-c8442e881a29.png)
