### ISSUE TITLE
Publish release YAMLs for cosigned

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1414]
This would make it easier to install directly from CI without needing helm.

cc @n3wscott @mattmoor

**Comment by k4leung4** [comment]
im interested in taking this on.

**Comment by dlorenc** [comment]
cc @puerco @cpanato I think we fixed this right?

**Comment by k4leung4** [comment]
this is done.

**Comment by cpanato** [comment]
yes as kenny said :)
