### ISSUE TITLE
feature: create image policy types and CRDs

### ISSUE THREAD

**Issue by kkavitha** [sigstore/cosign#1417]
Associated doc: https://docs.google.com/document/d/1gBLEOOHWOmvHVsoJbgGU74GdwA6CGxMRp3MAeEB50l4/edit#

Based upon discovery in the referenced doc, create necessary types and CRD to support future work on Image Policy for cosigned admission controller.

Outcome:
* Necessary data types have been defined
* Validation and default values have been established

@mattmoor @coyote240 @hectorj2f 

See also: #1418 #1419

**Comment by mattmoor** [comment]
Here's a sample anatomy from the Knative sample-controller:
 * Type definition: https://github.com/knative-sandbox/sample-controller/blob/main/pkg/apis/samples/v1alpha1/addressable_service_types.go
 * Defaulting logic: https://github.com/knative-sandbox/sample-controller/blob/e0d660a91633d4c48d9ce12359fc1b17a2dbfc0b/pkg/apis/samples/v1alpha1/addressable_service_defaults.go#L24
 * Validation logic: https://github.com/knative-sandbox/sample-controller/blob/e0d660a91633d4c48d9ce12359fc1b17a2dbfc0b/pkg/apis/samples/v1alpha1/addressable_service_validation.go#L26

We also generally use `_lifecycle.go` to capture status manipulations: https://github.com/knative-sandbox/sample-controller/blob/e0d660a91633d4c48d9ce12359fc1b17a2dbfc0b/pkg/apis/samples/v1alpha1/addressable_service_lifecycle.go#L27

**Comment by mattmoor** [comment]
When we get to conversion webhooks, that'd go somewhere like this: https://github.com/knative/serving/blob/0b4ef84741509d6d8b67454a09fd15849ba48b93/pkg/apis/serving/v1/configuration_conversion.go#L26 (posting mostly for completeness).

**Comment by coyote240** [comment]
Working thru issues w/ internally generated CA. Basic policy structure and room for validation and defaulting in place. Will be asking for help from Knative team members w/in our org.

Need to add tests.

https://github.com/coyote240/cosign/pull/2/files

**Comment by mattmoor** [comment]
Awesome.  LMK if I can help play matchmaker or if there's anything I can do to help.

**Comment by mattmoor** [comment]
Left some comments on the latest PR, I also have someone eager to help, so maybe we can sync up on where we are on these issues?

**Comment by mattmoor** [comment]
cc @jdolitsky ☝️
