### ISSUE TITLE
feature: integrate policy CRD into admission webhook

### ISSUE THREAD

**Issue by kkavitha** [sigstore/cosign#1419]
Use the created policy/configmaps created in #1417 and #1418 in the webhook to enforce policy

@mattmoor @coyote240 @hectorj2f

**Comment by mattmoor** [comment]
Once we have things in a `configmap`, we have this idea of a "configmap watcher" which is an informer-based way of watching certain configmaps and turning them into an internal form.

There is also a "config store" that supports watching a set of configs through the configmap watch, e.g. https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/cmd/webhook/main.go#L66-L68

... and snapshotting a copy of those configs onto the context that is passed down into webhooks, e.g. https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/cmd/webhook/main.go#L83

Controllers can also be configured with a config store, which is automatically snapshotted onto the `ctx` passed to `ReconcileKind` methods, but I don't think we will need that.
