### ISSUE TITLE
cosign upload blob with identity-token

### ISSUE THREAD

**Issue by godofredoc** [sigstore/cosign#1444]
**Question**
Is it possible to use `upload blob` with an identity token? Looking in the documentation I found this is supported in the sign command with the `--identity-token` flag but could not find a similar option for `upload blob`.

**Comment by dlorenc** [comment]
I think the identity token flag is mostly for signing. What are you trying to upload to?

**Comment by godofredoc** [comment]
I'm try to upload to gcr.io using something like:

```
echo "my first artifact" > artifact
cosign upload blob -f artifact gcr.io/flutter-dashboard-dev/artifact
```
The link returned in the error message suggests to use a service account but I'm trying to upload and sign artifacts from a CI system that uses short lived tokens for authentication.

**Comment by godofredoc** [comment]
This is the full list of steps:

```
gcloud auth login
gcloud auth configure-docker gcr.io
echo "my first artifact" > artifact
cosign upload blob -f artifact gcr.io/flutter-dashboard-dev/artifact
```

The missing step was:

```
gcloud auth configure-docker gcr.io
```
