### ISSUE TITLE
Can IPFS be an option for generating key pairs ?

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1445]
**Question**

I wonder about how [IPFS](https://ipfs.io) can be an option to store public/private key pairs, for example, wouldn't be nice if we can say the following:

```shell
$ cosign generate-key-pair --key ipfs://<something>
```

cc: @dentrax

**Comment by znewman01** [comment]
Storing a private key in IPFS is probably a bad idea :)

But even for the public keys: if you have to remember/distribute an IPFS address what’s the advantage over remembering/distributing the public key manually? This is more-or-less "key fingerprints" from PGP if I understand correctly.
