### ISSUE TITLE
Return multiple rekor entries if looked up during verify-blob

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#1447]
**Description**

In verify-blob with the transparency log enabled, we'll attempt to look up an entry in the log using the search API. This will return the latest signature/cert found for a blob, which may not be the one the user actually is looking for. We should consider improving this UX if multiple entries are found. The relevant codepath is here:

https://github.com/sigstore/cosign/blob/78fb2dc6bcf078fbff5ec14ce5a3a7d5f7c789b6/pkg/cosign/tlog.go#L183

In general we'll also need to better explain the guarantees of the search API. The results returned from it are generally considered "best-effort" and are not guaranteed to be comprehensive. Every result in that API is valid - but the API does not necessarily return every result.

**Comment by znewman01** [comment]
Oh actually https://github.com/sigstore/cosign/pull/1673 *does* add a message clarifying the guarantees. It does so *only* when relevant: that is, the search API *didn't* find a corresponding signature.

This can be closed.
