### ISSUE TITLE
AWS KMS key creation - getting public key: NotFoundException

### ISSUE THREAD

**Issue by Isakofff** [sigstore/cosign#1474]
I create AWS KMS key using the command `cosign generate-key-pair --kms awskms:///alias/cosign_key_test` or `cosign generate-key-pair --kms awskms:///arn:aws:kms:us-east-1:<aws_account_id_hidden>:alias/cosign_key_test` and first run I see the error. Exit code is 1.
```
Error: creating key: getting public key: NotFoundException: Alias arn:aws:kms:us-east-1:<aws_account_id_hidden>:alias/cosign_key_test is not found.
main.go:46: error during command execution: creating key: getting public key: NotFoundException: Alias arn:aws:kms:us-east-1:<aws_account_id_hidden>:alias/cosign_key_test is not found.
```
Then check AWS KMS console and the new KMS key is there.
Then I run that exact command second time and see: `Public key written to cosign.pub`. Exit code is 0.

Is it a bug or maybe I do something wrong?

**Comment by Isakofff** [comment]
It looks like this is a random issue - out of 10 launches only 2 ended with that error. AWS KMS status is OK.

**Comment by haydentherapper** [comment]
Closing as outdated
