### ISSUE TITLE
Update media type for attach attestation command

### ISSUE THREAD

**Issue by spiffcs** [sigstore/cosign#1494]
**Description**

When I was using the `cosign attach attestation` command I saw in the code that layer media type is always going to be `ctypes.SimpleSigningMediaType`.

https://github.com/sigstore/cosign/blob/70d4cce81112331e7e934642372db347165fcc12/cmd/cosign/cli/attach/attestation.go#L71-L74

https://github.com/sigstore/cosign/blob/70d4cce81112331e7e934642372db347165fcc12/pkg/oci/static/signature.go#L38-L42

https://github.com/sigstore/cosign/blob/70d4cce81112331e7e934642372db347165fcc12/pkg/oci/static/options.go#L38-L42

Per the specification [here](https://github.com/sigstore/cosign/blob/main/specs/ATTESTATION_SPEC.md), I was wondering if I could make a change so that the media type can be changed in this constructor. When the `cosign attach attestation` command is used I believe that the type should be `application/vnd.dsse.envelope.v1+json`

If this is not correct I can close this issue. If this does need follow-up I can create a PR today to update the command to use the correct media type.

Thanks again!

**Comment by dlorenc** [comment]
It looks like this is indeed a bug! A fix would be welcomed.
