### ISSUE TITLE
A Harbor with Cosign Probelm:  Get "https://offlineharbor.com/v2/": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by neblen** [sigstore/cosign#1505]
**Question**

I want to sign images in harbor by cosign.I build harbor offline by using openssl which can provide personal CA.So I want to know how to solve this problem。
```
Enter password for private key: Error: signing [offlineharbor.com/public-test2/algorithmloader:v1]: accessing entity: Get "https://offlineharbor.com/v2/": x509: certificate signed by unknown authority
main.go:46: error during command execution: signing [offlineharbor.com/public-test2/algorithmloader:v1]: accessing entity: Get "https://offlineharbor.com/v2/": x509: certificate signed by unknown authority
```

**Comment by dlorenc** [comment]
Depending on your OS you might be able to use the `SSL_CERT_FILE` or `SSL_CERT_DIR` env vars to control where cosign will check for certificates: https://go.dev/src/crypto/x509/root_unix.go

**Comment by neblen** [comment]
> Depending on your OS you might be able to use the `SSL_CERT_FILE` or `SSL_CERT_DIR` env vars to control where cosign will check for certificates: https://go.dev/src/crypto/x509/root_unix.go

Thank you for your reply.According to your hint, I put ca.crt  under /etc/ssl/certs path and it works.
