### ISSUE TITLE
Signature stripped when pushing to DockerHub

### ISSUE THREAD

**Issue by javuto** [sigstore/cosign#1549]
**Question**
I have been signing images using `cosign` and those images were in a public AWS ECR repo. Recently noticed that if I want to `docker pull` a signed image and then `docker push` to DockerHub, the digest changes and in the image pushed to DockerHub the signature is gone. Is it normal that docker strips the signature generated with cosign? Thank you!

**Comment by dlorenc** [comment]
The digest shouldn't actually change - but docker won't copy the signatures by default. You can just cosign cp if you want to copy an image and signatures though!

**Comment by javuto** [comment]
Thanks for the quick response! I just tried the `cosign copy` and that worked like a charm. By the way, `cosign` is amazing! 👏 👏

**Comment by theopolis** [comment]
+1, thanks for clarifying and thanks for bringing up this use case @javuto. I wanted to do something similar where the signatures are moved to other repos (`--sig-only`) before the content, so that UIs that present tag lists show the tag content first and signature tags second.
