### ISSUE TITLE
cmd: public-key doesn't make use of COSIGN_PASSWORD if password is empty

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#156]
"cosign public-key -key cosign.key" command is prompting
interactively for a password. I suspect we should probably
add a symmetry here.

**Comment by dlorenc** [comment]
hmm, I can't see why that would be the case. I'll dig in.

**Comment by dlorenc** [comment]
Not reproing for me. The text "enter password" still shows up which is a glitch, but the flow works:
![image](https://user-images.githubusercontent.com/1714486/112240804-0753c900-8c17-11eb-8faf-6b78177e2411.png)

**Comment by ahmetb** [comment]
ok I have a theory, I think we don't distinguish between COSIGN_PASSWORD "set but empty" vs "empty string" :) my password was empty (just pressed return while generating)

**Comment by dlorenc** [comment]
That sounds incredibly likely
