### ISSUE TITLE
What key-value pairs are validated and which are just notes?

### ISSUE THREAD

**Issue by johnterickson** [sigstore/cosign#1567]
In https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/ it shows this sample:
```
      - name: Sign container image with annotations from our environment
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            ghcr.io/your-org/your-repo:some-tag
        env:
          COSIGN_PASSWORD: ""
```

**Does Fulcio sign this *only* if given a GitHub OIDC token for an Actions run of that repo/workflow and ref?**  The other `cosign sign` examples refer to `-a` as "annotations" which to me sounds like not-crypographically-confirmed information.  I do see some logic on the Fulcio side that maybe adds this as "AddtionalInfo": https://github.com/sigstore/fulcio/blob/dcfd3e87755590845de2f55de6c8d48610dbfe96/pkg/challenges/challenges.go#L273

**Comment by dlorenc** [comment]
There's a distinction between what's validated by Fulcio and what's cryptographically signed.

The `- a`s are included in the payload that's cryptographically signed by cosign. These are in the payload itself.

Fulcio issues and signs certificates after validating the OIDC token (in this example). This includes information about the job run itself, and whatever else GitHub provides.

Everything in the certificate is validated by Fulcio, everything in the signature payload is signed and verified by the job author.
