### ISSUE TITLE
Resolve Secrets from CIP into ConfigMap

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1573]
As a follow on to #1562 we need to read the Secrets (which are really just public keys in this use case) and add them into the config-image-policies ConfigMap.

There's couple of questions about this. If a Secret has multiple keys in it, should we cat them all into a single `data` entry in the fields. Related,is it meant that this field can hold multiple keys or just a single key?

https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_types.go#L94

**Comment by hectorj2f** [comment]
I'd vote for using an array of SecretRefs and expecting `data` only contains a single public key.
