### ISSUE TITLE
ClusterImagePolicy pull secrets for fetching when Source is specified

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1575]
We currently have a Source that specifies where to fetch information from:
https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_types.go#L100

But aren't there cases where we would need to specify pull secrets if they live in different repos?

**Comment by hectorj2f** [comment]
@vaikas I believe this issue can be closed https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_types.go#L122.

**Comment by hectorj2f** [comment]
Closing it for now! Please, feel free to re-open it.
