### ISSUE TITLE
cosigned error validation messages could be improved

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#1607]
**Description**

I see three places in the `cosigned` API validation logic that use `ErrGeneric`, which takes a variadic second argument for field names, here is one such place:
https://github.com/sigstore/cosign/blob/8906eff69f8f79d7d463eb042d9e5a65e424fc19/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_validation.go#L31-L33

The error from this shows up as:
```
At least one image should be defined:
```

With the `.ViaField` doing nothing because no fields were supplied to the `ErrGeneric`!

I think that all of the current `ErrGeneric` calls in this file should be changed to use `apis.ErrMissingField`, which will produce a better error message.

cc @vaikas @kkavitha @coyote240

**Comment by cpanato** [comment]
i will work on this
