### ISSUE TITLE
Install docs are out of date or inaccurate

### ISSUE THREAD

**Issue by se3000** [sigstore/cosign#1630]
The install directions on the [documentation site](https://docs.sigstore.dev/cosign/installation/) do not match the install directions [on the readme](https://github.com/sigstore/cosign#installation).

The documentation site gives me this error:
```
$ go install github.com/sigstore/cosign/cmd/cosign@latest
go: downloading github.com/sigstore/cosign v1.6.0
go: github.com/sigstore/cosign/cmd/cosign@latest (in github.com/sigstore/cosign@v1.6.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

The readme instructions work though. Are the readme instructions ok to follow as a user, or intended just for development purposes?

**Comment by dlorenc** [comment]
Ugh, yeah this sucks. It's a duplicate of https://github.com/sigstore/cosign/issues/1555

FWIW I think we should just drop the `go install` method from docs or suggest it only for development. Go install only works if you don't have any `replace` directives in your go.mod file, but sometimes dependency hell can require it :(

**Comment by se3000** [comment]
Ah, I looked for docs issues as duplicates. That one looks like the root problem, I'll close this. Thanks!
