### ISSUE TITLE
FUN.md seems to be broken at Level 11

### ISSUE THREAD

**Issue by MitchellJThomas** [sigstore/cosign#1632]
**Description**

Running cosign (installed via brew) version   
   ____    ___    ____    ___    ____   _   _
  / ___|  / _ \  / ___|  |_ _|  / ___| | \ | |
 | |     | | | | \___ \   | |  | |  _  |  \| |
 | |___  | |_| |  ___) |  | |  | |_| | | |\  |
  \____|  \___/  |____/  |___|  \____| |_| \_|
cosign 

GitVersion:    1.6.0
GitCommit:     4b2c3c0c8ee97f31b9dac3859b40e0a48b8648ee
GitTreeState:  "clean"
BuildDate:     2022-03-03T17:59:06Z
GoVersion:     go1.17.8
Compiler:      gc
Platform:      darwin/amd64

and rekor-cli (installed via go install command) version 
GitVersion:    v0.5.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.17.8
Compiler:      gc
Platform:      darwin/amd64

I found that [the `Level 11` instructions at the `verify-blob`](https://github.com/sigstore/cosign/blob/d0aa73bfdf4b2e0d709f6234ac5eaa4f51f8900b/FUN.md?plain=1#L105) command failed due to a change in the JSON return value in the rekor-cli command fetching both the sig and the cert values.

**Comment by dlorenc** [comment]
Fixed with #1633!
