### ISSUE TITLE
[cosigned] Enforce authority key errors 

### ISSUE THREAD

**Issue by DennyHoang** [sigstore/cosign#1642]
**Description**

With the implementation of https://github.com/sigstore/cosign/pull/1623, we currently only warn on errors and do not actually error out when there are issues with getting and using authority keys so that it does not introduce breaking behavior.

When we enforce the new clusterimagepolicy resource and the authority keys, we should update [these lines](https://github.com/sigstore/cosign/pull/1623/files#diff-506dbced92e7841cdd78058e329145cd4c554d7b7a61837db031cb128e9d73dfR148) to add to `errs` instead of a Warn log.

Tracking that we should enforce fail on errors once full migration to using clusterimagepolicy is done. 

cc: @hectorj2f @vaikas

**Comment by hectorj2f** [comment]
@DennyHoang I am not sure. Why don't we attempt to parse the content of  KeyRef.Data into a ecdsa.PublicKey when creating/update the ClusterImagePolicy resource ? That way we won't need to parse it when validating every single PodSpec.

**Comment by DennyHoang** [comment]
Closing. 
Issue is no longer a problem as errors are propagated up now.
