### ISSUE TITLE
Functional bug: Pulling only first UUID for blob verification without certificate

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#1647]
https://github.com/sigstore/cosign/blob/18d2ce0b458018951f7356db911467a427a8dffe/cmd/cosign/cli/verify/verify_blob.go#L140-L164

In case a cert or key ref isn't passed into verify-blob, we use the FIRST UUID uploaded in rekor for the certificate. IMO, I don't think this is correct behavior -- especially since this supports pinning an expected cert email. The first UUID may not be the expected certificate.

Anyway, I'm not sure that searching by payload without the certificate is great behavior -- at least clients should log that they're doing a best effort search for the signing certificate.

@haydentherapper

**Comment by dlorenc** [comment]
Is this the same issue https://github.com/sigstore/cosign/issues/1447 ?

**Comment by haydentherapper** [comment]
These seem the same.

**Comment by dlorenc** [comment]
+1 on pulling them all, and then also displaying a message explaining the guarantees of the search API. Basically - the results returned are guaranteed to be valid, but we can make no guarantees that **every** valid entry is returned.

**Comment by asraa** [comment]
> Basically - the results returned are guaranteed to be valid, but we can make no guarantees that every valid entry is returned.

Great, right! 

I'll close this issue in favor of that one, and open up a fix PR for more discussion. I think it should display a message as soon as  it reached the experimental case to strongly suggest that passing in a certificate in the CLI.
