### ISSUE TITLE
Assess threat model for in-memory private keys

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#165]
Currently (1) the `generate-key-pair` command generates a private key in-memory
and then writes it to a file (2) the keyless `sign` command also generates a
single-use private key in-memory (to exchange it with a cert from Fulcio).

However we do not zero these slices (and I'm not sure if Go GC makes copies of
these), therefore a subsequent process calling malloc might retrieve a portion
that contains the private key (and the password).

Not sure if this is a credible enough threat because it implies there's a
malicious software running on the signer party's machine (likely also with full
fs access).

See https://github.com/golang/go/issues/21865 for more discussion.

**Comment by dlorenc** [comment]
I'm definitely interested in opinions here or if there is anything we can do better in Go.
