### ISSUE TITLE
Keyless signing clobbers signatures when using image refs with digests

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#1654]
When I `cosign sign` twice then `cosign verify`, I expect to see both signatures; instead, I only see the latter. When signing images referred to by a tag, I *do* see both signatures. To reproduce:

```shell
# requires cosign, jq
export COSIGN_EXPERIMENTAL=1

IMAGE_DIGEST=$(cosign upload blob -f /dev/null ttl.sh/$(openssl rand -hex 8):5m)
echo "Sign the image with GitHub:"
cosign sign --verbose $IMAGE_DIGEST 2> digest.github.log
echo "Sign the image with Google:"
cosign sign --verbose $IMAGE_DIGEST 2> digest.google.log
cosign verify $IMAGE_DIGEST | jq 'map(.optional.Subject + ":" + .optional.Issuer)'

IMAGE_TAG=ttl.sh/$(openssl rand -hex 8):5m
cosign upload blob -f /dev/null $IMAGE_TAG
echo "Sign the image with GitHub:"
cosign sign --verbose $IMAGE_TAG 2> tag.github.log
echo "Sign the image with Google:"
cosign sign --verbose $IMAGE_TAG 2> tag.google.log
cosign verify $IMAGE_TAG | jq 'map(.optional.Subject + ":" + .optional.Issuer)'
```

The output of `jq` is respectively:
```json
[  "znewman01@gmail.com:https://accounts.google.com" ]
```
and 
```json
[ "znewman01@gmail.com:https://github.com/login/oauth", "znewman01@gmail.com:https://accounts.google.com" ]
```

I've attached [the result of `grep '\--> .* https://ttl.sh' *.log` on the log files](https://github.com/sigstore/cosign/files/8344926/logs.txt) (after some tidying).

I have not checked whether this happens in the key-full signing flow.

**Comment by dekkagaijin** [comment]
Equivalent signatures (same public key and annotations) are automatically de-duplicated. This is done to prevent automation from effectively DoSing an image by adding dozens of duplicate signatures.

**Comment by wlynch** [comment]
This feels like a good getting started issue - mind if I poke around this a bit? 👀

**Comment by znewman01** [comment]
Go for it! If you'd like to pair at some point we can set up time for that too.
