### ISSUE TITLE
Allow specifying ImagePullSecrets in ClusterImagePolicies

### ISSUE THREAD

**Issue by tcnghia** [sigstore/cosign#1655]
**Description**

Currently `cosigned` uses ImagePullSecrets through the PodSpec-providing resources (https://github.com/sigstore/cosign/issues/801). However, there is no guarantee that signatures are stored in the same repository of the image (for instance, if `COSIGN_REPOSITORY` was set when signing).

If we can specify ImagePullSecrets in the ClusterImagePolicies, `cosigned` can use them for verification.

**Comment by hectorj2f** [comment]
@tcnghia We are working on adding support to [ClusterImagePolicy](https://github.com/sigstore/cosign/blob/main/pkg/apis/cosigned/v1alpha1/clusterimagepolicy_types.go#L103) where you could specify where to look for the signatures. These changes and others are coming from the following design document https://docs.google.com/document/d/1gBLEOOHWOmvHVsoJbgGU74GdwA6CGxMRp3MAeEB50l4/edit#.

**Comment by tcnghia** [comment]
@hectorj2f I see. Thanks for pointing out. I am not sure if we should close this bug or re-use it to track part of the the design doc implementation? You know better than me about what the right thing to do for the repo, so I'll let you close or leave open as necessary. Thanks!

**Comment by hectorj2f** [comment]
This issue is related to #1651

**Comment by DennyHoang** [comment]
Going to start working on this

**Comment by shawnho1018** [comment]
@DennyHoang  Is there any test bit for 1.9 or when will 1.9 be released? I am trying to use cosigned with GCP's gcr.io with 1.8 but stuck in the permission against private repository (gcr.io). Is there any workaround I could test before 1.9? 
```
Error from server (BadRequest): error when creating "nginx-1.yaml": admission webhook "cosigned.sigstore.dev" denied the request: validation failed: GET https://gcr.io/v2/shawn-demo-2022/nginx/manifests/sha256:61face6bf030edce7ef6d7dd66fe452298d6f5f7ce032afdd01683ef02b2b841: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication: spec.containers[0].image
gcr.io/shawn-demo-2022/nginx@sha256:61face6bf030edce7ef6d7dd66fe452298d6f5f7ce032afdd01683ef02b2b841
```

**Comment by elfotografo007** [comment]
@shawnho1018 Are the signature and the container in the same registry or different registries? If they are in the same registry, have you tried passing a service account with the imagePullSecrets to the Pod Spec?

**Comment by shawnho1018** [comment]
@elfotografo007  Signature and container are in the same registry. 
I am using workload identity way to grant all service accounts in cosign-system with gcr.io privilege. I have not tested imagepullsecret yet and will try it.
