### ISSUE TITLE
verify: empty claim value is not distinguished

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#168]
Suppose I do "cosign sign -a k1=v1 -a k2= IMG". Here k2 exists but empty.

When I run "cosign verify -a k3=" this passes, despite k3 doesn't exist in
the signed payload. This is due to:

    func correctAnnotations(wanted, have map[string]string) bool {
        for k, v := range wanted {
            if have[k] != v {
                return false
            }
        }
        return true
    }

Bug or not?

**Comment by dlorenc** [comment]
Good question! I guess it comes down to expectations. My initial reaction is that this is WAI, but can see how this would be confusing.

Maybe it would be safest to block empty annotations?
