### ISSUE TITLE
go mod vendor does not work (  github.com/hashicorp/vault/sdk/version: //go:build comment without // +build comment ) 

### ISSUE THREAD

**Issue by msmeissn** [sigstore/cosign#1703]
**Description**

go1.16:

go mod vendor 

internal error: failed to find embedded files of github.com/hashicorp/vault/sdk/version: //go:build comment without // +build comment

**Comment by dlorenc** [comment]
That's correct, the hashicorp dependencies seem to have moved on to require go 1.17 style build tags already.

**Comment by msmeissn** [comment]
ok, can confirm go 1.17  worked
