### ISSUE TITLE
cosign + local Rekor instance verification fail with "signedEntryTimestamp: unable to verify"

### ISSUE THREAD

**Issue by chunteck** [sigstore/cosign#1716]
Hi All,

I tried signing and verifying a blob using `cosign` and the public Rekor instance, and there doesn't seem to be any problem. However, when i self host a local Rekor instance using `docker-compose`, `cosign` seems to fail the verification of the blob with this "signedEntryTimestamp: unable to verify" error. Does anyone know why this is happening?

The same problem happens when i sign with a docker image instead of a blob

SUCCESS CASE

Signing with public Rekor instance:
```
COSIGN_EXPERIMENTAL=1 cosign sign-blob --key cosign.key blob.txt
---
Using payload from: blob.txt
Enter password for private key: 
tlog entry created with index: 1915415
MEQCIAk3n+VSJ7fjgqgQOJkHsCwjBUfUGTmYnfn676P7jlBXAiAW9UJLNcVyHLVfFpFbgGibJOQoAX15B59wwoI3yW05Eg==
```

Verifying with public Rekor instance:
```
COSIGN_EXPERIMENTAL=1 cosign verify-blob --key cosign.pub --signature MEQCIAk3n+VSJ7fjgqgQOJkHsCwjBUfUGTmYnfn676P7jlBXAiAW9UJLNcVyHLVfFpFbgGibJOQoAX15B59wwoI3yW05Eg== 
blob.txt
---
tlog entry verified with uuid: "5f92c44adfc85a6937428b4841d3b154c70a7534e145d3e1b6c19cea3ed4b1c3" index: 1915415
Verified OK
```

--------------------------------------------------------------------------------------------------
FAILURE CASE

Installing & running local Rekor instance
```
go install -v github.com/sigstore/rekor/cmd/rekor-server@latest
cd into the rekor folder
docker-compose up
```

Signing with local Rekor instance 
```
COSIGN_EXPERIMENTAL=1 cosign sign-blob --key cosign.key --rekor-url http://localhost:3000 blob.txt
---
Using payload from: blob.txt
Enter password for private key: 
tlog entry created with index: 0
MEYCIQCcEs8PIibNwAbW48vLPpUQw6z3dBrs+Hwp9BfJ0PW9iQIhAMIt6ysX6E8DpsaRaH8UmCd1FvgKA9rOEj0OUHbgI7DJ
```

Verifying with local Rekor instance
```
COSIGN_EXPERIMENTAL=1 cosign verify-blob --key cosign.pub --rekor-url http://localhost:3000 --signature MEYCIQCcEs8PIibNwAbW48vLPpUQw6z3dBrs+Hwp9BfJ0PW9iQIhAMIt6ysX6E8DpsaRaH8UmCd1FvgKA9rOEj0OUHbgI7DJ blob.txt
---
Error: verifying blob [blob.txt]: verifying signedEntryTimestamp: unable to verify
main.go:46: error during command execution: verifying blob [blob.txt]: verifying signedEntryTimestamp: unable to verify
```

**Comment by asraa** [comment]
Hi! 

This is because cosign relies on a TUF root to distribute targets to verify against (this allows us to update in case there's a compromise to one of the signing keys). In order to do this, you'll need to sign off on your own TUF root, after extracting out the rekor public key that you're using.

You can use this script https://gist.github.com/asraa/947f1a38afd03af57c7b71d893c36af0

If you collect the targets into a `targets` folder. You'll need the Fulcio [cert](https://github.com/sigstore/root-signing/blob/main/targets/fulcio_v1.crt.pem), local rekor key, and ctfe [key](https://github.com/sigstore/root-signing/blob/main/targets/ctfe.pub).

You can query your local rekor key with the [endpoint](https://github.com/sigstore/rekor/blob/0fcdf1949397bef7aecb868c41e3fe6bc908a62c/openapi.yaml#L89)

**Comment by chunteck** [comment]
i see, let me try your solution then! Thanks for your assistance

**Comment by chunteck** [comment]
By the way, it seems like i need both the [fulcio_v1.crt.pem](https://github.com/sigstore/root-signing/blob/main/targets/fulcio_v1.crt.pem) and the [fulcio.crt.pem](https://github.com/sigstore/root-signing/blob/main/targets/fulcio.crt.pem) in the targets.

So there is a total of 4 items in the targets folder

**Comment by asraa** [comment]
> it seems like i need both the [fulcio_v1.crt.pem](https://github.com/sigstore/root-signing/blob/main/targets/fulcio_v1.crt.pem) and the [fulcio.crt.pem](https://github.com/sigstore/root-signing/blob/main/targets/fulcio.crt.pem) in the targets.

Oh, thank you! That is a bug. Putting out a fix and will tag. It was intended to be such that at least one would need to be retrieved, and our code requires both on accident.

**Comment by dlorenc** [comment]
I think we can probably just drop the old one now, it's been long enough

**Comment by asraa** [comment]
Done on both accounts: https://github.com/sigstore/cosign/pull/1738
