### ISSUE TITLE
[cosigned] Webhook error when trying to verify an image signed with RSA key 

### ISSUE THREAD

**Issue by oliviergaumond** [sigstore/cosign#1729]
**Description**

To reproduce:
- Sign an image with an RSA key
- Configure cosigned webhook with the RSA public key
- Try to run a pod with signed image

The admission webhook returns an error

The following is found in the webhook logs
`http: panic serving 192.168.172.222:42498: interface conversion: interface {} is *rsa.PublicKey, not *ecdsa.PublicKey\n
`

**Expected behavior**
As cosign supports RSA key, cosigned should also support them

**Comment by hectorj2f** [comment]
Thanks for the issue @oliviergaumond. We’ ll check the weather

**Comment by dlorenc** [comment]
Yeah we probably missed a few refactors to support the genetic Verifier stuff.
