### ISSUE TITLE
Missing arm64 deb download

### ISSUE THREAD

**Issue by tekumara** [sigstore/cosign#1733]
**Description**

In release v1.7.1 there is no arm64 .deb download, see https://github.com/sigstore/cosign/releases/tag/v1.7.1

**Comment by tekumara** [comment]
And the .deb file no longer contains a version number, eg: is now `cosign.deb` not `cosign_${version}_arm64.deb`

**Comment by tekumara** [comment]
FYI the .deb file no longer contains a version number, eg: is now `cosign.deb` not `cosign_${version}_arm64.deb` (which may or may not be an issue)

**Comment by cpanato** [comment]
i see what is the issue, the name of the file was changed in this PR https://github.com/sigstore/cosign/pull/1683

and now looks like that is generating the same name for all archs. will fix that

**Comment by cpanato** [comment]
related to https://sigstore.slack.com/archives/C01DGF0G8U9/p1649463423951579
