### ISSUE TITLE
RFC: Recommend attaching sBOMs as attestations

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#1742]
**Description**

**Goal**

* This RFC aims to describe a recommendation to attach tamper-proof SBOMs using cosign.

Through the execution of a supply chain pipeline a number of metadata documents are constantly generated. One of these metadata documents is the Software Bill of Materials (SBOM). An SBOM reflects what is in a particular build. It provides transparency and visibility into the produced components of the software organizations market and use.

`sigstore/cosign` offers two alternatives to attach a SBOM document to an image:

**Option 1: cosign attach sbom** 

With this command, each individual SBOM is represented as a layer using a standard descriptor. Likewise, in some scenarios, multiple SBOMs may be attached to one container image. Or each SBOM may refer to the image, or to a specific part of it. 

```
cosign attach sbom --type cyclonedx --sbom cyclone-keycloak-1_16 registry/demo/keycloak@sha256:0eac7ab576f65214d176881ea009db8f631913a7c8efccbd82e6d312ca91df11
```

cosign attaches a SBOM document to the keycloak container image in a repository. That SBOM document typically represents the content of the object they are referring to, although under certain circumstances they may relate to the object indirectly. 

This approach still misses a tamper-proof mechanism to increase transparency and trustability of the generated SBOM. In other words, it requires four images one for the former container image, one for the signature of the image, the sbom image, and the signed sbom.

**Option 2: cosign attest -predicate my-sbom-attest** 

This alternative is similar to the previous one, as it attaches the metadata document to the container images. The main difference relies on attaching an [in-toto attestation](https://github.com/in-toto/attestation/blob/main/spec/README.md) to a container image instead of the raw SBOM document. Attestations are a piece of evidence of a specific action in a supply chain, e.g. process, environment, infrastructure. They can contain large amounts of information, but they should contain a summary that can be evaluated easily by a policy engine. Following this approach, the attestations contain the SBOM metadata as part of their Predicate, as explained [here](https://github.com/in-toto/attestation/blob/main/spec/predicates/spdx.md) and illustrated in the following fragment:

```
{
  // Standard attestation fields:
  "_type": "https://in-toto.io/Statement/v0.1",
  "subject": [{ ... }],

  // Predicate:
  "predicateType": "https://spdx.dev/Document",
  "predicate": {
    "SPDXID" : "SPDXRef-DOCUMENT",
    "spdxVersion" : "SPDX-2.2",
    ...
  }
}

```

The following command signs and attaches an attestation to a keycloak container image:

```
cosign attest -predicate my-sbom-attest.json -key ./cosign.key 
registry/demo/keycloak@sha256:0eac7ab576f65214d176881ea009db8f631913a7c8efccbd82e6d312ca91df11
```

In this example, the SBOM is signed ( tamper-proof ) as it comes within an attestation, thereby consumers can validate its authenticity.
Likewise, attestations can easily be used for policy enforcement rather than simply processing SBOM’s content looking for validations.

cc @dlorenc @SantiagoTorres @luhring

**Comment by dlorenc** [comment]
As the original author of these commands, I think this is a good move. At the time there weren't really any SBOM or Attestations happening in practice. I knew it would be confusing but chose to support both ways to see which would catch on and make the most sense.

Signed SBOMs, or Attestations, seem to be the winner! We should recommend them.

I don't really want to remove the unsigned version quite yet since it's still a reasonable stepping stone, and most images today still don't have signatures OR sboms. If your threat model doesn't require signatures, then you still deserve a good SBOM tool. There aren't any others yet, so I like keeping this one around.

**Comment by hectorj2f** [comment]
@dlorenc Great, i share the same thoughts as the “cosign attach sbom” command satisfy some use cases.

Should we add a note in the documentation?
What about adding a warning when using cosign attach sbom? It could suggest to use attestations or signing the sBOM to have a tamper proof document.

**Comment by dlorenc** [comment]
Warning sounds good. "Attaching SBOMs this way does not sign them... If you want to do that, use..."

**Comment by hectorj2f** [comment]
I'll create a PR so it also reflected in the documentation.

**Comment by lumjjb** [comment]
I really like option 2 of using intoto attestation for the SBOM document! SBOM communities do have their own provenance specs, however, I think that having this alternative angle will be helpful to provide some perspective on another way of doing this - which I am in favor of. 


I have a dumb question - would there be a way to encode a URI or descriptor of where an SBOM can be downloaded - trying to think of the use cases outside OCI since the lack of distribution spec is a problem in SBOM right now, this would help solve it.

**Comment by hectorj2f** [comment]
> I have a dumb question - would there be a way to encode a URI or descriptor of where an SBOM can be downloaded - trying to think of the use cases outside OCI since the lack of distribution spec is a problem in SBOM right now, this would help solve it.

I'm trying to think of use cases outside OCI. I feel that using a URI or descriptor falls into the problem of having to trust the location from where you will download the SBOM and its authenticity. 
However there are other ways to share SBOMs by using services that allow to store and organize SBOMs e.g. dependency track. You could also serve the SBOM document as part of the released artifacts in a public repository.

**Comment by lumjjb** [comment]
>I feel that using a URI or descriptor falls into the problem of having to trust the location from where you will download the SBOM and its authenticity.

Would the hash be sufficient to do this? I think we're not looking for downloading these documents as part of the spec requirement for creating the attestation, but additional information that a client can use.

**Comment by asraa** [comment]
> I have a dumb question - would there be a way to encode a URI or descriptor of where an SBOM can be downloaded - trying to think of the use cases outside OCI since the lack of distribution spec is a problem in SBOM right now, this would help solve it.

Right now with option 2 the SBOM is uploaded to the registry as well. Or are you asking if there's a way for cosign to `cosign attest` to a blob? (Currently there's not)

In my spec https://github.com/sigstore/cosign/issues/1743 proposal, i would add an annotation where that URI lives. Nice catch about hash for integrity.

**Comment by lumjjb** [comment]
> Right now with option 2 the SBOM is uploaded to the registry as well. Or are you asking if there's a way for cosign to cosign attest to a non-OCI blob? (Currently there's not)

The later - non-OCI blob! We were thinking like pointing to an s3 or gcs or HTTP URI.

**Comment by asraa** [comment]
> The later - non-OCI blob! We were thinking like pointing to an s3 or gcs or HTTP URI.

Awesome, I want to get non-OCI blob attestations too! Hope to finish this up next week and try a PR to see how implementation goes https://docs.google.com/document/d/1jkdjbGS4AwtqlujoU90sTqEGW5YPdKYZdp8xMfvqHJk/edit?resourcekey=0-GZXZSmZiF5yioCTyOTUpBA#

**Comment by hectorj2f** [comment]
I am closing this issue, as the docs PR has been merged.
