### ISSUE TITLE
Expand the cosigned webhook to support attestations, plus cue policy for CIP.

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1769]
This is a follow on work for the Cosigned API task force. Idea being is to bring parity between 'cosign cli' and being able to specify attestation policies just like we can do with 'verify-attestation' flag.

This document was created as a starting point for the discussion by few folks, @mlieberman85 @mattmoor @hectorj2f 

I've been playing with it, and the policy bits are probably way too verbose because I don't quite know enough of cue to create sensible policies, but at least I was able to create a what I see a real world example demonstrating cases like:
 * need to support multiple attestations
 * need to support an image that must be signed by N different signatures
 * need to support that attestations of same type (say vuln scan) is attested by multiple signatures, and specifying the exact allowed signatures.

This document is a copy of the original cosigned api document, and the changes to it have been made in 'suggestion' mode to hopefully make the differences be easier to review.
https://docs.google.com/document/d/1p51OYNT1Qegc20aIwcchzXbLv7-PN8iip3OHtTOXWew/edit?usp=sharing

**Comment by hectorj2f** [comment]
@vaikas I think it is a great approach ❤️  to build this solution as part of functionalities that can be used by the CLI itself. I like the idea of adding support for matching attestations as part of the same policy definition.

Also if we develop it as a SDK functionality, other integrations could benefit by using it to ensure other type of resources (custom CRs) are also signed/attested using CIPs to define the policies.

We're happy to help here.
