### ISSUE TITLE
Idea: "cosign upload-blob" command.

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#178]
See https://github.com/sigstore/cosign#oci-artifacts

We have upload and sign-blob, we could sort of reverse it!

```
# Upload as artifact
$ cosign upload-artifact cosign.exe gcr.io/dlorenc-vmtest2/exe
Uploading as OCI artifact with media type application/octet-stream...
# Then sign the normal way
$ cosign sign -key cosign.key gcr.io/dlorenc-vmtest2/exe
```

Cons: could be confusing with the existing `cosign upload` command which is used for uploading signatures.

**Comment by dlorenc** [comment]
cc @jonjohnsonjr I think you suggested this yesterday

**Comment by dlorenc** [comment]
cc @awakecoding I'd love your feedback here!

**Comment by hectorj2f** [comment]
@dlorenc Isn't this already supported with `cosign update blob ...`  ?

**Comment by dlorenc** [comment]
Ah yep! We can close this.
