### ISSUE TITLE
Support signing helm charts

### ISSUE THREAD

**Issue by dioguerra** [sigstore/cosign#1802]
I was wondering if we could use cosign to sign helm oci artifacts.
From the docs and what i breafly have read, it appears this tool was created to specifically sign images (because of the dockerReference and dockerManifestDigest).

I was thinking that it should be viable to make this a more broad tool to sign all kinds of artifact manifests, and not only the docker images.
I just tried to cosign an oci:// helm image and this tool seems to work (not sure if i am missing some details).

Maybe we should think of making manifest signing a thing?

**Comment by hectorj2f** [comment]
@dioguerra We are already using cosign to sign helm charts, you can see how we are signing our own helm-charts. https://github.com/sigstore/helm-charts/blob/main/.github/workflows/release.yml#L43. You can get more info here https://github.com/sigstore/helm-sigstore.

**Comment by dlorenc** [comment]
cc @sabre1041 as well

**Comment by sabre1041** [comment]
@hectorj2f we are still leveraging the existing supported method of signing charts (GPG based).

However, given that OCI based charts are just OCI artifacts, you can use cosign directly to target the OCI reference. 

For simplicity, a minimal workflow would be the following:

1. Create a chart

```shell
$ helm  create mychart
```

2. Package chart

```shell
$ helm  package mychart
```

3. Push chart to OCI registry

```shell
$ helm  push <packaged_chart> oci://<registry+namespace>
```

4. Create a cosign private key

```shell
$ cosign generate-key-pair
```

5. Sign Chart/OCI Artifact

```shell
$ cosign sign --key=<key> <registry>/<namespace>/<chart_name>:<chart_version>
```

Then at install time

5. Verify Chart/OCI Artifact

```shell
$ cosign verify --key=<public_key> <registry>/<namespace>/<chart_name>:<chart_version>
```

5. Install Chart

```shell
$ helm install <release_name> --version=<version> oci://<registry+namespace>/<chart_name>
```

**Comment by hectorj2f** [comment]
@dioguerra Would the aforementioned solution work for you ?

**Comment by dioguerra** [comment]
Yes, i belive so. I gave it a try a while back and it worked. Thanks
