### ISSUE TITLE
cosign sign --bundle flag

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#181]
We should have a way to bundle ALL proofs for into the signature object. This requires trusting all the signing keys through our system:

For all modes:
- Rekor trillian key

For keyless mdoe:
- Fulcio root CA
- CT Log key

The signing keys CT log keys will rotate more quickly than the root CA, so we should sign the other public keys with the Fulcio root CA and bake fulcio root CA trust into all the tools.

Then, a bundle could contain:

- The signature itself
- The signed inclusion proof (and timestamp) of the signature in the transparency log
- [Keyless Mode] The public certificate (containing the public key) corresponding to the signature
- [Keyless Mode] The signed inclusion proof of the certificate in the CT log

Combined with the client's Fulcio Root CA, this bundle could verify everything.

**Comment by dlorenc** [comment]
cc @mnm678 @SantiagoTorres

**Comment by dlorenc** [comment]
@trishankkarthik

**Comment by trishankkarthik** [comment]
@trishankatdatadog

**Comment by priyawadhwa** [comment]
I'm gonna start sketching out a design for this, if anyone has ideas or wants to collab let me know!

**Comment by trishankatdatadog** [comment]
> I'm gonna start sketching out a design for this, if anyone has ideas or wants to collab let me know!

Sounds good! How can I help?

**Comment by priyawadhwa** [comment]
@trishankkarthik I'll ping you on Slack and we can start chatting about it!

**Comment by priyawadhwa** [comment]
As a first step, I'm going to implement this for not-keyless since it's way simpler. For this, we just need to add the following as an annotations:
- the signed inclusion proof that the signature was added to Rekor
- the UUID of the entry in the log

& that should be everything we need to verify the entry is in the log without having to actually access it

**Comment by dlorenc** [comment]
Doc here: https://docs.google.com/document/d/1rVuwr0Acvq_0L1FIZn19bwQ5V3oWoEs_5CxX8H_R8Jc/edit?resourcekey=0-3CtYIjkUlZADfYoUwNvjWQ#heading=h.p4l5zh6qb4zs

**Comment by dlorenc** [comment]
Fixed!
