### ISSUE TITLE
`sign-blob --bundle` clobbers `--output-{signature,certificate}`

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#1821]
If I pass all three of `--output-signature`, `--output-certificate`, and `--bundle`, Cosign silently only respects `--bundle`.

```shell
$ cosign sign-blob /dev/null --output-signature /tmp/keyless.sig --output-certificate /tmp/keyless.crt --bundle /tmp/keyless.bundle
[...]
$ ls /tmp/keyless.*
/tmp/keyless.bundle
```

I expect either:

1. I get all three: a signature, a bundle, a cert (preferred)
2. An error from the option parser

Guilty line looks like: https://github.com/sigstore/cosign/blob/e74f180ce697dcde62dbe12f48f1a6a26522ea77/cmd/cosign/cli/sign/sign_blob.go#L86

It appears that `cosign sign` does not support `--bundle`, though I'm not sure why not. CC @priyawadhwa who added it in https://github.com/sigstore/cosign/pull/1306

**Comment by priyawadhwa** [comment]
Hey @znewman01 sorry I missed your ping in this issue! Basically for OCI images the bundle will be stored on the image, so it can be saved locally with `cosign save` and `cosign load` and offline verification will still work. But, this doesn't really work for blobs, so we added in `--bundle` for blobs only. The goal was offline verification for blobs. There's some more explanation in this issue: https://github.com/sigstore/cosign/issues/1193
