### ISSUE TITLE
`--cert-email` doesn't work for keyless signatures

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#1848]
First, sign some blob keylessly:

```shell
$ export COSIGN_EXPERIMENTAL=1
$ cosign sign-blob /dev/null --output-certificate /tmp/null.crt  --output-signature /tmp/null.sig
[...]
```

Now verify:

```shell
$ cat /tmp/null.crt \
        | base64 -d \
        | step certificate inspect - \
        | grep -A1 "Subject Alternative Name"
X509v3 Subject Alternative Name: critical
    email:zjn@chainguard.dev
$ cosign verify-blob /dev/null --cert /tmp/null.crt  --signature /tmp/null.sig --cert-email zjn@chainguard.dev && echo "yay!"
[...]
yay!
```

Looks like it confirmed the subject in my cert! Or did it...?

```shell
$ cosign verify-blob /dev/null --cert /tmp/null.crt  --signature /tmp/null.sig --cert-email evil@hacker.com && echo "that wasn't supposed to happen"
[...]
that wasn't supposed to happen
```

The help for `--cert-email` is:

> the email expected in a valid Fulcio certificate

So I'd expect it to require a matching email. If I'm misunderstanding, I think (1) the help should be updated, and (2) `cosign` should warn if it's going to silently ignore the flag.

**Comment by haydentherapper** [comment]
taking a look

**Comment by haydentherapper** [comment]
Oh that's a subtle bug, good find. When the certificate flag is provided for verify-blob, we're only calling the function to unpack and validate the certificate when a chain is also provided - https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify/verify_blob.go#L124

Compared to when no certificate is provided and the cert is fetched from Rekor, which always calls this - https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify/verify_blob.go#L152-L166 and https://github.com/sigstore/cosign/blob/b649926565859155d11de082830a781338d5f790/cmd/cosign/cli/verify/verify_blob.go#L210

`cosign verify` has the same issue. When a cert is provided, it'll only validate the values of the cert if a chain is provided. If using the experimental mode when a cert is fetched from the OCI annotation, it works as expected.
