### ISSUE TITLE
Add IBM Cloud Container Registry to list of supported Registries

### ISSUE THREAD

**Issue by bainsy88** [sigstore/cosign#1855]
**Description**

I work on the IBM Cloud Container Registry (icr.io) which is a OCI compliant registry and therefore works with cosign. 

I have done some local testing and know that other people have been using it for a little while, so I am happy from my perspective to be added to the  the list. 

If someone on the cosign team needs to test it, before we can added please see our getting started [guide](https://cloud.ibm.com/docs/Registry?topic=Registry-getting-started)  which will give you enough info to get set up to run cosign.

**Comment by dlorenc** [comment]
Nice! Want to send a PR? I don't think we need to test it separately.

**Comment by bainsy88** [comment]
Thanks @dlorenc will get that done now :+1:
