### ISSUE TITLE
Change 'cosigned' name to 'policy-controller'

### ISSUE THREAD

**Issue by adamd-vmw** [sigstore/cosign#1892]
As discussed in https://github.com/sigstore/TSC/issues/9,

`cosigned` will be renamed `policy-controller`

**Comment by adamd-vmw** [comment]
This is to separate the renaming work from the API version bump up and the work to split the controller to its own repo

**Comment by imjasonh** [comment]
So it sounds like there's around three big refactor-ey changes in the immediate pipeline:

1. bump `v1alpha1` -> `v1beta1` (sounds like this is in progress)
2. rename `cosigned` -> `policy-controller`
3. move code out from https://github.com/sigstore/cosign, to https://github.com/sigstore/policy-controller

Do we want (2) to happen before or after (3), or at the same time? Sorry if this has already been discussed and settled.

cc @vaikas

**Comment by adamd-vmw** [comment]
For our purposes, we actually prefer (2) to happen before (3) simply because when we do (3), we have to do a whole internal approval and build process, which we would prefer to work on after we finish our current product release which needs (2).

but that's just for our own purposes/convenience at vmw
