### ISSUE TITLE
Remove CodeQL from presubmits?

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#191]
![image](https://user-images.githubusercontent.com/1714486/112767740-0d162980-8fde-11eb-8847-79a081640201.png)

I've never seen it catch anything, ever, and it takes the longest out of all of our tests.

**Comment by naveensrinivasan** [comment]
I agree, codeql usually does not find stuff. But it is that one time that you miss it catches. Usually, the codeql tests aren't this slow for PR.

But I vote for not removing it. It is a security feature and for this project it is critical. 

Here is an example of it caught an issue https://github.com/ossf/scorecard/commit/b278475af0c79b6c43139934b29a575961d44a37

**Comment by asraa** [comment]
Maybe make this a daily scheduled job rather than PR?

**Comment by naveensrinivasan** [comment]
> Maybe make this a daily scheduled job rather than PR?

But how do you catch bad code in PR?

**Comment by asraa** [comment]
> But how do you catch bad code in PR?

Yeah, it would only be daily. This is only useful if you recommend people work on releases or at least a couple days before latest. I think pinning at latest revisions is bad practice anyway.

Other alternative: only build some portion of the code based on the diff.

**Comment by dlorenc** [comment]
I think we actually already have it daily: https://github.com/sigstore/cosign/blob/main/.github/workflows/codeql-analysis.yml

**Comment by naveensrinivasan** [comment]
> > But how do you catch bad code in PR?
> 
> Yeah, it would only be daily. This is only useful if you recommend people work on releases or at least a couple days before latest. I think pinning at latest revisions is bad practice anyway.

☝️ Sorry, I don't get it.

> Other alternative: only build some portion of the code based on the diff.

**Comment by asraa** [comment]
> Sorry, I don't get it.

If it were daily you can still catch and fix regressions within a short window 1-2 days. As long as people aren't running directly at head this doesn't expose them to the issue.

I see. Looks like it's on both daily and PR.

**Comment by naveensrinivasan** [comment]
> > Sorry, I don't get it.
> 
> If it were daily you can still catch and fix regressions within a short window 1-2 days. As long as people aren't running directly at head this doesn't expose them to the issue.
> 
> I see. Looks like it's on both daily and PR.

Thanks, I understand. That means someone has to manually look at the issue in the Security center and do PR for the fix. If it is missed then we run into an issue of opening a security hole.
