### ISSUE TITLE
upload attestation to an oci registry before adding an entry to tlog

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1936]
**Description**

I got an error while uploading an attestation to an OCI registry but I saw that tlog entry was addeded even if I got an error, so, I think, it should try uploading first and then adding an entry to tlog.

![Screen Shot 2022-05-30 at 20 43 44](https://user-images.githubusercontent.com/16693043/171199479-a78a52ec-5362-4bca-a66e-551934cdaa49.png)

**Version**

cc: @znewman01 @priyawadhwa

**Comment by developer-guy** [comment]
We did some analysis on codebase, I saw that we couldn't gonna make it happen without adding an entry to tlog because we add rekor bundle to the attestaton as you see below;

```go
	// Check whether we should be uploading to the transparency log
	if sign.ShouldUploadToTlog(ctx, digest, force, ko.RekorURL) {
		bundle, err := uploadToTlog(ctx, sv, ko.RekorURL, func(r *client.Rekor, b []byte) (*models.LogEntryAnon, error) {
			return cosign.TLogUploadInTotoAttestation(ctx, r, signedPayload, b)
		})
		if err != nil {
			return err
		}
		opts = append(opts, static.WithBundle(bundle))  <-- we add bundle to the opts
	}

	sig, err := static.NewAttestation(signedPayload, opts...) <-- we use it in here before uploading sig to the registry
	if err != nil {
		return err
	}
```

any thoughts @znewman01 @priyawadhwa

**Comment by znewman01** [comment]
Oh, huh. I suppose that makes sense.

I see a few ways forward:

1. Upload the attestation to the registry *before*, without a pointer to the tlog, then update it!

    - Pros:  Attestation is somewhat useful (though less trustworthy) even without the transparency log.
    - Cons: This may fail if the registry doesn't support mutating tags. It can also fail if something else changed in between.
2. Upload a test artifact.

   - Pros: Should catch *most* cases where the upload would fail.
   - Cons: May leave cruft around, even if cosign tries to clean up after itself (e.g. if the client gets killed).
 3. Do nothing (maybe make the output more clear).
 
     - Pros: easy to implement. I don't think it's a *big* problem if a tlog entry gets created without the corresponding attestation being available.
     - Cons: doesn't fix the problem.
     
 I'd lean towards (3), but I want to hear what you think!

**Comment by developer-guy** [comment]
Yep, agree, it is not a big deal, the most suitable one is 3 for me too. Thanks, @znewman01, for this such an excellent analysis.
