### ISSUE TITLE
How to compile cosigned

### ISSUE THREAD

**Issue by INT2ECALL** [sigstore/cosign#1939]
hello , can i compile cosigned by myself and how to do it

**Comment by INT2ECALL** [comment]
cosigned is admission controller

**Comment by hectorj2f** [comment]
@INT2ECALL You could run `make cosigned` as part of the sigstore/cosign targets in the Makefile. That would compile cosigned. You might also want to use `KO_DOCKER_REPO` or `KO_PREFIX` env variables when publishing the container image.

**Comment by INT2ECALL** [comment]
> @INT2ECALL You could run `make policy-controller ko-policy-controller` as part of the sigstore/cosign targets in the Makefile. That would compile cosigned. You might also want to use `KO_DOCKER_REPO` or `KO_PREFIX` env variables when publishing the container image.

ok

when i read makefile ,i know i can build it from ko thank

**Comment by INT2ECALL** [comment]
> @INT2ECALL You could run `make policy-controller ko-policy-controller` as part of the sigstore/cosign targets in the Makefile. That would compile cosigned. You might also want to use `KO_DOCKER_REPO` or `KO_PREFIX` env variables when publishing the container image.

when i push compile my image i got this error

Error: error processing import paths in "config/policy-webhook.yaml": error resolving image references: PUT https://index.docker.io/v2/le0zh0u/policy-webhook/manifests/--tags: unexpected status code 404 Not Found: 404 page not found

**Comment by INT2ECALL** [comment]
> > @INT2ECALL You could run `make policy-controller ko-policy-controller` as part of the sigstore/cosign targets in the Makefile. That would compile cosigned. You might also want to use `KO_DOCKER_REPO` or `KO_PREFIX` env variables when publishing the container image.
> 
> when i push compile my image i got this error
> 
> Error: error processing import paths in "config/policy-webhook.yaml": error resolving image references: PUT https://index.docker.io/v2/le0zh0u/policy-webhook/manifests/--tags: unexpected status code 404 Not Found: 404 page not found

solve this by git clone this project

**Comment by hectorj2f** [comment]
@INT2ECALL I am closing this issue, as it seems you solved it. Even though the project is not located in a different repository.
