### ISSUE TITLE
GHA failed signing binary (automated via goreleaser)

### ISSUE THREAD

**Issue by georgettica** [sigstore/cosign#1960]
**Question**
I posted this question here, and got redirected to cosign

https://github.com/goreleaser/goreleaser-action/issues/361#issuecomment-1146098674

Feel free to add as much or as little info you can so this issue can be solved

**Comment by asraa** [comment]
cc @haydentherapper anything going on with the SCT verification?

**Comment by haydentherapper** [comment]
This would be because cosign hasn’t been updated. What needs to be updated? Goreleaser?

**Comment by georgettica** [comment]
Commenting as I am not sure @caarlos0  or @haydentherapper sound the root cause

**Comment by caarlos0** [comment]
> This would be because cosign hasn’t been updated. What needs to be updated? Goreleaser?


this seems to be the route cause... so you'll likely have to update your github action to use the latest cosign..

**Comment by georgettica** [comment]
And I've done that.
So I'll.close hopefully it won't show up
