### ISSUE TITLE
Batching multiple key verification

### ISSUE THREAD

**Issue by asraa** [sigstore/cosign#197]
**Description**

Cosign could verify that a signature exists for each (or any) key provided:
`cosign verify -key key1.pub -key key2.pub <image>`

which be default would make sure that a signature exists for each of the provided keys in a single call, for example, the pubkey of the build system and of a maintainer.

(Someone may also want to provide an --any flag, i.e. signed by any of the  keys provided in a single call, but maybe that's functionality left for a deployer.)

* This would mean it *would* be valid to use both key and kms:
`cosign verify -key key1.pub -kms <blah> <image>`
 would mean verify that <image> has a signature for the public key in KMS and `key1.pub`.

**Comment by dlorenc** [comment]
+1 to this!

**Comment by dlorenc** [comment]
This starts to tie into the policy conversation :) I think we decided to leave the CLI at one key but support multiple in the API/cosigned
