### ISSUE TITLE
print cert-extensions if any in verification message

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#1989]
**Description**

In the PrintVerification function, we do not print the cert extensions to the output, it'd be nice to print them if we have any.

Source👇https://github.com/sigstore/cosign/blob/68e8d9375a246a5fbc3607f8a919551164fa8cbf/cmd/cosign/cli/verify/verify.go#L237

**Comment by chipzoller** [comment]
Closed in https://github.com/sigstore/cosign/pull/1626 ?

**Comment by developer-guy** [comment]
> Closed in https://github.com/sigstore/cosign/pull/1626 ?

Yep, closed with #1626

**Comment by developer-guy** [comment]
Thanks @chipzoller for bringing this into my attention 🙋🏻‍♂️
