### ISSUE TITLE
cosign doesn't get image metadata from JFrog Artifactory Enterprise 6.16.0 rev 61600900

### ISSUE THREAD

**Issue by chvasu** [sigstore/cosign#1994]
Hi,

cosign doesn't work for JFrog registry (JFrog Artifactory Enterprise 6.16.0 rev 61600900) that is in-house deployed in our company. **The error details are provided below.**

`root@visubuntu:~/Downloads# ./cosign sign --key import-cosign.key sm-hardened-docker-images.smtools.sentinelcloud.com/base:1.0
Enter password for private key: 
Pushing signature to: sm-hardened-docker-images.smtools.sentinelcloud.com/base
Error: signing [sm-hardened-docker-images.smtools.sentinelcloud.com/base:1.0]: recursively signing: signing digest: PUT https://sm-hardened-docker-images.smtools.sentinelcloud.com/v2/base/manifests/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: MANIFEST_INVALID: manifest invalid; map[description:null]
main.go:52: error during command execution: signing [sm-hardened-docker-images.smtools.sentinelcloud.com/base:1.0]: recursively signing: signing digest: PUT https://sm-hardened-docker-images.smtools.sentinelcloud.com/v2/base/manifests/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: MANIFEST_INVALID: manifest invalid; map[description:null]`

**Using the crane tool**
`root@visubuntu:~/Downloads# ./crane manifest sm-hardened-docker-images.smtools.sentinelcloud.com/base:sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig
Error: fetching manifest sm-hardened-docker-images.smtools.sentinelcloud.com/base:sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: GET https://sm-hardened-docker-images.smtools.sentinelcloud.com/v2/base/manifests/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: MANIFEST_UNKNOWN: The named manifest is not known to the registry.; map[manifest:base/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig/manifest.json]`

**However, Docker manifest works fine.**
`root@visubuntu:~/Downloads/TDI# docker manifest inspect sm-hardened-docker-images.smtools.sentinelcloud.com/base:1.0
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 1463,
		"digest": "sha256:d2e4e1f511320dfb2d0baff2468fcf0526998b73fe10c8890b4684bb7ef8290f"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 30421006,
			"digest": "sha256:125a6e411906fe6b0aaa50fc9d600bf6ff9bb11a8651727ce1ed482dc271c24c"
		}
	]
}`

**I tried alternate way to attach signature by signing with openssl as well. It doesn't work.**
`root@visubuntu:~/Downloads# ./cosign attach signature --signature myimage.b64.sig sm-hardened-docker-images.smtools.sentinelcloud.com/base:1.0
Error: PUT https://sm-hardened-docker-images.smtools.sentinelcloud.com/v2/base/manifests/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: MANIFEST_INVALID: manifest invalid; map[description:null]
main.go:52: error during command execution: PUT https://sm-hardened-docker-images.smtools.sentinelcloud.com/v2/base/manifests/sha256-aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d.sig: MANIFEST_INVALID: manifest invalid; map[description:null]`

**I even deleted the repository in the JFrog and re-created it but still get the same error.**

**Comment by dlorenc** [comment]
You might need a newer version of artifactory, what's the latest one?

**Comment by chvasu** [comment]
Yes, please close this issue. It worked after passing the environment variable (COSIGN_DOCKER_MEDIA_TYPES=1) you mentioned to support legacy registries. Thanks a lot mate. You are awesome.
