### ISSUE TITLE
Add Copy method in pkg 

### ISSUE THREAD

**Issue by gpkmr-genesys** [sigstore/cosign#2017]
**Description** 

Currently, `cosign` has the `copy` command only in `cli`. But it will be very useful if it is included as a shared `pkg` so that it is reusable.

I have an application developed in `go` which authenticates and copies images between 2 private registries using `crane` pkg. Now that our images are signed using `cosign`, I need to add this feature to our app.
I am unable to find a way to copy both image and it's signature data programmatically.

**Comment by gpkmr-genesys** [comment]
@imjasonh - created this as per our conversation in slack

**Comment by haydentherapper** [comment]
Closing out old issues: We're open to refactors of cosign as a package vs as a CLI, though the focus is on a clean room implementation in sigstore-go and bringing those changes into Cosign.
