### ISSUE TITLE
Replication doesn't not replicate signatures along with artifact

### ISSUE THREAD

**Issue by brackend** [sigstore/cosign#2028]
**Local replication did not replicate the cosign signatures from another local repository**

Created a pull replication from one local repo to another local repo on the same Harbor registry.  
The source had several cosign signatures.
Replication worked fine for replicating the image into the new repository.  Problem is the destination repo doesn't see the signatures.  That is the new repo replicates the images but not the signatures

For replication I used "ALL" and also "image".  But same result.
Flatten and not flattened - not that it would matter but you never know.

**Version**

Version v2.5.0-98e1b82f

Documentation:
A key feature of using Cosign with Harbor is the ability use Harbor’s [replication capabilities](https://goharbor.io/docs/2.5.0/administration/configuring-replication/) to replicate signatures with their associated signed artifact. This means that if a [replication rule](https://goharbor.io/docs/2.5.0/administration/configuring-replication/create-replication-rules/) applies to a signed artifact, Harbor will apply the replication rule to the signature in the same way it applies it to the signed artifact.

When replicating between Harbor instances, the target Harbor instance will maintain the link between the signed artifact and its associated signatures. You will be able to see the relationship between the two artifacts in the target Harbor interface, in the same way that you do in the source registry.

When replicating from Harbor to another target registry type, the target registry will not manage the link between the signed artifact and any associated signatures. You will see the subject manifest and signatures as coordinating artifacts under the same repository.

**Comment by brackend** [comment]
Hi,  can anyone help with this?   Right now I don't have access to external registries hence reason I'm sourcing repo in same registry instance.

**Comment by dlorenc** [comment]
This might be a better bug for the harbor issue tracker.

**Comment by brackend** [comment]
Absolutely.  My apologies.  Didn't realize I posted in the wrong one.  Closing.

**Comment by dlorenc** [comment]
No worries! Let me know if there's anything to fix on this end.
