### ISSUE TITLE
Lack of backward compatibility for verify-attestation

### ISSUE THREAD

**Issue by sfzylad** [sigstore/cosign#2034]
**Description**

Images attested with `cosign v1.4.1` (for full output from cosign version refer to the Version section) cannot be verified with `verify attestation` due to the lack of `payloadType` field compatibility when verified with `cosign 1.9.0`.

To reproduce the problem (using cosign 1.4.1):
```
grype -ojson <image>:<tag> > test.cve.result.json
cosign attest --predicate test.cve.result.json --key <key> <image>:<tag>

syft -ospdx <image>:<tag> > test.sbom.spdx
cosign attest --predicate test.sbom.spdx --type spdx --key <key> <image>:<tag>
```

Then using the `cosign 1.9.0`:
```
cosign  verify-attestation --key <key> <image>:<tag>
```

*Output:*
```
Error: no matching attestations:
invalid payloadType https://spdx.dev/Document on envelope. Expected application/vnd.in-toto+json
 invalid payloadType cosign.sigstore.dev/attestation/v1 on envelope. Expected application/vnd.in-toto+json
main.go:52: error during command execution: no matching attestations:
invalid payloadType https://spdx.dev/Document on envelope. Expected application/vnd.in-toto+json
 invalid payloadType cosign.sigstore.dev/attestation/v1 on envelope. Expected application/vnd.in-toto+json
```

*Expected output:*
Cosign should return two attestations.

**Version**

*attesting version:*
```
GitVersion:    v1.4.1
GitCommit:     934567a4c606cf59e6ab17af889b4db3ee0a3f0b
GitTreeState:  clean
BuildDate:     '2021-12-10T16:54:56Z'
GoVersion:     go1.17.5
Compiler:      gc
Platform:      darwin/amd64
```

*verifying version:*
```
GitVersion:    1.9.0
GitCommit:     a4cb262dc3d45a283a6a7513bb767a38a2d3f448
GitTreeState:  "clean"
BuildDate:     2022-06-03T13:47:07Z
GoVersion:     go1.18.3
Compiler:      gc
Platform:      darwin/amd64
```

**Comment by hectorj2f** [comment]
@sfzylad Thanks for the issue. I have a couple of questions. Is there any reason to use 1.4.1 ? Why don't you use the same cosign version for the attestation and verification ?

**Comment by sfzylad** [comment]
@hectorj2f I've encountered this problem trying to verify the attestation that's been created some time ago when version 1.4.1 was the most recent or close to the most recent. The described problem started just after updating.

**Comment by dlorenc** [comment]
Hey,

Sorry about this one. We were incorrectly storing attestations before, and confusing the DSSE envelope with the in-toto attestation in a few areas. The bug fix was unfortunately backwards incompatible.

**Comment by dlorenc** [comment]
Not much we can do here now, apologies for not remembering this would break at the time.
