### ISSUE TITLE
cosign 1.9.0 make all complains about goimports

### ISSUE THREAD

**Issue by williamh** [sigstore/cosign#2084]
**Description**

The following is the output when "make all" is run on v1.9.0. The build is successful, but it complains about goimports, which doesn't make sense since "make all" just builds the cosign binary.

```
$ cd cosign-git-repo
$ git checkout v1.9.0
$ make all
/bin/sh: line 1: goimports: command not found
CGO_ENABLED=0 go build -trimpath -ldflags "-buildid= -X sigs.k8s.io/release-utils/version.gitVersion=v1.9.0 -X sigs.k8s.io/release-utils/version.gitCommit=a4cb262dc3d45a283a6a7513bb767a38a2d3f448 -X sigs.k8s.io/release-utils/version.gitTreeState="clean" -X sigs.k8s.io/release-utils/version.buildDate=2022-06-03T13:47:07Z" -o cosign ./cmd/cosign
...
```

It seems like "make all" shouldn't be attempting to run "goimports".

**Version**

This happens when attempting to build version 1.9.0.

Thanks,

William

**Comment by williamh** [comment]
This is still an issue with 1.10.0.

Thanks,

William

**Comment by cpanato** [comment]
i will fix that
