### ISSUE TITLE
Output json instead of json lines / ndjson for cosign verify

### ISSUE THREAD

**Issue by xopham** [sigstore/cosign#210]
## Description
When verifying signatures of an image that has been signed multiple times with the same key, cosign outputs the results as *json lines* / *ndjson* which is not real *json*. While *json lines* is great for streaming, "proper" *json* (a json list) might facilitate processing and using the results, specifically when parsing complex output.

## To reproduce
* Sign an image twice with the same key (potentially use different annotations)
* Verify the image with the public key

## Example:
Verify my testimage:
```bash
cosign verify -key cosign.pub xoph/cosigntest:doublesigned
```
Using the corresponding public key:
```bash
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEB7lB3K/WcZiVUhRPDYXJSMivR6Pl
WTeCtrpTUbhba/pIytg6f/WYLNAyQBE5Ht7uqZaZdP+d8GNC8gFRNhaGdw==
-----END PUBLIC KEY-----
```
This will yield *json lines* format output:
```bash
{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d253329323da4c500c7fe343e068c0382b8df4"},"Type":"cosign container signature"},"Optional":null}
{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d253329323da4c500c7fe343e068c0382b8df4"},"Type":"cosign container signature"},"Optional":{"foo":"bar"}}
```

## Expected Behavior
"Proper" json would be:
```bash
[{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d253329323da4c500c7fe343e068c0382b8df4"},"Type":"cosign container signature"},"Optional":null},
{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d253329323da4c500c7fe343e068c0382b8df4"},"Type":"cosign container signature"},"Optional":{"foo":"bar"}}]
```
Now, *json lines* is sometimes considered more shell compatible. One could also make the output format selectable.

**Comment by dlorenc** [comment]
+1!

**Comment by cpanato** [comment]
I can work on this.

which other formats we want?
- json
- plain text?
- yaml?

**Comment by dlorenc** [comment]
The actual payload objects we're outputting are basically plain text, but they happen to be JSON. It's a little awkward. Outputting the overall thing as JSON would basically just be wrapping in a JSON list. I can't think of any other formats that would make sense other than the existing JSON lines or full JSON.
