### ISSUE TITLE
Why is an SBOM attestation predicate wrapped in CosignPredicate?

### ISSUE THREAD

**Issue by otms61** [sigstore/cosign#2126]
**Question**

When Cosign creates an SBOM attestation, the SBOM predicate is wrapped in [CosignPredicate](https://github.com/sigstore/cosign/blob/0f017f82d1f6201799548dc1d60dfbe61426e562/specs/COSIGN_PREDICATE_SPEC.md
). ([spdx](https://github.com/sigstore/cosign/blob/5aa17b98ec2cb16721b314d48d5599df8d4387d9/pkg/cosign/attestation/attestation.go#L244-L246), [cyclonedx](https://github.com/sigstore/cosign/blob/5aa17b98ec2cb16721b314d48d5599df8d4387d9/pkg/cosign/attestation/attestation.go#L257-L259))
Therefore, SBOM locates under `predicate.Data`.

The photo below is an example of spdx.
![sbom_attestation](https://user-images.githubusercontent.com/1850144/182736647-5e81a1cb-b904-4f60-90e7-0632d8d8e76c.png)

This differs from the [in-toto spdx specification](https://github.com/in-toto/attestation/blob/bfd304734d26e5a10e16609ca812d605407d24c5/spec/predicates/spdx.md
). It defines that the SBOM is located under the `predicate`.

```json
{
  // Standard attestation fields:
  "_type": "https://in-toto.io/Statement/v0.1",
  "subject": [{ ... }],

  // Predicate:
  "predicateType": "https://spdx.dev/Document",
  "predicate": {
    "SPDXID" : "SPDXRef-DOCUMENT",
    "spdxVersion" : "SPDX-2.2",
    ...
  }
}
```

This difference makes it difficult to tell whether the SBOM is in `predicate` or `predicate.Data`, when we get an SBOM attestation.

So, why is an SBOM attestation predicate wrapped in CosignPredicate?

**Comment by developer-guy** [comment]
Hi @otms61, thanks for the question. You don't need to use _CosignPredicate_ unless you specify a type for your attestation. AFAIK, cosign will use the _custom_ type and put the given predicate under the _Data_ section if you don't specify any type. Still, of course, there is a chance to define your attestation type by using a URL format like this _--type https://spdx.dev/Document_; if that happens, cosign will put the data under the _predicate_ section like the following screenshot:
![Screen Shot 2022-10-03 at 12 00 37 PM](https://user-images.githubusercontent.com/16693043/193539439-0bbadd2a-0c1d-463b-8518-00b2d8758952.png)

**Comment by cnwaldron** [comment]
> Hi @otms61, thanks for the question. You don't need to use _CosignPredicate_ unless you specify a type for your attestation. AFAIK, cosign will use the _custom_ type and put the given predicate under the _Data_ section if you don't specify any type. Still, of course, there is a chance to define your attestation type by using a URL format like this _--type https://spdx.dev/Document_; if that happens, cosign will put the data under the _predicate_ section like the following screenshot:
> 
> _COSIGN_EXPERIMENTAL=1 cosign attest --predicate sbom.json --type https://spdx.dev/Document devopps/hello-world-ko:distroless_
> 
> _COSIGN_EXPERIMENTAL=1 cosign verify-attestation --type https://spdx.dev/Document devopps/hello-world-ko:distroless > attest.sbom.syft.json_
> 
> _cat attest.sbom.syft.json | jq '.payload | @base64d | fromjson' > attest.sbom.syft.json.decoded_
> 
> ![Screen Shot 2022-10-03 at 12 00 37 PM](https://user-images.githubusercontent.com/16693043/193539439-0bbadd2a-0c1d-463b-8518-00b2d8758952.png)
> 
> > Better to use _--type=spdx_ or _--type=spdxjson_.

I'm a bit confused by this statement. I ran into this issue when using `--type spdxjson` and `--type cyclonedx` however reading your message it sounds like the sbom shouldn't be under `predicate.Data` in this case?

Is this behavior documented anywhere?

**Comment by ChristianCiach** [comment]
I just encounted this issue too while trying to implement a parser that follows the in-toto specification. The fact that the SBOM is wrapped in a `Data` element seems wrong.

But changing this now can lead to issues elsewhere. For example, Trivy explicitly supports the current attestation format: https://aquasecurity.github.io/trivy/v0.31.3/docs/attestation/sbom/

I do think Cosign should follow the In-Toto specification, but maybe this should be coordinated with the Trivy developers to avoid breaking changes.

**Comment by mattmoor** [comment]
+1, I think that we should take a posture similar to what we've been doing with incorrect media types and drop this from basically everything except the cosign `custom` predicate type.  Wrapping existing predicate types seems like a schema violation to me.

**Comment by mattmoor** [comment]
@developer-guy are you actively looking into this or should we unassign?

**Comment by developer-guy** [comment]
Nope I'm not actively looking at it, please go ahead and unassign it 😇
