### ISSUE TITLE
Has anyone had success signing an windows executable? (SignTool)

### ISSUE THREAD

**Issue by jean3x7** [sigstore/cosign#2170]
**Question**

https://docs.microsoft.com/pt-br/windows/win32/seccrypto/signtool
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/authenticode

**Comment by haydentherapper** [comment]
Copying response from a Fulcio issue (https://github.com/sigstore/fulcio/issues/250) on this topic:

There are no current plans to include the Fulcio root in the macOS or Windows trust stores. The way that Sigstore manages and updates its roots of trust through [TheUpdateFramework](https://theupdateframework.io/) is incompatible with the OSs' trust store requirements.

As for the short expiration, Authenticode supports including a [signed timestamp](https://docs.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures). Sigstore is working on spinning up a timestamping authority (TSA), though you could also request a signed timestamp from a TSA like [Digicert's](https://knowledge.digicert.com/generalinformation/INFO4231.html). For any TSA where its root is not trusted by the OS, you will run into the same warnings.

re: https://github.com/sigstore/fulcio/issues/250#issuecomment-1019297096, there may be some X.509 extension or additional value that needs to be set in a Windows code signing certificate. We have a specification for issued certificates in our [docs](https://github.com/sigstore/fulcio/blob/main/docs/certificate-specification.md).
