### ISSUE TITLE
Implement version flag

### ISSUE THREAD

**Issue by lukehinds** [sigstore/cosign#220]
In accordance with https://github.com/sigstore/community/issues/16, implement a version flag

**Comment by cpanato** [comment]
@lukehinds you mean to output the version of the tool?

today `cosign` have a version command that output the version

```
$ cosign version
GitVersion:    v0.2.0-18-gfdce69c
GitCommit:     fdce69c1f650e44d3b3c14978098f2c9ace1e270
GitTreeState:  clean
BuildDate:     '2021-04-06T14:38:17Z'
GoVersion:     go1.16.1
Compiler:      gc
Platform:      darwin/amd64
```

is that this issue is about?
