### ISSUE TITLE
Cosign Clean Response is "DIGEST_INVALID: provided digest did not match uploaded content"

### ISSUE THREAD

**Issue by adammfrank** [sigstore/cosign#2265]
**Description**

I want to be able to clean all signatures off of a signed image, but `cosign clean` fails.

**Steps to Reproduce:**

Start with a signed image that has been saved to a local directory: `signed_image/`

Run local registry:  `docker run -d -p 5001:5000 --restart always -e REGISTRY_STORAGE_DELETE_ENABLED=true --name registry registry:2`

Save local dir to local registry: ` cosign load --dir signed_image localhost:5001/signed_image`

Try to clean: `cosign clean localhost:5001/signed_image --verbose`

**Response**:

```
WARNING: this will remove all signatures, SBOMs and attestations from the image

Are you sure you want to continue? (y/[N]): y
could not delete localhost:5001/signed_image:sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.sig from localhost:5001/signed_image
: DELETE http://localhost:5001/v2/signed_image/manifests/sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.sig: DIGEST_INVALID: provided digest did not match uploaded content
could not delete localhost:5001/signed_image:sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.att from localhost:5001/signed_image
: DELETE http://localhost:5001/v2/signed_image/manifests/sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.att: DIGEST_INVALID: provided digest did not match uploaded content
could not delete localhost:5001/signed_image:sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.sbom from localhost:5001/signed_image
: DELETE http://localhost:5001/v2/signed_image/manifests/sha256-deefb2e7e7163483ea38661838abb5f91a73be739d7ac56e23b634b726c6a4ff.sbom: DIGEST_INVALID: provided digest did not match uploaded content
```

**Version**

```
 custom cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    1.9.0
GitCommit:     a4cb262dc3d45a283a6a7513bb767a38a2d3f448
GitTreeState:  "clean"
BuildDate:     2022-06-03T13:47:07Z
GoVersion:     go1.18.3
Compiler:      gc
Platform:      darwin/arm64
```

**Comment by lancew-q** [comment]
I am also running into this same issue with almost the exact same setup but I am using cosign v1.13.0. Signature is placed on an existing image using `cosign sign`.

**Comment by lancew-q** [comment]
I think the problem here, according the documentation, it will only delete manifests by digest: 

https://docs.docker.com/registry/spec/api/#deleting-an-image

`For deletes, reference must be a digest or the delete will fail`

**Comment by znewman01** [comment]
I think this varies based on registry; that checks out with the above explanation. Thanks for the investigative work @lancew-q !

CC @imjasonh : I feel like what we *really* want Cosign clean to do is:

1. Remove the *tags*, keeping track of the digests that the tags pointed to
2. Delete the digests iff there's no tags pointing at those images

I have no idea if OCI APIs support that. If they don't, we could do:

1. Resolve the relevant tags to digests
2. Delete the images by digest

But that feels race-y.
