### ISSUE TITLE
Signature spec compatibility

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#228]
The signature storage spec in #214 isn't really a signature spec - it's a spec about how the signatures can be stored and discovered within an OCI registry. This format is optimized for the storage layer, which is why it looks unfamiliar to people or tooling who might be expecting a JOSE object or an in-toto metablock. Fortunately, these formats are actually "compatible" - we have all the information needed to construct an in-toto metablock or a series of JWTs.

Let's add support for conversion there at the tooling level:

```
cosign upload --metablock=<>
cosign upload --jwt=<>
```

```
cosign fetch --format=jwt|metablock
cosign verify --format=jwt|metablock
```

**Comment by letmaik** [comment]
@dlorenc Could you sketch out in more detail how you would transform to/from a JWS? I don't see how this is possible given that the signature of a JWS is over `base64(JSON(JOSE header object)).base64(payload)` whereas the signature in cosign is defined over the payload only. I think you'd have to re-sign as JWS and store that in addition.

**Comment by dlorenc** [comment]
@letmaik good catch! We definitely can't do JWT.
