### ISSUE TITLE
Cosign doesn't use the correct CycloneDX predicate

### ISSUE THREAD

**Issue by lehors** [sigstore/cosign#2367]
**Description**

The CycloneDX predicate defined in in-toto-golang has changed and cosign needs to move to the latest version to be compatible with other tools like syft. See https://github.com/in-toto/in-toto-golang/pull/188

**Version**

GitVersion:    1.12.0
GitCommit:     8483d6c71f153f38f237ba79c88d0fda6306e6e3
GitTreeState:  "clean"
BuildDate:     2022-09-14T15:41:15Z
GoVersion:     go1.19.1
Compiler:      gc
Platform:      darwin/amd64

**Comment by developer-guy** [comment]
Yeah, AFAIK, @puerco already knows that problem, and will fix it soon 🙋🏻‍♂️

**Comment by lehors** [comment]
Fixed by PR #2368
