### ISSUE TITLE
cosign login: Registries must be valid RFC 3986 URI authorities: https://gcr.io/my-project-id

### ISSUE THREAD

**Issue by AaronLuo3296** [sigstore/cosign#2372]
It seems that cosign login doesn't support private registry on Google Container Registry.

I got "Error: registries must be valid RFC 3986 URI authorities: https://gcr.io/my-project-id" error while I was running the following scripts to login to my gcr registry.

```gcr-login.sh
#!/usr/bin/env bash

set -euo pipefail

docker-credential-gcr config --token-source="env" > /dev/null 2>&1 && docker-credential-gcr configure-docker > /dev/null 2>&1
TOKEN=$(echo "gcr.io" | docker-credential-gcr get | jq -r .Secret)

echo "Docker login gcr.io/${GCP_PROJECT_ID}"
cosign login -u oauth2accesstoken -p "${TOKEN}" "https://gcr.io/${GCP_PROJECT_ID}"
```

Any ideas how to login to gcr?

**Comment by dlorenc** [comment]
I think login is scoped to just the domain portion, can you try `docker login gcr.io` instead?

**Comment by AaronLuo3296** [comment]
> I think login is scoped to just the domain portion, can you try `docker login gcr.io` instead?

`docker login -u oauth2accesstoken -p "${TOKEN}" "https://gcr.io/${GCP_PROJECT_ID}"` works.

I was trying to use `cosign sign/copy` features without relying on docker. Is that possible?

**Comment by dlorenc** [comment]
Ah sorry can you try `cosign login gcr.io` without the suffix part? It should be possible, docker might just be more flexible here on the string they take. 

cc @jonjohnsonjr

**Comment by AaronLuo3296** [comment]
`cosign login gcr.io` doesn't work. I got another error which might be related to `docker-credential-gcr`.
```
Error: error storing credentials - err: exit status 1, out: `add is unimplemented`
main.go:62: error during command execution: error storing credentials - err: exit status 1, out: `add is unimplemented`
```

BTW, when I change it to `docker login -u oauth2accesstoken -p "${TOKEN}" gcr.io`, I also got the same error "Error: error storing credentials - err: exit status 1, out: \`add is unimplemented\`".

> Ah sorry can you try `cosign login gcr.io` without the suffix part? It should be possible, docker might just be more flexible here on the string they take.
> 
> cc @jonjohnsonjr

**Comment by dlorenc** [comment]
Ah - if you have docker-credential-gcr you shouldn't need to login. You can try:

`gcloud auth configure-docker` then just use cosign as usual!

**Comment by AaronLuo3296** [comment]
> Ah - if you have docker-credential-gcr you shouldn't need to login. You can try:
> 
> `gcloud auth configure-docker` then just use cosign as usual!

Yes, you are right. Once I run `docker-credential-gcr configure-docker` (similar as `gcloud auth configure-docker`, `cosign copy` just works. Thanks for your help.
