### ISSUE TITLE
Env variables are not taken into account when Azure user is signed in

### ISSUE THREAD

**Issue by toddysm** [sigstore/cosign#2384]
**Description**

When trying out signing with a key from Azure Key Vault it doesn't seem that the env variables are taken into account as described in the https://docs.sigstore.dev/cosign/kms_support#azure-key-vault. What happened was that I was signed in with a user account on the console and have also set the environment variables. The user account had permissions on the registry while the service principal that was set in the env variables had permissions on the Key Vault. It seems though that the code used the user account credentials to sign into Key Vault instead the credentials from the environment variables. 

Would be good to clarify and document what is the intended flow here.

**Comment by dlorenc** [comment]
Thanks for filing! Most of us are azure newbies so we'll try to better document this, but if you have any pointers to what flow would make the most sense we'd really appreciate it!

**Comment by toddysm** [comment]
I have not looked at the code to see how you got the signed in user token but if the documentation says that the env variables should be the ones used for Key Vault access, I would expect to sign into the Key Vault with the information stored in the env variables (i.e. the service principal in this case). Having in mind that this flow will mostly be used in automation, using the developer credentials (stored by manually signing in) should be lower priority IMO. Service principal and Azure Managed Identities should be the ones with higher priority with fall back to user identity.

**Comment by jeremyrickard** [comment]
I can try and help improve this.

**Comment by cpanato** [comment]
thanks @jeremyrickard let me know where i can help you

**Comment by toddysm** [comment]
@jeremyrickard If you are going to improve this, I would suggest the following behavior:

- If env variables are present, consider the env variables as priority (i.e. ignore the signed in user)
- If env variables are not present, fallback to signed in user (if present)

I am not sure whether Managed Identity should be considered in this scenario. Is running build agents with MI a common practice?

**Comment by haydentherapper** [comment]
Closing as outdated, but feel free to reopen and make the suggested changes.
