### ISSUE TITLE
Tagged release of "cosign" container images on "gcr" showing the wrong creation date

### ISSUE THREAD

**Issue by Rajpratik71** [sigstore/cosign#2396]
**Description**

Tagged release of "cosign" container images on "[gcr](https://console.cloud.google.com/gcr/images/projectsigstore/global/cosign)" showing the wrong creation date

![image](https://user-images.githubusercontent.com/12658912/199248616-2c0d7ad3-3296-4497-9c0a-63960f940afa.png)

![image](https://user-images.githubusercontent.com/12658912/199248883-9d5f722f-91ce-4ebf-8e7f-a8225b62cd8b.png)

**Comment by znewman01** [comment]
Yes, that's deliberate and necessary for reproducible OCI image builds. [Ko](https://github.com/ko-build/ko) (which we use) and many other image creation tools do this by default.

Is it causing problems?

**Comment by znewman01** [comment]
I'm going to close this for now. Feel free to comment/reopen if this is causing issues.
