### ISSUE TITLE
How should one attach multiple SBOMs of the same type (CycloneDX in my case)to an image?

### ISSUE THREAD

**Issue by L1ghtman2k** [sigstore/cosign#2413]
**Question**
How should one attach multiple SBOMs of the same type (CycloneDX in my case)to an image?

Context:

I have a multi-stage docker build image. The final stage only contains the compiled binary, on a bare-bones alpine container. I want to attach two SBOM files to the image:
 - The SBOM file of the final image
 - The SBOM file of the file system from which the compiled binary was generated (in my case, I am using rust, so I expect syft to generate SBOM of the Cargo.lock file)

This seemed to me like the only way to capture the whole picture since syft can't gather the contents of Cargo.lock's packages in the final image alone.

Currently, I am trying to do the following:

```
echo "Generating SBOM attestation for the image"
syft attest my-image -o cyclonedx > ./sbom_image.att.json

echo "Generating SBOM attestation for the project directory"
syft ./ -o cyclonedx > ./sbom_source.json

echo "Attaching generated SBOM attestation"
cosign attest --force  --predicate "./sbom_source.json" --type https://cyclonedx.org/bom my-image

echo "Attach Image Attestation Generated By Syft"
cosign attach attestation my-image --attestation "./sbom_image.att.json"
```

However, this doesn't seem correct to me. Running following:
`COSIGN_EXPERIMENTAL=1 cosign verify-attestation --type https://cyclonedx.org/bom my-image | jq -r '.payload' | base64 -d | jq -r`
ends up producing two back-to-back JSON documents(SBOMs) separated by a new line.

What is the practice around having multiple SBOMs associated with a single image?

**Comment by vaikas** [comment]
One option would be to use this flag:
```
      --attachment-tag-prefix [AttachmentTagPrefix]sha256-[TargetImageDigest].[AttachmentName]   optional custom prefix to use for attached image tags. Attachment images are tagged as: [AttachmentTagPrefix]sha256-[TargetImageDigest].[AttachmentName]
```

**Comment by L1ghtman2k** [comment]
Thank you, that solves it for me!
