### ISSUE TITLE
Unable to post a key pair into GitLab

### ISSUE THREAD

**Issue by Footur** [sigstore/cosign#2416]
We are using a self-hosted GitLab instance. By generating a key pair we get the following error message:
```
Error: could not create "COSIGN_PASSWORD" variable: Post "gitlab.govkg.de/api/v4/projects/5/variables": unsupported protocol scheme ""
main.go:46: error during command execution: could not create "COSIGN_PASSWORD" variable: Post "gitlab.example.net/api/v4/projects/5/variables": unsupported protocol scheme ""
```
Our config is based on [this](https://docs.sigstore.dev/cosign/git_support) documentation. Is there a way to get a more verbose output (we are already using the `-d` flag)?

For reproduction:
```bash
#!/bin/sh

set -eu

export GITLAB_HOST=gitlab.example.net
export GITLAB_TOKEN=<token>
export COSIGN_PASSWORD='hunter2'

cosign generate-key-pair -d gitlab://5
```

**Comment by developer-guy** [comment]
IIRC, the client pkg we used for interacting GitLab instances requires setting protocol schemes such as http or https. Can you please retry by setting the correct scheme for your GitLab instance ?

**Comment by Footur** [comment]
@developer-guy Thank you! It's working! 💖

The configuration variables should be documented in the official documentation.

**Comment by developer-guy** [comment]
great, happy to help 🥳

**Comment by znewman01** [comment]
@Footur: Where did you see the `GITLAB_HOST` variable documented?

FYI our env vars should be documented with `cosign env`:

```bash
$ cosign env
[...]
# GITLAB_HOST is URL of the GitLab instance
# Expects: string with the URL of GitLab instance
GITLAB_HOST=
# GITLAB_TOKEN is a token used to authenticate with GitLab
# Expects: string with a token
GITLAB_TOKEN=
[...]
```

Could be better (examples!) but it does tell you about the URL.

I agree that the GitLab docs should also mention this 😄

**Comment by Footur** [comment]
@znewman01 I've used the latest container image, but the env command was not available. I recommend that these variables are also included in [this](https://docs.sigstore.dev/cosign/) documentation.

**Comment by znewman01** [comment]
See https://github.com/sigstore/docs/issues/27 to track docs
