### ISSUE TITLE
Feature request: sign and verify the (custom metadata file)blobs and use them as attestation files 

### ISSUE THREAD

**Issue by SaiJyothiGudibandi** [sigstore/cosign#2421]
**Feature Request**

**Description**
Trying to achieve supply chain using GitHub/Jenkins pipeline using cosign and rekor.
1. In Each and every stage of the pipeline, sign the (auto/)generated (custom)metadata file. 
2. Attest the signed metadata data files as a bundle of predicate files after publishing artifacts. 
3. At the time of verify-attestation, cosign should be mature enough to verify all the attached/attested metadata file signatures in addition to the policy verification.

**Comment by znewman01** [comment]
Can you describe what support you'd need from Cosign for this? I believe this is all possible using Cosign as-is.

It  sounds like you'd be interested in the integration with [in-toto](https://in-toto.io/). There aren't good docs for that at the moment; we should write some.

**Comment by znewman01** [comment]
Ping—can you clarify the request for us?
