### ISSUE TITLE
Cosigned Helm Chart - tls: no certificates configured

### ISSUE THREAD

**Issue by quadrinho** [sigstore/cosign#2428]
**Description**

App Version 1.8.0
Chart Version 0.1.23

I have tried to deploy the last version of the cosigned chart but in the webhook and policy-webhook i received this errors:

**{"level":"warn","ts":"2022-11-09T11:00:37.588Z","logger":"clusterimagepolicy","caller":"webhook/webhook.go:154","msg":"server key missing"}
2022/11/09 11:00:37 http: TLS handshake error from 10.199.120.107:43092: tls: no certificates configured**

I installed the chart using this command:

`helm upgrade -i cosigned . --devel -n default --set cosign.secretKeyRef.name=mysecret`

In the "mysecret" kubernetes secret is present the public key cosign.pub that i retrieve from AWS KMS after creating on it the key:

CREATION OF THE KEY ON KMS:

`aws kms create-key --key-usage SIGN_VERIFY --customer-master-key-spec RSA_4096 --description "KMS key for signing images" `

RETRIEVE THE PUBLIC KEY:

`aws kms get-public-key --key-id $KMS_ALIAS_ARN --query 'PublicKey' --output text | openssl enc -base64 -A -d -in /dev/stdin | openssl rsa -pubin -inform DER -outform PEM -in /dev/stdin -out cosign.pub`

So i don't underst the above bold error.

**Comment by hectorj2f** [comment]
@quadrinho Please, could you open this issue in https://github.com/sigstore/policy-controller ? I'd be glad to help you there.
