### ISSUE TITLE
Support `verify` with public keys from URL

### ISSUE THREAD

**Issue by dekkagaijin** [sigstore/cosign#247]
This would make certain use-cases easier, e.g. if the public key used to verify the signature of a release is stored in the same GitHub repo as the source:

`verify --key-url https://raw.githubusercontent.com/image-publishing-org/project-repo/$RELEASE_TAG/cosign.pub gcr.io/image/to/verify:$RELEASE_TAG`

**Comment by dlorenc** [comment]
+1!
