### ISSUE TITLE
Hash algorithm defaults to SHA256 when verifying with a certificate

### ISSUE THREAD

**Issue by dimitar-dimitrow** [sigstore/cosign#2487]
**Question**
When verifying a signature using a certificate and certificate chain the hash algorithm is hard coded as SHA256 [here](https://github.com/sigstore/cosign/blob/72dac4d760825f1fe7161e48c93d23bd7ec842a1/pkg/cosign/verify.go#L191). According to verify command help a  _signature-digest-algorithm_ flag could be specified. Do this flag only makes sense when verifying with public key or it is a lapse?

**Comment by hectorj2f** [comment]
> Do this flag only makes sense when verifying with public key or it is a lapse?

@dimitar-dimitrow Yes, it is used to verify keys with a different digest algorithm e.g. sha512... That was the purpose of this flag when we added it.

**Comment by dimitar-dimitrow** [comment]
@hectorj2f I could sign an image with different digest algorithm, e.g. sha512, and try to verify it using certificate, but it would fail as the digest algorithm is presumed to be sha256. Here are some commands to follow:
```
openssl genrsa -des3 -out rootCA.key 4096
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1825 -out rootCA.crt
openssl genrsa -out mydomain.com.key 4096
openssl req -new -key mydomain.com.key -out mydomain.com.csr
openssl x509 -req -in mydomain.com.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out mydomain.com.crt -days 365 -sha256
cosign generate localhost:5000/test:signed > payload.json
openssl dgst -sha512 -sign mydomain.com.key -out payload.sig payload.json
cat payload.sig | base64 > payloadbase64.sig
cosign attach signature --payload payload.json --signature payloadbase64.sig localhost:5000/test:signed
cosign verify --certificate mydomain.com.crt --certificate-chain rootCA.crt localhost:5000/test:signed
cosign verify --certificate mydomain.com.crt --certificate-chain rootCA.crt --signature-digest-algorithm sha512 localhost:5000/test:signed
```
The verification fails in both cases with:
```
Error: no matching signatures:
crypto/rsa: verification error
main.go:62: error during command execution: no matching signatures:
crypto/rsa: verification error
```

**Comment by hectorj2f** [comment]
Yes, it makes sense that means it should be considered as a feature request to support certificates and certificate-chains.
