### ISSUE TITLE
Spec: rename "type" in the simple signing payload

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#252]
Do we need to use "atomic container signature" as is specified in the simple signing spec?

https://www.redhat.com/en/blog/container-image-signing

Ref #214

**Comment by dekkagaijin** [comment]
Depends on how close we want to adhere to the spec, e.g. do we want to require a repo path in the sig payload

**Comment by dlorenc** [comment]
I think we decided to add the field, but not validate it.

**Comment by dekkagaijin** [comment]
Right, which would mean that we're not adherent to the spec of the overall scheme. If we don't want to require validation of a "critical" portion of the signature payload, why require it? If we don't want to require it, then we can't adhere to the `atomic` payload spec

**Comment by dlorenc** [comment]
So the high level desire is that payloads we generate can be validated by things that expect simple signing. I think it's a fair claim to pretend we're compliant at least during the signature generation process, even though we're not for verification.

It is ambiguous though.

**Comment by dekkagaijin** [comment]
> I think it's a fair claim to pretend we're compliant at least during the signature generation process

The current atomic/Simple Signing spec only supports OpenPGP: https://github.com/containers/image/blob/master/docs/containers-signature.5.md#the-cryptographic-signature

**Comment by dlorenc** [comment]
Oof. At least it's worded in a way that allows for more:

> Currently the only defined cryptographic signature format is an OpenPGP signature (RFC 4880), but others may be added in the future. (The blob does not contain metadata identifying the cryptographic signature format. It is expected that most formats are sufficiently self-describing that this is not necessary and the configured expected public key provides another indication of the expected cryptographic signature format. Such metadata may be added in the future for newly added cryptographic signature formats, if necessary.)

OK though, we'll leave this as is until we get a real plan for interop.

**Comment by dlorenc** [comment]
Fixed, we can close.
