### ISSUE TITLE
e2e_test_secrets.sh CI failing at HEAD

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#2531]
**Description**

Related to the many changes recently submitted, we likely just need to add a `tlog-upload=false` on signing and `insecure-skip-tlog-verify=true` on verification. Another question is why this only runs at HEAD and not on PR submission.

**Comment by cpanato** [comment]
it runs only on HEAD because that needs aoidc token to connect into the gcp project, however let me refactor that.
