### ISSUE TITLE
Fips

### ISSUE THREAD

**Issue by dolevhadad** [sigstore/cosign#2533]
**Question**

Hi 
Is Cosign Fips Compliant?

**Comment by znewman01** [comment]
Reopening https://github.com/sigstore/cosign/issues/94 and closing this issue as a duplicate

Basically, it's somewhat of a complicated question. The answer is "no, but we know how we would go about getting there."

Can you chime in on  https://github.com/sigstore/cosign/issues/94 if this is a blocker for you?
