### ISSUE TITLE
2.0: Documentation updates for COSIGN_EXPERIMENTAL and new flags

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#2534]
**Description**

We need to remove references to `COSIGN_EXPERIMENTAL` in code (tests and CLI docs), documentation, and blog posts. We also need to update documentation with any new required flags (like identity flags) and optional flags (like tlog-upload).

**Comment by znewman01** [comment]
Timing is a little awkward here. There's a few changes we should have staged up and ready to go simultaneous with the release (anything breaking). Before the 2.0 release we can't push most of these.

Leaving `COSIGN_EXPERIMENTAL` in for a while doesn't actually hurt anything, and I worry switching too soon will cause confusion before folks have updated.

**Comment by haydentherapper** [comment]
All examples in the code should reflect the current state imo, so we should at least remove the references to experimental in the code base.  

We also need to go add the newly required identity flags, since all existing example commands won’t work.
