### ISSUE TITLE
Need to expose CTLog public key in cosign.CheckOpts

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#2537]
**Description**

Support was added to specify things like RekorPub keys as part of the CheckOpts structure so that we can decouple the TUF / Verify boundaries.

What's missing from CheckOpts however is the ability to specify the CTLog public key:
https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L119

This should be added.

@asraa or am I missing something?

**Comment by asraa** [comment]
Nope, I think you're correct. There's still this, and piping through each of these in the signing path. I can probably see if I can get to both at the end of the week, but likely not in the next 3 days!

**Comment by vaikas** [comment]
Ack, thanks!

**Comment by haydentherapper** [comment]
@asraa do you want me to track this a 2.0 blocker? We wouldn't be cutting 2.0 for a while (just a RC soon)
