### ISSUE TITLE
Is there a reason why rekor pubkeys has to be ecdsa

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#2540]
**Description**

Just curious if there's a reason why this has to be explicitly ecdsa and not just crypto.publickey?
https://github.com/sigstore/cosign/blob/main/pkg/cosign/tlog.go#L56

I just know when I was working on some of the scaffolding things there was some future proofing work so just curious.
@asraa @haydentherapper

**Comment by haydentherapper** [comment]
Iirc it’s hardcoded into rekor, unless we’ve switched to the signer/verifier interface

**Comment by vaikas** [comment]
Ack, thanks!
