### ISSUE TITLE
Improve the document for new users to understand quickly that Cosign supports blobs signing

### ISSUE THREAD

**Issue by suzuki-shunsuke** [sigstore/cosign#2554]
Thank you for your great project.
I have a feedback about the document about Cosign.

Cosign supports not only containers but also standard files and blobs (or binary large objects).

https://docs.sigstore.dev/cosign/working_with_blobs

But I misunderstood Cosign supports only containers, because the repository description and the top of README and official document describe only containers.

repository description

> Container Signing

README

> Container Signing, Verification and Storage in an OCI registry.

Official document: https://docs.sigstore.dev/cosign/overview

> Cosign supports container signing, verification, and storage in an OCI registry.

I know there is a [document about blobs signing](https://docs.sigstore.dev/cosign/working_with_blobs), but users may miss the document.

So I think we should improve the document so that new users can understand quickly that Cosign supports blobs signing.

What do you think?

**Comment by suzuki-shunsuke** [comment]
Oh, the issue label is inappropriate.
Could you remove the `enhancement` label and add the `documentation` label?

**Comment by dlorenc** [comment]
All set!
