### ISSUE TITLE
Support custom error messages when evaluating Rego policies

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#2570]
**Description**

At the moment, cosign Rego policies are expecting a specific template and the result is evaluated as a boolean to determine if the policy is satisfied or not. The current template is detailed below:

```
package sigstore

default isCompliant = false
isCompliant {

# Rego logic goes here; must evaluate to true for policy to pass

}
```

`Cosign` should support custom error messages when any Rego policy evals to `false`. To do so, I propose to support the following Rego module template:

```
package sigstore

isComplaint[response] {
   result := ( ... Rego logic evaluated here to a boolean ....) 
   
   errorMsg := "Your custom error message..."
   response :={
	"result" : result,
	"errors" : errorMsg,
  }
}
```
With this new template, the value store in `result` will determine if the logic evaluated is complaint. If `result` evals to `false` then the cosign source code will return the content of `errorMsg`. 

Note that the result evaluation within cosign will be able to handle both templates the old (legacy) and the new proposed here. 

Other alternatives have been discarded due to the complexity to ensure a proper handling of the Rego.ResultSet without increasing the complexity of the current user experience.

**Comment by mattmoor** [comment]
@hectorj2f I could see it being useful for `policy-controller` to allow policies to return warnings as well.

Basically what I've been thinking is that when we're in `mode: enforce` allowing the policy to return `errors` or `warnings`, so that they don't have to split things into two separate policies.

**Comment by hectorj2f** [comment]
@mattmoor Yes, the policy-controller reuses this source code so any change here could work for both. I didn't think about a warnings field for the response, but that is a good idea.
