### ISSUE TITLE
Cosign requires Go 1.19

### ISSUE THREAD

**Issue by stefan-zh** [sigstore/cosign#2582]
I am trying to do 2 things, both of which end up unsuccessful (I have Golang `1.17.13` installed):
- clone the cosign repo and run some of the tests locally
- install the cosign binary according to documentation:
![image](https://user-images.githubusercontent.com/878624/209935672-05493da8-9f2b-465f-bee3-dd7af064a6f0.png)

In both cases I get errors that the project requires at least `Golang 1.18` or `1.19`:
![image](https://user-images.githubusercontent.com/878624/209935811-467a8e00-edad-40dc-93ca-1168dc97efba.png)
![image](https://user-images.githubusercontent.com/878624/209936405-beaeccb7-1b83-419f-8fc1-c2ec7253ebf1.png)

**Suggestions**:  
Could you update the documentation to reflect that the project requires Golang `1.18` or `1.19`?
Or, if the project could be run under Golang `1.17` could you update the instructions to specify how?

**Comment by cpanato** [comment]
thanks for the issue @stefan-zh 

Yep cosign requires go 1.19 as marked here https://github.com/sigstore/cosign/blob/main/go.mod#L3

go1.17 is archived and not supported anymore, go1.18 will soon be deprecated as well.


are you willing to update the doc to add this mention?

**Comment by stefan-zh** [comment]
Thanks @cpanato 
Given your clarification about Golang 1.19 being required, I will open a PR to update the docs.
