### ISSUE TITLE
Enchancement: Keyless Cosign Verify error statement

### ISSUE THREAD

**Issue by garymalaysia** [sigstore/cosign#2588]
**Description**
When `cosign initialize` is executed within CICD pipeline for automatic artifact signing, local users who wish to validate the signed artifact using `COSIGN_EXPERIMENTAL=1 cosign verify --rekor-url "https://<internal-rekor-server>.com"` on their local machine need to perform `cosign initalize <same root.json as CICD> `.

Should users fail to execute local initialization, a vague error message was issue to users.
```
Error: no matching signatures:
x509: certificate signed by unknown authority
main.go:62: error during command execution: no matching signatures:
x509: certificate signed by unknown authority
```

**Comment by asraa** [comment]
This makes sense! You are actually seeing the error that the Fulcio certs were not found. When the Rekor public key is not found you would get an error like `rekor log public key not found for payload`. 

What we can do is print an error here and for the Fulcio cases that you should check your TUF root and/or run `cosign initialize`. Just to confirm, your TUF root also contains the Fulcio cert?

**Comment by garymalaysia** [comment]
Hi @asraa! Thank you for looking into this :)
To answer your qs, No. our TUF root does not contain Fulcio cert

**Comment by asraa** [comment]
Hmmm interesting. Were you using a custom Fulcio? The error messages suggest that the certificate was not issued by the production Fulcio.

**Comment by garymalaysia** [comment]
Correct! we are using custom Fulcio. Along with that, we are also using custom Rekor and TUF endpoints
All 3 are setup internally.

**Comment by asraa** [comment]
Got it! In that case, your custom TUF root must contain all the custom items (custom Fulcio root/intermediate CA, custom CT, custom Rekor).

See this script! s

**Comment by garymalaysia** [comment]
Just to clarify, if my custom TUF root contains all the custom items (custom Fulcio root/intermediate CA, custom CT, custom Rekor, i do not need to execute `cosign initialize <same root.json as CICD> ` locally on my machine to verify signed artifact ?

**Comment by asraa** [comment]
>  i do not need to execute cosign initialize <same root.json as CICD>  locally on my machine to verify signed artifact ?

yes, you do! 

my question was that it seemed like the TUF root did not contain the custom Fulcio root/intermediate. Just wanted to make sure that if you did run cosign initialize, the TUF root had all the necessary targets including the Fulcio one.

**Comment by garymalaysia** [comment]
Ah! gotcha! thank you for clarifying. 
I am still a noob in Sigstore inner working so please bare with me :D

**Comment by znewman01** [comment]
> Ah! gotcha! thank you for clarifying. I am still a noob in Sigstore inner working so please bare with me :D

You shouldn't have to be an expert to use the tool :) thanks for filing this feedback
