### ISSUE TITLE
Using --insecure-skip-tlog-verify possibly broken?

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#2590]
**Description**

It's unclear to me what the behaviour of the --insecure-skip-tlog-verify means or if there's a bug. I would assume that by using that flag, less verifications would be done, and therefore verification using that flag should not result in something failing that passes without that flag.

```
      --insecure-skip-tlog-verify                                                                skip transparency log verification, to be used when an artifact signature has not been uploaded to the transparency log. Artifacts cannot be publicly verified when not included in a log
```

An example (from the head), first with not specifying --insecure-skip-tlog-verify and the second with it:
```
./cosign verify cgr.dev/chainguard/static@sha256:39ae0654d64cb72003216f6148e581e6d7cf239ac32325867af46666e31739d2 --certificate-identity='https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main' --certificate-oidc-issuer='https://token.actions.githubusercontent.com'

Verification for cgr.dev/chainguard/static@sha256:39ae0654d64cb72003216f6148e581e6d7cf239ac32325867af46666e31739d2 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"ghcr.io/chainguard-images/static"},"image":{"docker-manifest-digest":"sha256:39ae0654d64cb72003216f6148e581e6d7cf239ac32325867af46666e31739d2"},"type":"cosign container image signature"},"optional":{"1.3.6.1.4.1.57264.1.1":"https://token.actions.githubusercontent.com","1.3.6.1.4.1.57264.1.2":"schedule","1.3.6.1.4.1.57264.1.3":"e0e47eb5f17844c26a041480b6cd6c8ff612778f","1.3.6.1.4.1.57264.1.4":".github/workflows/release.yaml","1.3.6.1.4.1.57264.1.5":"chainguard-images/images","1.3.6.1.4.1.57264.1.6":"refs/heads/main","Bundle":{"SignedEntryTimestamp":"MEYCIQD0mNj/m4tLjb/o2/7+SUAimv8gIkj2hE5ZE/5wCI8iogIhAND5nqBgET4sj+5lqiTni7dDOxITBeBVgPpb/8keMGgi","Payload":{"body":"eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiJmODQ1N2UzMTQyZTVlMGIxYWRjMjhhNWU0ZDI4OGViOWIyYTMzNTBiODgzZWZkYTdhNjZjOTE5MTI0NDIzOGQzIn19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FUUNJQjhGMWtsNzV2Uk9mc2pnbWRqZWMzbXo2T08vU2pIcHlQQlZmVzB2UkVPT0FpQnl2YnVTL01zWVAyczBzUU1mVms4dFRPOFZ3Tkt0RkkzdkdFbEh0T0I4MEE9PSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUjJSRU5EUVRCSFowRjNTVUpCWjBsVlIyTklZMDB4Y1ZoSlNqQXlUMGhXTW5sbVZXMHdTVGg1WldkdmQwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcE5kMDFVUVhsTlJFRjRUVVJCZUZkb1kwNU5hazEzVFZSQmVVMUVRWGxOUkVGNFYycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVZVY2tZdmIwUkpNRXBOSzJoT2IzSkRlRUZFV2tZNU1GQkpVSE50YUZreVMwaFpRemNLUTFGVVJUTlJhak15VWpaalJtZE9iVUpTY2pscldYVlFia0Z1WjFobVQxRXpaMlpZUVM4MVlqZG9RbWR6T0VveFpFdFBRMEZ0UVhkblowcGpUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlZSWlhReUNqZ3ZPVmRNYURoMFZUUXhhMjQwZG1ZeVRWVnphMDlGZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDJGQldVUldVakJTUVZGSUwwSkdOSGRZU1ZwaFlVaFNNR05JVFRaTWVUbHVZVmhTYjJSWFNYVlpNamwwVERKT2IxbFhiSFZhTTFab1kyMVJkQXBoVnpGb1dqSldla3d5YkhSWlYyUnNZM2s0ZFZveWJEQmhTRlpwVEROa2RtTnRkRzFpUnprelkzazVlVnBYZUd4WldFNXNURzVzYUdKWGVFRmpiVlp0Q21ONU9XOWFWMFpyWTNrNWRGbFhiSFZOUkd0SFEybHpSMEZSVVVKbk56aDNRVkZGUlVzeWFEQmtTRUo2VDJrNGRtUkhPWEphVnpSMVdWZE9NR0ZYT1hVS1kzazFibUZZVW05a1Ywb3hZekpXZVZreU9YVmtSMVoxWkVNMWFtSXlNSGRHWjFsTFMzZFpRa0pCUjBSMmVrRkNRV2RSU1dNeVRtOWFWMUl4WWtkVmR3cE9aMWxMUzNkWlFrSkJSMFIyZWtGQ1FYZFJiMXBVUW14T1JHUnNXV3BXYlUxVVl6Uk9SRkpxVFdwYWFFMUVVWGhPUkdkM1dXcGFhbHBFV21wUFIxcHRDazVxUlhsT2VtTTBXbXBCYzBKbmIzSkNaMFZGUVZsUEwwMUJSVVZDUWpSMVdqSnNNR0ZJVm1sTU0yUjJZMjEwYldKSE9UTmplVGw1V2xkNGJGbFlUbXdLVEc1c2FHSlhkM2RLWjFsTFMzZFpRa0pCUjBSMmVrRkNRbEZSV1ZreWFHaGhWelZ1WkZkR2VWcERNWEJpVjBadVdsaE5kbUZYTVdoYU1sWjZUVUl3UndwRGFYTkhRVkZSUW1jM09IZEJVVmxGUkROS2JGcHVUWFpoUjFab1draE5kbUpYUm5CaWFrTkNhV2RaUzB0M1dVSkNRVWhYWlZGSlJVRm5VamhDU0c5QkNtVkJRakpCVGpBNVRVZHlSM2g0UlhsWmVHdGxTRXBzYms1M1MybFRiRFkwTTJwNWRDODBaVXRqYjBGMlMyVTJUMEZCUVVKb1Z5OVJWVkU0UVVGQlVVUUtRVVZqZDFKUlNXZFhOREl6UW14U1dYWmlRVk5ZVGpZelVqTTJhRzUxVlZsa05XMVRTVUpGZGxwblEwTjBMM1JyWlZSUlEwbFJSRVZPV1VGRmVFSkNUd281TlhGaFFreEVVbVZEWjBGSVdIaENXa3g1VG5KbGFGWnRSM2RWVVcxTEwyNXFRVXRDWjJkeGFHdHFUMUJSVVVSQmQwNXdRVVJDYlVGcVJVRnpaV3Q0Q25KWGRFTnhlQ3RyV21rMGRXWkxTekE1YVRkVU9HSm1kVTVWVFVSbVVWSlZNMkp4VDNrekszbFhPRVZLTkZKSWNHUnZja3RZVEVwVVlYQndjRUZxUlVFS2REQmFhVk5PVWpOa01VOU9TR3A1ZEhObWRsUmlkbFJaZGpoMFNYaHNjSFZQVUdkblJIbE9kV2d4Vnk5NE5rMXlUMnBVY0hOeWRXaGlaMkZJVEM5NmVRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0ifX19fQ==","integratedTime":1672618221,"logIndex":10286378,"logID":"c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d"}},"Issuer":"https://token.actions.githubusercontent.com","Subject":"https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main","githubWorkflowName":".github/workflows/release.yaml","githubWorkflowRef":"refs/heads/main","githubWorkflowRepository":"chainguard-images/images","githubWorkflowSha":"e0e47eb5f17844c26a041480b6cd6c8ff612778f","githubWorkflowTrigger":"schedule","run_attempt":"1","run_id":"3819302484","sha":"e0e47eb5f17844c26a041480b6cd6c8ff612778f"}}]
vaikas@villes-mbp cosign % ./cosign verify cgr.dev/chainguard/static@sha256:39ae0654d64cb72003216f6148e581e6d7cf239ac32325867af46666e31739d2 --certificate-identity='https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main' --certificate-oidc-issuer='https://token.actions.githubusercontent.com' --insecure-skip-tlo
g-verify
**Warning** Skipping tlog verification is an insecure practice that lacks of transparency and auditability verification for the signature.
Error: no matching signatures:
checking expiry on certificate with bundle: certificate expired before signatures were entered in log: 2023-01-02T00:20:01Z is before 2023-01-04T11:00:44+02:00
main.go:62: error during command execution: no matching signatures:
checking expiry on certificate with bundle: certificate expired before signatures were entered in log: 2023-01-02T00:20:01Z is before 2023-01-04T11:00:44+02:00
```

It is skipping the verification here as expected:
https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L599

But now when it then goes here, the acceptableRekorBundleTime is nil as expected by specifying that flag, but then that means this gets evaluated against current time here:
https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L708

And not surprisingly it fails because the cert has expired by design. So, just curious if this is really the intended behaviour, or if there's a bug in here.

**Comment by vaikas** [comment]
@asraa @haydentherapper FYI since I know you've been doing some work here somewhat recently :)

**Comment by asraa** [comment]
> And not surprisingly it fails because the cert has expired by design.

That should be the case, since verification can't complete without the additional timestamp information.

>  I would assume that by using that flag, less verifications would be done, and therefore verification using that flag should not result in something failing that passes without that flag.

That being said, I understand your point here. This flag is meant to skip checking the tlog for presence (either offline or online) but as a consequence we lose information on the timestamp of the signature.

I think there is a small bug here though. You were passing container, which likely contains an tlog entry bundle. We probably should still verify that for the timestamp. `--insecure-skip-tlog-verify` should indicate not REQUIRING tlog presence, but still preserve the timestamp check which SHOULD satisfy the principle you mentioned.

**Comment by asraa** [comment]
There's a small complication here but I can put out a PR for discussion. If we always try to verify a rekor bundle (offline), then we always need the Rekor pubkeys from TUF in the CLI (we can't gate fetching that TUF info with `SkipTlogVerify` anymore)

**Comment by asraa** [comment]
I think I'm back and forth on this, unless we rename `--insecure-skip-tlog-verify` to `--insecure-no-require-tlog`.

**Comment by asraa** [comment]
> My thinking was that without hoisting this check outside the insecure-skip-tlog-verify flag
https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L600
I don't see how it could work.

Right, that was probably my proposed change. Then fail if there is an error or the bundle was not verified and we require tlog verification.

> should be looking at the code/comments and the two flags (--insecure-skip-tlog-verify --offline) :)

Offline was meant to prevent checking Rekor online. So you can still verify TLOG presence offline with the bundle with the --offline flag. Or you can skip TLOG presence entirely with the skip-tlog-verify flag.

> When you say timestamp check, what do you mean by this? Are you saying we should grab it from the bundle and hence verify the bundle?

Right. 

What I'm not sure about is whether `--insecure-skip-tlog-verify` should mean (1) the original as stated flag where it toggles checking the TLOG at all. This would mean loss of timestamp information and the possibility of failing. (2) toggles failing on lack/failure of TLOG presence, but still checks the presence of TLOG bundles on disk. this way, it still grabs the TLOG entry for the timestamp check.

With (2) I think it there may be some unexpected cases: if we skip tlog verification why are we relying on the tlog for the timestamp? On the other hand, with (1) we have the weird lack of invariant (skipping a check should only make verification more permissive) 

This is why I'm a little back and forth :|

**Comment by znewman01** [comment]
@vaikas : would a refactor of the flags a la this comment address this? https://github.com/sigstore/cosign/issues/2466#issuecomment-1320213278

(Don't let that stop a local improvement here to make things clearer)

**Comment by haydentherapper** [comment]
The original thought with `--insecure-skip-tlog-verify` was it should signify that Rekor was not used in signing. You have no bundle and you don't want to do an online check. 

Should it be an error if you pass `--insecure-skip-tlog-verify` and there is a bundle present?

**Comment by asraa** [comment]
> Should it be an error if you pass --insecure-skip-tlog-verify and there is a bundle present?

No, because the client can't control whether a bundle is present on their OCI image, but skipping TLOG verification may be part of their policy, IMO

**Comment by priyawadhwa** [comment]
If the original goal with `--insecure-skip-tlog-verify` was to signify Rekor was not used in signing, the only alternative would be that a TSA was used. If a user sets `--insecure-skip-tlog-verify`, maybe cosign should expect that an RFC Timestamp bundle is available and fail if it isn't.

**Comment by haydentherapper** [comment]
The other case is someone uses a certificate that is not yet expired so doesn't need a signed timestamp or Rekor. While this isn't likely for Sigstore issued certs, it may be for byo PKI

**Comment by priyawadhwa** [comment]
That makes sense, looks like cosign has that case covered and can verify unexpired certs against the current time.

I guess if the purpose of this flag is "ignore rekor" then even though this is kinda unexpected/confusing behavior it's also correct. +1 to Asra's suggestion to rename the flag to `--insecure-ignore-tlog` or something so that the flag name isn't as misleading, since `--insecure-skip-tlog-verify` does seem like a verification step should be skipped.

**Comment by hectorj2f** [comment]
@haydentherapper @asraa @priyawadhwa @vaikas I opened a PR with the proposed changes based on the comments here https://github.com/sigstore/cosign/pull/2620. 

Please, let me know if you feel we are missing something. I tried to handle the lack of a missing signed timestamp whenever the cert expired and the user ignores the tlog verification and a rfc3161 timestamp isn't found.  

> The other case is someone uses a certificate that is not yet expired so doesn't need a signed timestamp or Rekor.

@haydentherapper I am not sure how we can better handle in https://github.com/sigstore/cosign/pull/2620. this scenario. Open to suggestions there.

**Comment by haydentherapper** [comment]
@hectorj2f It should still be handled based on your PR, since you only print the error if the certificate can't be verified with the current time
