### ISSUE TITLE
Predicate URIs aren't RFC 3986 compliant

### ISSUE THREAD

**Issue by wlynch** [sigstore/cosign#2612]
**Description**

[In-toto spec says](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#TypeURI) that predicate URIs should be [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-3) compliant, which means that we should include a scheme (i.e. `https://` in the URIs we're producing.

https://github.com/sigstore/cosign/blob/04fb9c0a5bdebf7580d772dfd3e439ae66ac2b8a/pkg/cosign/attestation/attestation.go#L31-L37

The change to add the scheme seems simple enough, but could be construed as a breaking change if clients are switching on these values, so not sure if we need to take extra steps to change this. Thoughts? 👀 

**Version**

[04fb9c0](https://github.com/sigstore/cosign/commit/04fb9c0a5bdebf7580d772dfd3e439ae66ac2b8a) (latest main)

**Comment by wlynch** [comment]
cc @mattmoor @vaikas

**Comment by mattmoor** [comment]
Thanks for opening this! 🙏

**Comment by znewman01** [comment]
See also https://github.com/sigstore/cosign/issues/2596

**Comment by mattmoor** [comment]
I'm gonna send a PR for this.  I was attempting to cleanup the usage of shortnames in some `policy-controller` policies, and it's validation is too strict to accept these schemeless URIs 😞
