### ISSUE TITLE
accessing entity: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by thangarajav** [sigstore/cosign#2654]
**Description**

Background: I am trying to configure cosing in our ADO pipeline, we are building a image with cosign binary. And using that image we are creating a docker container and signing that image.
issue: We are getting some error while signing the image as below
# docker run -it --rm -v keys:/tango/keys tangaraja/cosign:v.1.0 /tango/cosign sign --key /tango/keys/cosign.key tangaraja/alpine:v1
WARNING: Image reference tangaraja/alpine:v1 uses a tag, not a digest, to identify the image to sign.
This can lead you to sign a different image than the intended one. Please use a
digest ([example.com/ubuntu@sha256:abc123...](http://example.com/ubuntu@sha256:abc123...)) rather than tag
([example.com/ubuntu:latest](http://example.com/ubuntu:latest)) for the input to cosign. The ability to refer to
images by tag will be removed in a future release.
****_Error: signing [tangaraja/alpine:v1]: accessing entity: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority
main.go:62: error during command execution: signing [tangaraja/alpine:v1]: accessing entity: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority_****
#

**Comment by thangarajav** [comment]
Please find the dockerfile 

FROM ubuntu
RUN mkdir -p /tango
RUN mkdir -p /tango/keys
RUN chmod 777 /tango
WORKDIR /tango
COPY  cosign .
RUN chmod 544 cosign
#COPY generatekeys.sh .
ENV COSIGN_PASSWORD=passwd
WORKDIR /tango/keys

**Comment by znewman01** [comment]
Folding into https://github.com/sigstore/cosign/issues/2659
