### ISSUE TITLE
Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by thangarajav** [sigstore/cosign#2659]
Background: I am trying to configure cosing in our ADO pipeline, we are building a image with cosign binary. And using that image we are creating a docker container and signing that image.
issue: We are getting some error while signing the image as below

```
docker run -it --rm -v keys:/tango/keys tangaraja/cosign:v.1.0 /tango/cosign sign --key /tango/keys/cosign.key tangaraja/alpine:v1
WARNING: Image reference tangaraja/alpine:v1 uses a tag, not a digest, to identify the image to sign.
This can lead you to sign a different image than the intended one. Please use a
digest ([example.com/ubuntu@sha256:abc123...](http://example.com/ubuntu@sha256:abc123...)) rather than tag
([example.com/ubuntu:latest](http://example.com/ubuntu:latest)) for the input to cosign. The ability to refer to
images by tag will be removed in a future release.
Error: signing [tangaraja/alpine:v1]: accessing entity: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority
main.go:62: error during command execution: signing [tangaraja/alpine:v1]: accessing entity: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority
```

We are able reach https://index.docker.io/v2/ from the VM but not from cosign container image.

```
root@master:/home/vagrant/test# curl https://index.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
root@master:/home/vagrant/test#
```

**Comment by znewman01** [comment]
I think this is inside go-containerregistry. CC @imjasonh: what CA bundle does g-cr use? Would it be different from the system one?

**Comment by imjasonh** [comment]
It shouldn't be any different from the system CA bundle. I don't even think we support [Docker's custom `certs.d` flow](https://docs.docker.com/engine/security/certificates/).

cc @jonjohnsonjr

**Comment by thangarajav** [comment]
Now i created a new docker image using relase tag: 2.0.0-rc.1
and run the same command got this new error

root@master:/home/vagrant# docker run -it --rm -v /tmp/keys:/tango/keys tangaraja/cosign:2.0.0 /tango/cosign sign --key /tango/keys/cosign.key tangaraja/cosign:v.1.0
WARNING: Image reference tangaraja/cosign:v.1.0 uses a tag, not a digest, to identify the image to sign.
    This can lead you to sign a different image than the intended one. Please use a
    digest (example.com/ubuntu@sha256:abc123...) rather than tag
    (example.com/ubuntu:latest) for the input to cosign. The ability to refer to
    images by tag will be removed in a future release.


        Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.

By typing 'y', you attest that you grant (or have permission to grant) and agree to have this information stored permanently in transparency logs.
Are you sure you would like to continue? [y/N] y
tlog entry created with index: 12039450
Pushing signature to: index.docker.io/tangaraja/cosign
Error: signing [tangaraja/cosign:v.1.0]: recursively signing: signing digest: POST https://index.docker.io/v2/tangaraja/cosign/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tangaraja/cosign Type:repository] map[Action:push Class: Name:tangaraja/cosign Type:repository]]
main.go:63: error during command execution: signing [tangaraja/cosign:v.1.0]: recursively signing: signing digest: POST https://index.docker.io/v2/tangaraja/cosign/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tangaraja/cosign Type:repository] map[Action:push Class: Name:tangaraja/cosign Type:repository]]
root@master:/home/vagrant#

**Comment by thangarajav** [comment]
# /tango/cosign sign --key /tango/keys/cosign.key tangaraja/cosign:v.1.2
WARNING: Image reference tangaraja/cosign:v.1.2 uses a tag, not a digest, to identify the image to sign.
    This can lead you to sign a different image than the intended one. Please use a
    digest ([example.com/ubuntu@sha256:abc123...](http://example.com/ubuntu@sha256:abc123...)) rather than tag
    ([example.com/ubuntu:latest](http://example.com/ubuntu:latest)) for the input to cosign. The ability to refer to
    images by tag will be removed in a future release.
        Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
By typing 'y', you attest that you grant (or have permission to grant) and agree to have this information stored permanently in transparency logs.
Are you sure you would like to continue? [y/N] y
tlog entry created with index: 12044697
Pushing signature to: [index.docker.io/tangaraja/cosign](http://index.docker.io/tangaraja/cosign)
Error: signing [tangaraja/cosign:v.1.2]: recursively signing: signing digest: POST https://index.docker.io/v2/tangaraja/cosign/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tangaraja/cosign Type:repository] map[Action:push Class: Name:tangaraja/cosign Type:repository]]
main.go:63: error during command execution: signing [tangaraja/cosign:v.1.2]: recursively signing: signing digest: POST https://index.docker.io/v2/tangaraja/cosign/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tangaraja/cosign Type:repository] map[Action:push Class: Name:tangaraja/cosign Type:repository]]
#
I configured the config.json and copied that file inside the container and got same issue
config.json
#
# cat /root/.docker/config.json
{
        "auths": {
                "[index.docker.io](http://index.docker.io/)": {
                        "auth": "dGFuZ2FyYWphOkdvbGRraW5nQDEyMw=="
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.06.2-ce (linux)"
        }
}#

Dockerfile:

root@master:/home/vagrant# cat Dockerfile
FROM ubuntu:20.04
RUN mkdir -p /tango/keys
RUN chmod 777 /tango
RUN mkdir -p /root/.docker/
COPY config.json /root/.docker/
RUN apt-get update && apt-get install -y curl
WORKDIR /tango
COPY cosign-linux-amd64 ./cosign
RUN chmod 544 cosign
ENV COSIGN_PASSWORD=passwd
WORKDIR /tango/keys
root@master:/home/vagrant#

**Comment by znewman01** [comment]
> copied that file inside the container

Oh, I think that's your problem. In general you're going to run into a lot of trouble trying to sign from *within* the container. That explains the issues with both authentication and network access.

What happens if you install cosign on the VM itself and run it from there?

**Comment by jonjohnsonjr** [comment]
> It shouldn't be any different from the system CA bundle. I don't even think we support [Docker's custom certs.d flow](https://docs.docker.com/engine/security/certificates/).

Yeah: https://github.com/google/go-containerregistry/issues/211

There are workarounds in that issue but also if someone wanted to implement support for that, I think we'd merge it.

**Comment by yiakwy** [comment]
hi @jonjohnsonjr  what is your workaround ? I try to cosign inside a container my freshly published images to a private registry. See this https://github.com/sigstore/cosign/issues/2329#issuecomment-1411582442 in issue #2329 .

Hi @imjasonh I think the README is not accurate since we are not ready to cosign inside a docker. In my personal view, all my development in workstations are inside docker and I have been trying to avoid "nested docker for CI". 

The current flow is to install `cosign` by a human in a computer with sudo privileges and cosign the freshly published images. But in the future I want to integrate this to CI without human intervention.

Could we do it?

**Comment by jonjohnsonjr** [comment]
> what is your workaround ?

If you require self-signed certs in your cert bundle, it's up to you to get those certs into the container. [Your image](https://explore.ggcr.dev/layers/tangaraja/cosign:v.1.0@sha256:4e37b0b8da93f8b27cb62a5aba206735fca05df5e057411ec465fe9016cbaf05/etc/os-release%20-%3E%20/usr/lib/os-release) appears to be ubuntu-based, so I believe you need to mount those certs as [`/etc/ssl/certs/ca-certificates.crt`](https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/crypto/x509/root_linux.go;l=9;drc=fd4b391849dcd3ac0e90d3a86b0ee7df00b9b269) or into [`/etc/ssl/certs`](https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/crypto/x509/root_linux.go;l=19;drc=fd4b391849dcd3ac0e90d3a86b0ee7df00b9b269).
