### ISSUE TITLE
Feature: GitHub Enterprise Server (GHES) support for 'cosign generate-key-pair github:'

### ISSUE THREAD

**Issue by netsandbox** [sigstore/cosign#2675]
**Description**

`cosign generate-key-pair github:` currently only supports `github.com` repositories.
It would be nice if [GitHub Enterprise Server](https://docs.github.com/en/enterprise-server@3.7/admin/overview/about-github-enterprise-server) (GHES) would be also supported by the above command.

**Comment by cpanato** [comment]
sounds good to me, let me take a look

**Comment by cpanato** [comment]
or are you willing to implement this @netsandbox?

**Comment by netsandbox** [comment]
I already created a PR with the changes.
I introduced a new `GITHUB_HOST` environment variable, similar to the `GITLAB_HOST` environment variable.

Maybe it makes sense to also support other environment variables for GitHub host and token.
For example [GitHub CLI](https://cli.github.com/manual/gh_help_environment) supports the following environment variables:
* GH_TOKEN
* GITHUB_TOKEN
* GH_ENTERPRISE_TOKEN
* GITHUB_ENTERPRISE_TOKEN
* GH_HOST

Supporting the same set of environment variables would make it easier for users who use both, GitHub CLI and cosign.
But I'm not sure if this is just to much.

**Comment by cpanato** [comment]
cool, thanks!

**Comment by cpanato** [comment]
> I already created a PR with the changes. I introduced a new `GITHUB_HOST` environment variable, similar to the `GITLAB_HOST` environment variable.
> 
> Maybe it makes sense to also support other environment variables for GitHub host and token. For example [GitHub CLI](https://cli.github.com/manual/gh_help_environment) supports the following environment variables:
> 
> * GH_TOKEN
> * GITHUB_TOKEN
> * GH_ENTERPRISE_TOKEN
> * GITHUB_ENTERPRISE_TOKEN
> * GH_HOST
> 
> Supporting the same set of environment variables would make it easier for users who use both, GitHub CLI and cosign. But I'm not sure if this is just to much.

this we can do in a follow up
