### ISSUE TITLE
GitLab provider

### ISSUE THREAD

**Issue by adanil** [sigstore/cosign#2697]
**Description**

Need a gitlab provider to automate the build and signing of artifacts. It can be implemented using the JWT token automatically generated by GitLab CI

**Comment by znewman01** [comment]
See also https://github.com/sigstore/cosign/issues/1254

**Comment by znewman01** [comment]
Does the token have an `aud` claim now?

**Comment by haydentherapper** [comment]
There's an open PR in Fulcio, but we might hold off on merging it until their OIDC issuer stabilizes (they said it's likely to change in the near future).
I don't think we should merge this into Cosign yet until there's support in Fulcio, or else you're just going to get errors on GitLab CI.

**Comment by haydentherapper** [comment]
@wlynch Is this now complete with the above PR submitted?

**Comment by wlynch** [comment]
Yeah I think we can.

There's some room for follow up work once https://gitlab.com/gitlab-org/gitlab/-/issues/390711 lands to request the JWT on demand like we do for github actions, but the current flow works well enough.
