### ISSUE TITLE
local image fails signature verification

### ISSUE THREAD

**Issue by choukri-m** [sigstore/cosign#2700]
**Description**

with a signed image saved locally, cosign returns an error when the local image is verified. see error:

```
Error: no matching signatures:
searching log query: [POST /api/v1/log/entries/retrieve][404] searchLogQuery default  &{Code:404 Message:no responses found}
main.go:63: error during command execution: no matching signatures:
searching log query: [POST /api/v1/log/entries/retrieve][404] searchLogQuery default  &{Code:404 Message:no responses found}
```

Steps to replicate error:
1. sign a docker image from a private registry using a key. NOTE ensure to **not upload to the transparency log** 
    e.g. `cosign sign --key cosign.key registry.private.com/image:tag`
2. store the image signed locally. e.g. `cosign save --dir /root/local/dir registry.private.com/image:tag`
3. verify the local image. `cosign verify --key cosign.pub --local-image /root/local/dir registry.private.com/image:tag`

The error seen is raised in `tlogValidateEntry` which should not be called in the scenario above as the image was signed without a record on the transparency log. (as I mentioned in the steps above, I did not accept adding this image to the rekor log). so the function correctly returns an error but it should not be called in the first place.

I am not sure if this is intentional to force all verifications to not skip the transparency log? But I see it as a bug since we are allowing images to be signed without having an entry to the transparency log

**Version**

This is only happening in V2.0.0-rc.1. not an issue in earlier versions

**Comment by znewman01** [comment]
Thanks for filing!

If I understand correctly this is working as intended. In v2, Cosign expects a transparency log entry by default.

If you pass the `--insecure-ignore-tlog` flag we won't check the transparency log. (The UX there could use some workshopping, we may wind up renaming the flag at some point.)

**Comment by choukri-m** [comment]
Thank you @znewman01, it worked with the flag you mentioned
so the bug was in earlier versions where it did not raise an error which consisted a change in the way it operated
Cheers
