### ISSUE TITLE
Cosign wraps in-toto predicates violating their schema

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#2713]
**Description**

In certain cases (`attest --type {cyclone|spdx}`) `cosign` will wrap the user-supplied in-toto predicate with its own little envelope:
1. `--type spdx`: https://github.com/sigstore/cosign/blob/e4cc8f1a132ea58f4d92a22626a9597887f6dd2b/pkg/cosign/attestation/attestation.go#L242-L247
2. `--type cyclonedx`: https://github.com/sigstore/cosign/blob/e4cc8f1a132ea58f4d92a22626a9597887f6dd2b/pkg/cosign/attestation/attestation.go#L255-L260

The purpose of `predicateType` in in-toto is to express the schema of the `predicate`, so I would argue that this extra wrapping is a bug because it changes the data to not match the expected schema.

**Version**

HEAD

cc @znewman01 @dlorenc @vaikas to fact check me

**Comment by vaikas** [comment]
I think this is a dupe of:
https://github.com/sigstore/cosign/issues/2126

**Comment by mattmoor** [comment]
Totally.  thanks for the pointer.
