### ISSUE TITLE
401 Unauthorized /api/v1/signingCert

### ISSUE THREAD

**Issue by mi1wei** [sigstore/cosign#2747]
**Description**

when i use enterprise github action, i got failed. 
when i use github action, it works righly.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/32791982/221463892-9d6e4b94-d470-443d-8602-a2a756821a44.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/32791982/221464276-ce80010c-15a2-475c-92d6-d0b85b05e63c.png">

**Version**

v2

**Comment by znewman01** [comment]
Closing as a duplicated of https://github.com/sigstore/fulcio/issues/1022
