### ISSUE TITLE
Image Verification Failing

### ISSUE THREAD

**Issue by learningcicd** [sigstore/cosign#2763]
**Question**
Image Verification Failing!
error getting target ctfe.pib by usage : error verifying local metadata; local cache may be corrupt:  tuf: failed to decode snapshot.json: expired at 2023-03-01..

**Comment by znewman01** [comment]
Can you run `rm -rf ~/.sigstore` and try again?

**Comment by znewman01** [comment]
Reopen if you're still experiencing this.
