### ISSUE TITLE
README: intro .gif shows pre-keyless command-line flow

### ISSUE THREAD

**Issue by tstromberg** [sigstore/cosign#2764]
https://github.com/sigstore/cosign/blob/main/images/intro.gif (included in the README.md) was last updated two years ago, in Feb 2021. It should be refreshed to demonstrate the new default keyless command-line flow.

**Comment by enyinna1234** [comment]
I'd like to work on this issue.

**Comment by haydentherapper** [comment]
Can we just delete it? We did that in the docs repo already. Given you can’t copy commands from it, it doesn’t add much value
