### ISSUE TITLE
question: can we ignore if the signature already there?

### ISSUE THREAD

**Issue by tuananh** [sigstore/cosign#2775]
case: image has already been signed but i didnt know in advance. is there a way to ignore the error during sign if signature is already there in the registry?

**Comment by developer-guy** [comment]
AFAIK this is not possible today since you can sign your container image as much as you want 🤔

**Comment by tuananh** [comment]
> AFAIK this is not possible today since you can sign your container image as much as you want 🤔

in my case, the registry is immutable so re-uploading the sig is not possible. i guess i can check the sig in advance and do not sign again?

not sure if there's any security implication.

**Comment by znewman01** [comment]
> i guess i can check the sig in advance and do not sign again?

+1. Something like `cosign verify || cosign sign`.

Maybe https://github.com/sigstore/sigstore/issues/784 would help too, if we had a code for "failed to upload to registry"

> not sure if there's any security implication.

This should be okay.

------------------------------------------------

I'm going to close this out, but please let us know if that doesn't address your question.
