### ISSUE TITLE
How to integrate own kms into Cosign and policy-controller admission controller?

### ISSUE THREAD

**Issue by qiaozhi92** [sigstore/cosign#2776]
Currently, we have developed own kms, and want to sign and verify signatures for container images using our kms.
How to integrate own kms into Cosign and policy-controller admission controller?
Is there any development documentation and guidance?
thanks！

**Comment by hectorj2f** [comment]
@qiaozhi92 We don't have any documentation on how to support custom KMS services if they are not part of the list of supported ones.

**Comment by znewman01** [comment]
Let's track this over here: https://github.com/sigstore/cosign/issues/2776
