### ISSUE TITLE
Statement about new polynonce attack

### ISSUE THREAD

**Issue by bratkartoffel** [sigstore/cosign#2777]
**Question**

Hello,

First off: Thank you for this great tool!
Can you please share some thoughts about the polynonce attack? As cosign uses ECDSA keys and signatures it may be affected by this. How is the nonce for the signature generated?

https://research.kudelskisecurity.com/2023/03/06/polynonce-a-tale-of-a-novel-ecdsa-attack-and-bitcoin-tears/

Thanks,
Simon

**Comment by znewman01** [comment]
We use a [cryptographically secure random number generator](https://pkg.go.dev/crypto/rand) and are unaffected.
