### ISSUE TITLE
Add Buildkite provider

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#2778]
**Description**

Fulcio now has support for issuing certificates for identities from Buildkite, and this has been rolled out to production. We should add a [provider](https://github.com/sigstore/cosign/tree/main/pkg/providers) to support fetching an identity token from an environment variable or API call.

cc @sj26 @mattmoor

**Comment by mattmoor** [comment]
Yeah, this would be awesome.  I'm not sure how well it is surfaced as SDK, but a library form of:
```shell
buildkite-agent oidc request-token --audience sigstore
```

... would be 🔥
