### ISSUE TITLE
Cosign 'verify' fails to verify the same image on the another Harbor 

### ISSUE THREAD

**Issue by omkhard** [sigstore/cosign#2789]
**Description**

'cosign verify' fails for verifying image uploaded to another harbor with the same signature attached to the image as when the signed in from other harbor's instance.
Could it be an issue or signature attaching requires some additional payload/bundle/Body attaching?

###cosign verify --key cosign.pub  172.29.85.133/omtest1/newdebian:9 --allow-insecure-registry
Error: no matching signatures:
searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}
 searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}
 searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}
main.go:62: error during command execution: no matching signatures:
searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}
 searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}
 searching log query: [POST /api/v1/log/entries/retrieve][400] searchLogQueryBadRequest  &{Code:400 Message:unmarshalling entry: verifying signature: invalid signature when validating ASN.1 encoded signature}

**Comment by hectorj2f** [comment]
@omkhard Can you describe which cosign version are you using ? Is cosign v2.0.0 ?

**Comment by hectorj2f** [comment]
This issue seems a duplicated of #2790.

**Comment by ikwork** [comment]
Hi,

yes

cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v2.0.0
GitCommit:     d6b9001f8e6ed745fb845849d623274c897d55f2
GitTreeState:  clean
BuildDate:     2023-02-23T19:26:35Z
GoVersion:     go1.20.1
Compiler:      gc
Platform:      linux/amd64

**Comment by hectorj2f** [comment]
@ikwork @omkhard Let's keep one single issue open :). I'll close this issue so we can focus on #2790

**Comment by omkhard** [comment]
sure @hectorj2f we can close this , I am facing this on version v2.0.0-rc.0 , I downloaded this from release section tar gzips.

**Comment by hectorj2f** [comment]
@omkhard We have a v2.0.0 release, so I suggest you to use that version instead.
