### ISSUE TITLE
cosign verify fails for image uploaded to another harbor with same signature attached

### ISSUE THREAD

**Issue by ikwork** [sigstore/cosign#2790]
**Description**
Hi,

cosign verify fails for image uploaded to another harbor with same signature attached.

I have two disconnected harbor registries A and B and following the the below procedure:

1. upload image myimage to harbor A
`docker push harborA/myproj/myimage:tag`

2. cosign sign (with upload=false) on harbor A, create signature file myimage.sig
`cosign sign --allow-insecure-registry --key cosign.key --upload=false --output-signature=myimage.sig harborA/myproj/myimage@digest`

3. tar image and signature, copy to B
`scp myimage.tar myimage.sig user@hostB`

4. upload image to harbor B (docker load, tag then push)
```
user@hostB# docker load < myimage.tar
user@hostB# docker tag harborA/myproj/myimage:tag harborB/myproj/myimage:tag
user@hostB# docker push harborB/myproj/myimage:tag
```

5. cosign attach signature myimage.sig to image uploaded on harbor B (this results in the green "signed by cosign" tick)
`cosign attach signature --allow-insecure-registry --signature myimage.sig harborB/myproj/myimage:tag`

6. cosign verify image
`cosign verify --insecure-ignore-tlog=true --allow-insecure-registry --check-claims=false --key cosign.pub harborB/myproj/myimage:tag`

Step 6 Fails with the following error:
```
Error: no matching signatures:
invalid signature when validating ASN.1 encoded signature
main.go:69: error during command execution: no matching signatures:
invalid signature when validating ASN.1 encoded signature
```

Step 6 works just fine if attach and verify are done on the same harborA

We're skipping transparency log validation.

**Version**

2.0

**Comment by hectorj2f** [comment]
@ikwork  Have you tried using `cosign copy` command ?

**Comment by ikwork** [comment]
Hi hectorj2f, thanks for the reply

the two harbors are disconnected and owned by separate entities and don't have public connectivity. would cosign copy still work in airgap?

I'll try this rn and update asap

Thanks

**Comment by hectorj2f** [comment]
@ikwork I believe you could use `cosign save` and then `cosign copy` if you need to do it in an airgap env.

**Comment by ikwork** [comment]
Hi hectorj2f, thanks for the feedback

the cosign save doesn't seem to be working with insecure registry

```
cosign save --dir ./mysavedimage <harborAIP>/myproj/myimage:1.0

Error: signed entity: Get "https://<harborAIP>/v2/": tls: failed to verify certificate: x509: cannot validate certificate for <harborAIP> because it doesn't contain any IP SANs; Get "https://<harborAIP>:443/v2/": tls: failed to verify certificate: x509: cannot validate certificate for <harborAIP> because it doesn't contain any IP SANs
main.go:74: error during command execution: signed entity: Get "https://<harborAIP>/v2/": tls: failed to verify certificate: x509: cannot validate certificate for <harborAIP> because it doesn't contain any IP SANs; Get "https://<harborAIP>:443/v2/": tls: failed to verify certificate: x509: cannot validate certificate for <harborAIP> because it doesn't contain any IP SANs
```

Adding the --allow-insecure-registry doesn't seem to work either
```
cosign --allow-insecure-registry save --dir ./mysavedimage <harborAip>/myproj/myimage:2.0
Error: unknown command "<harborAip>/myproj/myimage:2.0" for "cosign"
Run 'cosign --help' for usage.
main.go:74: error during command execution: unknown command "<harborAip>/myproj/myimage:2.0" for "cosign"
```

**Comment by hectorj2f** [comment]
@ikwork Yes, it seems there isn't support for insecure registries when using `cosign save`.

**Comment by ikwork** [comment]
Thanks @hectorj2f for the confirmation.

Is there a possibility that it may be supported any time? Anyway, I'll try with tls configured and update if it works.

But, regarding the original approach. After uploading the same image to anothe harbor and doing "cosign attach" I can see that the image is considered "signed by cosign" in harbor, but I can't verify it (with the same pub key). Is there a reason why it may be failing? Apart from the signature is there something else that may need to be uploaded?

Regards

**Comment by ikwork** [comment]
Hi @hectorj2f 

The cosign copy/load works fine with tls configured registry. Thanks for the suggestion.

But please guide us through resolving the "cosign attach" issue.

Regards

**Comment by hectorj2f** [comment]
@ikwork I'd suggest you to open a PR adding support for insecure-registry when using `cosign save` and tests these changes, so you can use `cosign save` and `cosign copy`.

**Comment by hectorj2f** [comment]
@ikwork I'd generally suggest to use `cosign save/copy` to achieve your goal instead of `cosign attach`. However I'd like to know how you're verifying your image. Could you share all the commands you ran to reach that error ?

**Comment by ikwork** [comment]
Hi @hectorj2f 

Sure, following are the commands I run, pls let me know if you need anything more

```
On hostA (harborA)
==================

docker push harborA/myproj/myimage:tag
docker save harborA/myproj/myimage:tag > myimage.tar

cosign sign --allow-insecure-registry --key cosign.key --upload=false --output-signature=myimage.sig harborA/myproj/myimage@digest

scp myimage.tar myimage.sig cosign.pub user@hostB:~/

On hostB (harborB)
==================

docker load < myimage.tar
docker tag harborA/myproj/myimage:tag harborB/myproj/myimage:tag
docker push harborB/myproj/myimage:tag

// This results in the green "signed by cosign" tick
cosign attach signature --allow-insecure-registry --signature myimage.sig harborB/myproj/myimage:tag

// Verify image fails
cosign verify --insecure-ignore-tlog=true --allow-insecure-registry --check-claims=false --key cosign.pub harborB/myproj/myimage:tag

Error: no matching signatures:
invalid signature when validating ASN.1 encoded signature
main.go:69: error during command execution: no matching signatures:
invalid signature when validating ASN.1 encoded signature
```
