### ISSUE TITLE
Add GPG signatures to cosign releases

### ISSUE THREAD

**Issue by udf2457** [sigstore/cosign#2833]
At the moment, your releases present a bit of a "chicken or egg" scenario.

You only provide keyless signatures, which can only be verified with ... yes, that's right `cosign`.

So I would suggest there really there needs to be an out-of-band mechanism to enable people to verify `cosign` binaries when they don't have a pre-existing cosign installation.

**Comment by haydentherapper** [comment]
As discussed in https://github.com/sigstore/rekor/issues/1399#issuecomment-1482831421, we do sign our releases with a [dedicated key](https://github.com/sigstore/root-signing/blob/main/targets/artifact.pub), although it's an ECDSA key and not PGP. We'll update the instructions for verifying the TUF repository without Cosign.
