### ISSUE TITLE
Remove cosign policy command

### ISSUE THREAD

**Issue by rdimitrov** [sigstore/cosign#2836]
**Description**

Hey, based on the discussions in https://github.com/sigstore/sigstore/pull/737 (ref. https://github.com/sigstore/sigstore/pull/737#issuecomment-1480108979) is it right to assume that the `cosign policy` command should be deprecated since the code it depends on is going to be removed too?

Thanks in advance 👍

**Comment by znewman01** [comment]
CC @asraa @priyawadhwa 

I believe that's the case, as I don't know that anybody actually uses this feature. We should ask around a little first.

**Comment by rdimitrov** [comment]
Thanks, Zack 👍 

I already had a branch ([dimitrovr/remove-policy](https://github.com/rdimitrov/cosign/tree/dimitrovr/remove-policy)) with removing it but we should see if all agree to deprecate it.

**Comment by rdimitrov** [comment]
Let me know when it's decided and I'll open a PR 👍

**Comment by znewman01** [comment]
I think you can go for it, @rdimitrov !
