### ISSUE TITLE
Cleanup cosign help text with a custom printer

### ISSUE THREAD

**Issue by eddiezane** [sigstore/cosign#2887]
**Description**

The output of `cosign verify --help` is unreadable due to line wrapping.

![image](https://user-images.githubusercontent.com/959573/231228700-d087baf3-7579-44b3-8ee3-9aa05b100f92.png)

We solved this in kubectl by creating a custom tab printer.

https://github.com/kubernetes/kubernetes/pull/104736

**Comment by hrittikhere** [comment]
Can I get this assigned? I want to try this :D

**Comment by znewman01** [comment]
Thanks for volunteering! Let us know if you need any assistance.

**Comment by rnjudge** [comment]
@hrittikhere are you still working on this? Otherwise, I would like to work on it :)

**Comment by hrittikhere** [comment]
Hey @rnjudge I am actually trying a few iterations and should have something by this week. I will ping you if the results are not optimal so you can take over :)

**Comment by znewman01** [comment]
A little bit more color: you could do this one of two ways.

The "right" way to do this is to send a PR upstream to Cobra addressing https://github.com/spf13/cobra/issues/810 .  This will be slower and take longer.

The easy way (probably what you should do first) is to basically copy https://github.com/kubernetes/kubernetes/pull/104736 .
