### ISSUE TITLE
Support attaching a Rekor bundle to a container

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#2904]
**Description**

`cosign attach` supports attaching signatures, but not Rekor bundles. Should be straightforward to add support.

**Comment by mritunjaysharma394** [comment]
Hi @haydentherapper, seems like this can be a good first issue to begin and contribute to cosign, would love to pick up this issue if no one is working yet on it

**Comment by tannerjones4075** [comment]
What is the status of this issue? Should it be closed?
