### ISSUE TITLE
Enhancing cosing attach signature command to include RFC3161 Timestamp response

### ISSUE THREAD

**Issue by Mukuls77** [sigstore/cosign#2979]
**Description**

The existing cosign attach command does not support passing RFC3161Timestamp response from TSA as an argument. The cosing attach command should be enhanced to support attachment of the TSA response  along with existing functionality to attach signature, certificate and certificate chain.
This functionality will help the Private CA use case of cosign where cosign uses which want to use a Private PKI to sign the content would also be able to attach the Trusted TSA response for the generated Signature. so that Certificate validity can be checked with the Trusted signature Time stamp and short lived certificates can be generated for code signing.

The existing cosign attach command is as below. i would like to contribute for this enhancement. in cosign code.
 
Attach signatures to the supplied container image

Usage:
  cosign attach signature [flags]

Examples:
  cosign attach signature <image uri>

Flags:
      --allow-http-registry                                                                      whether to allow using HTTP protocol while connecting to registries. Don't use this for anything but testing
      --allow-insecure-registry                                                                  whether to allow insecure connections to registries (e.g., with expired or self-signed TLS certificates). Don't use this for anything but testing
      --attachment-tag-prefix [AttachmentTagPrefix]sha256-[TargetImageDigest].[AttachmentName]   optional custom prefix to use for attached image tags. Attachment images are tagged as: [AttachmentTagPrefix]sha256-[TargetImageDigest].[AttachmentName]
      --certificate string                                                                       path to the X.509 certificate in PEM format to include in the OCI Signature
      --certificate-chain string                                                                 path to a list of CA X.509 certificates in PEM format which will be needed when building the certificate chain for the signing certificate. Must start with the parent intermediate CA certificate of the signing certificate and end with the root certificate. Included in the OCI Signature
  -h, --help                                                                                     help for signature
      --k8s-keychain                                                                             whether to use the kubernetes keychain instead of the default keychain (supports workload identity).
      --payload string                                                                           path to the payload covered by the signature (if using another format)
      --signature string                                                                         path to the signature, or {-} for stdin

Global Flags:
      --output-file string   log output to a file
  -t, --timeout duration     timeout for commands (default 3m0s)
  -d, --verbose              log debug output

**Comment by znewman01** [comment]
CC @haydentherapper @malancas for TSA

**Comment by haydentherapper** [comment]
I'm supportive of this!

**Comment by Mukuls77** [comment]
I have done the changes needed for the Issue. i cloned the cosign project and create a new branch  MukulAddCmdChange

$ git status
On branch MukulAddCmdChange
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   cmd/cosign/cli/attach.go
        modified:   cmd/cosign/cli/attach/sig.go
        modified:   cmd/cosign/cli/options/attach.go
        modified:   doc/cosign_attach_signature.md
        modified:   test/e2e_test.go
        modified:   test/e2e_test_attach.sh
        new file:   test/testdata/test_attach_freetsacacert.pem

but when i am trying to push my changes to origin i am getting following issue

musharma@N-20S1PF2LWWHM MINGW64 ~/cosign (MukulAddCmdChange)
$ git push -u origin MukulAddCmdChange
remote: Permission to sigstore/cosign.git denied to Mukuls77.
fatal: unable to access 'https://github.com/sigstore/cosign.git/': The requested URL returned error: 403

----

I have tried many thing like clearing the credentials from window manager for github site.
creating a new github account. but noting is working.
can you pls suggest what can be the issue here why i am getting 403 response when i try to push my changes.

**Comment by Mukuls77** [comment]
I have created the Pull request to cover this issue

https://github.com/sigstore/cosign/pull/3001

**Comment by Mukuls77** [comment]
@haydentherapper @malancas can you pls review the PR created to close this issue.

https://github.com/sigstore/cosign/pull/3001

**Comment by Mukuls77** [comment]
This issue can be resolved now as the mentioned PR covering this issue has been approved
