### ISSUE TITLE
cosign load '--allow-insecure-registry' 

### ISSUE THREAD

**Issue by clemenko** [sigstore/cosign#2986]
**Description**
There is a need for being able to 'load' an image to a registry that is had either NO tls cert, or a self signed one. Having the ability to tell cosign to ignore the cert, or use http instead is important. 

Use case. Tactical edge deployments for the Government. ;)

**Comment by znewman01** [comment]
Should this be titled "cosign *load* ---allow-insecure-registry"?

**Comment by clemenko** [comment]
It looked like it was not a flag for all verbs. We can change the issue title if it makes sense.

**Comment by znewman01** [comment]
It doesn't necessarily make sense for every verb (think: `cosign sign-blob`) but agreed with the overall point. Do you know of any others besides `load`? It's in 19 different commands at this point :) 

Should just be a matter of getting a [`RegistryOptions`](https://github.com/sigstore/cosign/blob/b57ccbc835e21344ccd64c52dc3aa34c079d7145/cmd/cosign/cli/options/registry.go#L41) into that command.

**Comment by clemenko** [comment]
There was reference to the flag in another issue : https://github.com/sigstore/cosign/issues/311
Getting it working with `load` will be greatly helpful with loading into tactical edge deployments.

**Comment by mritunjaysharma394** [comment]
I was playing with commands only recently while contributing to #2994, I think it can be a quick win, let me know if I can pick up this?

**Comment by clemenko** [comment]
When can we see the new release?

**Comment by znewman01** [comment]
Real Soon Now (TM): https://github.com/sigstore/sigstore/pull/1166#issuecomment-1562784568 

:)
