### ISSUE TITLE
add support for mTLS connection to the TSA (timestamp server)

### ISSUE THREAD

**Issue by dmitris** [sigstore/cosign#3006]
**Description**

Currently there is no way to:
* pass client TLS certificates when establishing https connection to the timestamp server (TSA)
* specify custom CA certificate chain for that connection except the `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables which have a number of disadvantages such as 1) not having any effect on Darwin or Windows 2) to overwrite instead of extending the system certificate store you normally need to set _both_ `SSL_CERT_FILE` and `SSL_CERT_DIR`, possibly to some "fake" locations (overwriting instead of extending is necessary if you want to make sure that only custom CA certs can be used for the connection to the TSA)
* specify SAN values that the server's certificates must have (SAN validation of the TSA server's TLS certificates)

These missing features make it currently impossible to use a TSA server in an environment where every connection must be done using mTLS (for example cloud setup where mTLS is required for authentication and authorisation).

Currently we have the `--timestamp-server-url` parameter for `cosign sign`.  
We can add additional command-line (or possibly configuration) parameters to add those features. We can borrow some names from the corresponding `curl` parameters:
```bash
$ curl --help all | egrep 'cert|key'
     --cacert <file>      CA certificate to verify peer against
-E, --cert <certificate[:password]> Client certificate file and password
      --key <key>          Private key file name
     --key-type <type>    Private key file type (DER/PEM/ENG)
     --pass <phrase>      Pass phrase for the private key
```
     
Some possible new parameter names:     
* `--timestamp-server-cacert`
* `--timestamp-server-cert`
* `--timestamp-server-key`
* `--timestamp-server-san`   # for SAN validation of the TSA server's certificates

Eventually, for the "full blown" mTLS, it would be good to have a parameter on the server's side to specify the allowed values in the SAN values of the client's TLS certificate.

References:

1. https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_default_verify_paths.html
2. https://go.googlesource.com/go/+/refs/heads/master/src/crypto/x509/cert_pool.go#102
> 
```
On Unix systems other than macOS the environment variables SSL_CERT_FILE and
SSL_CERT_DIR can be used to override the system default locations for the SSL
certificate file and SSL certificate files directory, respectively. The
latter can be a colon-separated list.
```
3. https://go-review.googlesource.com/c/go/+/36093 crypto/x509: load certs from env vars + extra locations
4. [Discussion](https://gophers.slack.com/archives/C6CKB7AA2/p1685095252459469?thread_ts=1685051992.319459&cid=C6CKB7AA2) about `SSL_CERT_FILE` and `SSL_CERT_DIR` in #crypto channel of the Gophers slack (highlights that both needs to be set to achieve overwrite of the system roots)

**Comment by haydentherapper** [comment]
Is this useful for more than just the timestamp server connection? Should these be global flags for all HTTPS connections?

I'm supportive of this feature. Ideally we could also push for Golang to fix this in the core library.

**Comment by hslatman** [comment]
@haydentherapper IMO, supporting mTLS configuration is useful for other server connections too. But depending on the deployment, different servers may require different client certs (chaining to different roots) and may be serving a TLS certificate chaining to different roots. Global flags could thus work for environments where a single client cert + server root CA are in use, but having "server-specific" flags (e.g. for a TST) to override the globals may be necessary too.

**Comment by dmitris** [comment]
> Should these be global flags for all HTTPS connections?
As @hslatman mentioned, the "globally" can be tricky since the needs & requirements are likely differ depending on the connection.  For example, in our case we must have mTLS to the timestamp server but not to the Docker Registry (though in principle I'm for mTLS everywhere 😄).  I suggest that we start with the TSA connection and use it as a sort of a "pilot" use case - possibly extending it to other connections later (such as recor and fulcio).

Does cosign has a config file where those options could be specified?   Let's imagine that we eventually get mTLS support for connections with TSA, fulcio, and recor - that could be a lot of command-line flags! 😄   As a user, if I had to choose, I would prefer to have or start with the command-line flags, especially since there is `--timestamp-server-url` already - but eventually it would be good to be able to specify options both through config files and command-line parameters, with the usual precedence (command-lines higher one than the config file).  For now, since the output of both `cosign --help | grep -I config` and `cosign sign --help | grep -I config` is empty, I assume there is no config file support yet.

If you guys don't have objections, I'm going to start preparing a PR with the described parameters (in a couple of weeks, after a vacation 🍹 )

**Comment by haydentherapper** [comment]
We don't have a configuration file. I recall discussing this previously though I can only find an example for `cosign initialize`, not in general. We do have a mapping between environment variable and flag name, so hopefully it'd be straightforward to also support a configuration yaml file for example.

No objections from me, thanks!

**Comment by hslatman** [comment]
@dmitris putting `-server-` in the middle might be slightly confusing, because from the `cosign` side it's a client certificate. Cosign is the client of the timestamp server in this case, so `--timestamp-client-` fits better, imo.

**Comment by dmitris** [comment]
implemented in https://github.com/sigstore/cosign/pull/3052 - initially for `cosign sign`.  If it looks OK and the Reviewers prefer to add this for all commands interacting with the TSA server, I can add it.  Tested that the modified version allows to run `cosign sign` against `timestamp-authority` server using custom (internal) certificates and CA, run with the command like:
```bash
sudo $HOME/gh/sigstore/timestamp-authority/bin/timestamp-server serve --disable-ntp-monitoring --scheme https --tls-ca /opt/xyz/share/ssl/certs/a_certificate_bundle.pem --tls-certificate /var/certs/cert.pem --tls-key /var/keys/key.pem --tls-host $(hostname) --tls-port 4443
```
