### ISSUE TITLE
Does Cosign support sub-keys?

### ISSUE THREAD

**Issue by lmarchione-r7** [sigstore/cosign#3019]
**Question**
In TLS PKI, it is generally considered best practice to create a root certificate authority (CA), but NOT use that CA to sign individual leaf certificates. Instead, you should create one or more intermediate CAs which are signed by the root CA. Those intermediate CAs should then be used to either create more CAs, or sign individual leaf certificates. This creates a certificate chain (example below).

```mermaid
  graph TD;
      A[root CA]-->B[Intermediate CA 1]
      A-->C[Intermediate CA 2]
      B-->D[Leaf certificate 1]
      B-->E[Leaf certificate 2]
      C-->F[Leaf certificate 3]
      C-->G[Leaf certificate 4]
```

This has a number of benefits:

- The root CA private key only needs to be used when signing intermediate CAs, then can be kept offline the rest of the time
- Individual leaf certificates can have a shorter expiration timeframe (e.g., docs.sigstore.dev is [90 days](https://crt.sh/?id=9033218940)), while the root CA certifcate can have a long expiration timeframe (e.g., [20 years](https://crt.sh/?id=9314791) in the case of Let's Encrypt)
-  You only need to trust the root CA public certificate on each device (not each intermediate CA public certificate). Anything signed by that root CA public certificate will be trusted.

Does cosign have similar functionality?

**Potential use case**
We want to use a different cosign key for each Jenkins instance we have. However, this would require us to publish multiple cosign public keys. This could be confusing for customers trying to verify our Docker images if we have to specify a specific key for one image, a different key for another, etc...

It would be much easier if cosign had the concept of sub-keys. This way, we would only be required to give out one "root" public key, which could then be used to verify images signed by any of that root's sub-keys.

**Comment by haydentherapper** [comment]
Hey, this is already supported by the sigstore infrastructure and actually how the public instance of our CA, Fulcio, is configured. Certificates are issued from an intermediate CA. Note that both the root and intermediate are shipped through our TUF root of trust (see https://github.com/sigstore/root-signing/tree/main/targets for the list of targets), so it doesn't really matter if we were to use a root vs intermediate, as both are a part of our root of trust.

I would recommend reading over https://docs.sigstore.dev/security/ to learn more about identity-based signing. You could for example configure a service account for your Jenkins instance, and for each signing, use an identity token for that service account to fetch a certificate from the Fulcio CA.

**Comment by lmarchione-r7** [comment]
@haydentherapper  - Sorry about the confusing wording. I was specifically wondering about locally-generated cosign keys (e.g., when running `cosign generate-key-pair`), not the certificates that Fulcio uses.
