### ISSUE TITLE
`cosign download attestation` cannot filter by attestation predicate type

### ISSUE THREAD

**Issue by lcarva** [sigstore/cosign#3030]
**Description**

Given a test image:

```bash
$ IMAGE='quay.io/lucarval/festoji@sha256:61ac53fe9316734ed8a8bc6418b2c371730a2c122b5df1d7f76b960d381f5457'
```

I can download all of its attestations:

```bash
$ cosign download attestation $IMAGE | jq '.payload | @base64d | fromjson | .predicateType'
"https://slsa.dev/provenance/v0.2"
"https://spdx.dev/Document"
```

However, I cannot use the `--predicate-type` parameter to select the SLSA provenance attestation:

```bash
$ cosign download attestation $IMAGE --predicate-type 'https://slsa.dev/provenance/v0.2'
Error: no attestations with predicate type 'https://slsa.dev/provenance/v0.2' found
main.go:74: error during command execution: no attestations with predicate type 'https://slsa.dev/provenance/v0.2' found
```

However, it does work for the SBOM attestation:
```bash
$ cosign download attestation $IMAGE --predicate-type 'https://spdx.dev/Document'
{"payloadType":"application/vnd.in-toto+json","payload":"...
```

**Version**

```
🐚 cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v2.0.2
GitCommit:     871448050b924a7946ebe47678f23aae09ef432d
GitTreeState:  clean
BuildDate:     2023-04-24T17:31:42Z
GoVersion:     go1.20.3
Compiler:      gc
Platform:      linux/amd64
```

I can also reproduce the issue on the current HEAD of main (83c08ce4f35116da7c74350a67d5740ca5e28ca5).

**Comment by lcarva** [comment]
It looks like the `cosign download attestation` command requires the `predicateType` annotation when filtering: https://github.com/sigstore/cosign/blob/83c08ce4f35116da7c74350a67d5740ca5e28ca5/pkg/cosign/fetch.go#L153-L163

Sure enough, the SLSA Provenance attestation doesn't have that annotation, but the SBOM does.

There's disparity in how the `download attestation` and the `verify-attestation` commands work. I *can* filter by predicate type on the second:

```bash
cosign verify-attestation $IMAGE --certificate-identity-regexp '.*'  --certificate-oidc-issuer-regexp '.*' --type 'https://slsa.dev/provenance/v0.2'

Verification for quay.io/lucarval/festoji@sha256:61ac53fe9316734ed8a8bc6418b2c371730a2c122b5df1d7f76b960d381f5457 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The code-signing certificate was verified using trusted certificate authority certificates
Certificate subject: https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v1.4.0
Certificate issuer URL: https://token.actions.githubusercontent.com
GitHub Workflow Trigger: push
GitHub Workflow SHA: d9f2616186b454700a4c196e696b9a60fdcecfdb
GitHub Workflow Name: Package
GitHub Workflow Repository: lcarva/festoji
GitHub Workflow Ref: refs/heads/master
{"payloadType":"application/vnd.in-toto+json","payload":"
```

That's the because the `verify-attestation` command parses each attestation and does a comparison of the predicate type based on the payload data:
https://github.com/sigstore/cosign/blob/83c08ce4f35116da7c74350a67d5740ca5e28ca5/pkg/policy/attestation.go#L84-L87

**Comment by lcarva** [comment]
The problem seems to be that older cosign versions do not add the `predicateType` annotation. In fact, it was added simultaneously with support for filtering by predicate type: https://github.com/sigstore/cosign/commit/dd747eeade444d42a5c55c35adf5c17831d60c6c

**Comment by znewman01** [comment]
That sounds right to me—it does the right thing in more circumstances (including better backwards compat).

CC @chaospuppy would love your thoughts here!

**Comment by lcarva** [comment]
@chaospuppy, thanks for the prompt reply! See inline comments below.

>  1. Doing this meant that tools outside of the `cosign` ecosystem could find and retrieve the desired attestation blob using more-readily available manifest/manifest-layer metadata

I'd be overly cautious of using a field that is not part of the spec.

>  2. You wouldn't need to perform the more resource-hungry processes of decoding each payload before inspecting it

Good point. I do think we should favor correctness over performance. IMO the performance hit here is negligible.


> I do think it's confusing to have started adding the annotations at the same time they became usable, but that's why the default behavior matches what it was previously, where all the attestations are returned if a `--predicateType` isn't specified.

The issue is that the `predicateType` annotation is not part of any standard. If it were, then there would've been no issue with adding support for reading and writing at the same time.

> Maybe it would be best to update the fallback behavior if a `--predcateType` _is_ specified, but no matching annotations are found, to use the `verify-attestation` method instead of failing?

I think this is an improvement over the current approach. However, I take issue in it being _different_ than what `verify-attestation` does. As a user, it is very confusing when those commands don't behave the same way.

I made a PR which makes the logic the same for both commands: https://github.com/sigstore/cosign/pull/3031

Happy to hear what you think!

**Comment by chaospuppy** [comment]
Ultimately I'm good with the PR being made because the annotations will still be getting created, but there's probably some followup work on my end to get the `predicateType` (or more likely something like `dev.sigstore.cosign/predicatetype`) into the [layer](https://github.com/sigstore/cosign/blob/main/pkg/oci/signature/layer.go) so it's a bit more standardized.  When that happens, perhaps this short cut (no payload processing up front) could be re-added in both `verify-attestation` and `download attestation`?  Thoughts @znewman01 ?

**Comment by znewman01** [comment]
At the risk of complicating things even further, how does this play with [OCI 1.1 reference types](https://github.com/opencontainers/distribution-spec/pull/335) which support [a filter by `artifactType`](https://github.com/opencontainers/distribution-spec/blob/58a1fe939258cb1c688ab49f819bde65eb401f75/spec.md?plain=1#L746)? Is the `artifactType` always going to be just `application/vnd.dsse.envelope.v1+json` (in which case this is moot) or would we ever encode the predicate type into the `artifactType` somehow?

CC @sudo-bmitch 


----------------------------

Overall I defer to you all. My priorities are consistency between the different commands and correctness (no surprise missing data), and performance is a distant third. So I think I'd be okay with *either*:

1. Fallback workflow: use the annotation if it exists, and if it doesn't fall back to parsing the JSON blob.
2. Just parse the JSON.

IIUC #3031 does (2).

Please let me know if I'm misunderstanding anything here, the OCI side of Cosign is not my strength :)

**Comment by lcarva** [comment]
I'm not too familiar with `artifactType`, but it looks like, if anything, this would be set to a type that indicates that the artifact is an in-toto statement. The predicate type is one level deeper.

> Fallback workflow: use the annotation if it exists, and if it doesn't fall back to parsing the JSON blob.

If we do this in `download attestation`, we should probably also do it in `verify-attestations` to provide consistency. I can think of a couple of use cases where even with a fallback option, the filtering would be different.

I think we should go with option 2, which is what the PR does, at least for now. There's a longer term feature request to push the predicate type annotation into the in-toto standard(?) to facilitate querying. Having cosign continuing adding those annotation makes sense to me and brings us closer to this goal.

**Comment by sudo-bmitch** [comment]
For an artifact, you do not want to use "application/vnd.oci.image.config.v1+json" for the config. That's a sign that this is a container image (though runtimes will throw errors when they see the layer media type). Instead you either need a dedicated config blob with your own type and content, or if you have no separate config, you would use the artifactType field. We are finishing up what the config descriptor would contain in https://github.com/opencontainers/image-spec/pull/1068, but most likely an artifact that is just a `application/vnd.dsse.envelope.v1+json` blob would have something like the following manifest:

```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "artifactType": "application/vnd.dsse.envelope.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.empty.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.dsse.envelope.v1+json",
      "size": 8216,
      "digest": "sha256:90e4d184b4a6635ec6f3b88e244de0b7fe0a078569bbec710ea9109db29d8712",
      "annotations": {
        "dev.cosignproject.cosign/signature": "...",
        "dev.sigstore.cosign/bundle": "...",
        "dev.sigstore.cosign/certificate": "....",
        "dev.sigstore.cosign/chain": "....",
        "predicateType": "http://example.mytype" 
      }
    }
  ]
}
```

You'll likely want to feature gate this behind the oci-1-1 options in cosign since we haven't GA'd this yet. The one registry that I know you'll want to work with is GitLab who has an allow list on their config mediaType and may do the same for the artifactType.

**Comment by chaospuppy** [comment]
So sounds like you're on the money @lcarva, we will still need to set the annotation if we wish to identify which layer contains the desired predicate type, even after reference types are introduced.

**Comment by sudo-bmitch** [comment]
Assuming you only have a single layer, you would want to define any annotations useful for filtering on the manifest itself, rather than the layer. Annotations on the manifest are pulled up in the referrers response, allowing you to pick the dsse envelope artifact from a list of artifacts all created for the same image.

This is a bit different from the current cosign design where there's one attestation manifest with multiple layers. The goal of the OCI design is to make it easier to add and remove entries, especially when the registry is managing the referrers response.
