### ISSUE TITLE
The installation instructions appear to have some requirements missing

### ISSUE THREAD

**Issue by thebsdbox** [sigstore/cosign#304]
**Description**

I followed the instructions on the `README.md` unfortunately they resulted in an error:

```
dan@code:~$ go version
go version go1.16.3 linux/amd64
dan@code:~$ go install github.com/sigstore/cosign/cmd/cosign@latest
# pkg-config --cflags  -- libpcsclite
pkg-config: exec: "pkg-config": executable file not found in $PATH
```

**Comment by dlorenc** [comment]
Ref #305 as well - we should public static binaries for Linux that don't support yubikeys too.

**Comment by thebsdbox** [comment]
Awesome.. I finally had a few minutes to start playing with `cosign` against raw OS images in registries so just hit a few things :-) thanks for the quick response!
