### ISSUE TITLE
Is it supported to generate Cosign key pair without input password

### ISSUE THREAD

**Issue by LiZhang19817** [sigstore/cosign#3065]
**Question**
Now when use "cosign generate-key-pair" to generate Cosign Key pair,  must input a password, is it possible to disable encrypt the private key?

**Comment by xukey** [comment]
export COSIGN_PASSWORD="your password"
then generate key pair

**Comment by znewman01** [comment]
You can also hit enter to set an empty password.

Does that or the `$COSIGN_PASSWORD` approach work for you?
