### ISSUE TITLE
Document (and test) `cosign version` output

### ISSUE THREAD

**Issue by znewman01** [sigstore/cosign#3088]
H/t to @vEpiphyte who observes (on Slack):

> 2.1.0 changed to have cosign version output print to stdout instead of stderr. The change happened in this commit:
https://github.com/sigstore/cosign/commit/40dbbd8b09bd5c30191d6e7e7ced3bbd7f6ea559
> Which may come from this https://github.com/kubernetes-sigs/release-utils/compare/v0.7.3...v0.7.4
> specifically here
> https://github.com/kubernetes-sigs/release-utils/pull/76

Thanks for the detective work!

It would be useful for scripts to be able to rely on this information. 
Per our [versioning policy](https://github.com/sigstore/cosign/blob/main/VERSIONING.md#whats-covered), for that to happen we need to:

1. Document the expected STDOUT output of `cosign version`.
2. Add a test that checks the output and that it's sent to the right stream.

(For a bonus, we could add a `cosign version --format=json` flag that output this information in a machine-friendly way.)

**Comment by vEpiphyte** [comment]
Thanks filing this!

**Comment by LewisThomas** [comment]
I'd like to try to tackle this to dip my feet into cosign codebase and Go

**Comment by znewman01** [comment]
Nice! This should be a good introduction to the codebase. ~If~ when something is underdocumented and confusing, reach out here and we'll see if we can help.

**Comment by AppleGamer22** [comment]
Since this issue has been quiet for a couple of months, I'd be happy to jump into this issue and suggest documentation updates and commits to the version printing subcommand. Would this be appropriate given this issue is already assigned?

**Comment by haydentherapper** [comment]
Done, assigned @AppleGamer22

**Comment by AppleGamer22** [comment]
I started a new branch for this issue on [my fork](https://github.com/AppleGamer22/cosign/blob/version-tests-and-json-fmt/doc/cosign_version.md), which at the moment contains the documentation update. I'll open the PR once I get the testing code in shape. I'm happy to open it sooner if this is required.
