### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by smythp** [sigstore/cosign#3092]
I've noticed that `cosign --version` returns an unknown flag error. I know that `cosign version` is the canonical way to get version info, but a `--version` flag is fairly common with command line tools, and was the first thing I tried to make sure the installation was successful when I installed for the first time.

```
$ cosign --version
Error: unknown flag: --version
main.go:74: error during command execution: unknown flag: --version
```

At least some other tools in the Sigstore family, like Gitsign, do support a `--version` flag. If not adding the flag is not a deliberate design decision, it might make sense to support it.

This issue was created in connection with friction log https://github.com/sigstore/docs/issues/184

**Comment by cpanato** [comment]
you should use `cosign version`

**Comment by hectorj2f** [comment]
Yes, I agree with @cpanato.

**Comment by ChristianCiach** [comment]
I also think that `version` should be a command, not a parameter, so there is no need to change something here. Otherwise you would have to think about what to do if a user executes `cosign sign --version`, which seems strange. 

Notably, most of the kubernetes-related tool that I've checked (kubectl, kustomize, ...) also don't have a `--version` parameter.

**Comment by smythp** [comment]
I do think this probably isn't a feature that's going to make or break the experience of the tool on the command line, but as a counterpoint, here is a list of tools I happen to have installed that do implement the `--version` flag:

- npm
- jekyll
- node
- gcc
- make
- git
- python
- conda
- ruby
- sqlite3
- java
- code (VS code)
- google-chrome
- zsh
- gitsign

All GNU tools seem to include this flag, I include only gcc to avoid redundency.
