### ISSUE TITLE
Allow specifying an insecure repo for sign/verify 

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/cosign#311]
We'd have to do this if we wanted to run the tests that require a registry for tekton chains

Ref:  https://github.com/tektoncd/chains/pull/70

**Comment by loosebazooka** [comment]
I can look at this

**Comment by jonjohnsonjr** [comment]
Why does it have to be insecure?

**Comment by loosebazooka** [comment]
I think I might want to try to get the test infrastructure to bring up a "trusted" registry to see if that can work?

**Comment by priyawadhwa** [comment]
Yah so basically the Chains integration tests run on a GKE cluster but don't have credentials for GCR, so I set up an insecure registry in-cluster that we could push signatures to. We'd basically need this feature to be able to run `cosign verify` as a Task as the last step of the integration test.

Right now we get around needing this by port-forwarding the registry to a local port and using that for verification (instead of verifying in-cluster), and it seems to be working fine (although the port forwarding is pretty flaky). tbh since the port forwarding is a passable solution idk how necessary this is anymore.

**Comment by jonjohnsonjr** [comment]
I'd suggest having a self-signed cert for the registry and getting cosign to trust it via `SSL_CERT_FILE` or something.

**Comment by dlorenc** [comment]
Isn't this what crane has this for: https://github.com/google/go-containerregistry/blob/7e30746dde2f5a19b609f885dfef4e7b1d1503ad/pkg/name/registry.go#L35 ?

**Comment by jonjohnsonjr** [comment]
Yes, and it's lazy, and you shouldn't propagate it.
