### ISSUE TITLE
Add GitHub Action for e2e test for cosign attach

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#3111]
**Description**

https://github.com/sigstore/cosign/blob/main/test/e2e_test_attach.sh was added, but never called in a workflow.

**Comment by s1ntaxe770r** [comment]
hey @haydentherapper. 

I'd like to work on this isuuse. My current understanding is that I would need to add another step in the workflow run similar to what is happening [here](https://github.com/sigstore/cosign/blob/731adeb0ad7ce08e86f38417e7f70833db1bee15/.github/workflows/e2e-tests.yml#L50) but for the e2e test?

**Comment by haydentherapper** [comment]
Correct!
