### ISSUE TITLE
Artifacts are non-deterministic

### ISSUE THREAD

**Issue by jonjohnsonjr** [sigstore/cosign#3120]
**Description**

This effectively reverts https://github.com/sigstore/cosign/pull/2108

Determinism is a feature, not a bug. Libraries should not depend on external, global, mutable state (`time.Now()`).

Once this is fixed, I will reopen https://github.com/sigstore/cosign/issues/522, and (if someone wants) they can plumb an option through that sets the time.

**Version**

Since https://github.com/sigstore/cosign/issues/522

**Comment by Akaame** [comment]
It seems there were arguments regarding

- The importance of reproducibility (@dlorenc @dekkagaijin)
- Some providers using timestamps to perform housekeeping, thus not depending on `time.Now()` biting you in the back (again @dekkagaijin @imjasonh)
