### ISSUE TITLE
Sign with cosign and verify with docker trust.

### ISSUE THREAD

**Issue by chainhead** [sigstore/cosign#3129]
> I am new to container signing. 

Here is what I experimented.

1. Followed instructions from [the GitHub Action for `cosign`](https://github.com/marketplace/actions/cosign-installer) to sign container images using OIDC token. This works. Next steps in my GH Action publishes the image to GHCR.
2. Did `docker pull` against the signed image.
3. Ran `docker trust inspect` against the signed image.
4. Empty array results - see below.

```bash
[]
No signatures or cannot access ghcr.io/nsubrahm/image:tag
```
The "cannot access" part is not right since, `docker pull` went through.

My questions:

1. Signing the container image with `cosign` and verifying the same with `docker trust inspect` - is this supposed to work? 
2. If not, should images signed by `cosign` be verified by `cosign` only?
3. Out of curiosity, would the other way around work too? For example, `docker trust sign` followed by `cosign verify`.
4. My goal is to launch my application via `docker compose up -d` with signed container images _only_. Can you advise a strategy for the same, please? Or, point me to resources?

**Comment by haydentherapper** [comment]
From what I understand, `docker trust` is built on top of Notary, which is another project in the container signing space. Check out https://dlorenc.medium.com/notary-v2-and-cosign-b816658f044d for a comparison of the two. `docker trust` would not be compatible with Sigstore signatures.

Deployment-time verification policies are not in scope for Cosign. I would check out https://github.com/sigstore/policy-controller for an approach to that.

**Comment by chainhead** [comment]
> `docker trust` would not be compatible with Sigstore signatures.

Thank you for the clear answer.

`sigstore/policy-controller` sounds hopeful; but, I wanted a solution for Docker Compose. I will look around.
