### ISSUE TITLE
Failed to create a key pair

### ISSUE THREAD

**Issue by openstack-test** [sigstore/cosign#3137]
$ cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v2.1.1
GitCommit:     baf97ccb4926ed09c8f204b537dc0ee77b60d043
GitTreeState:  clean
BuildDate:     2023-06-27T06:57:11Z
GoVersion:     go1.20.5
Compiler:      gc
Platform:      linux/amd64

$ cosign generate-key-pair k8s://cosign/cosign-secret
Enter password for private key: 
Enter password for private key again: 
Error: new for config: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
main.go:74: error during command execution: new for config: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

$ kubectl  get ns |grep cosign
cosign            Active   23m

other version：
- aws eks v1.24
- kubectl v1.23.6

I need some help. Thanks

**Comment by haydentherapper** [comment]
If you're still running into issues, I would recommend asking on #cosign in Slack.
