### ISSUE TITLE
CI jobs: validate-release-job failing with 'no space left on device'

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#3149]
**Description**

It seems we are now facing a new problem with one of our CI jobs `validate-release-job` throwing errors caused by a lack of space on the device. 

When I run `df -h` on the runner, I got the following results:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          84G   71G   14G  85% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/root        84G   71G   14G  85% /__t
tmpfs           1.4G  1.2M  1.4G   1% /run/docker.sock
tmpfs           3.4G     0  3.4G   0% /proc/acpi
tmpfs           3.4G     0  3.4G   0% /proc/scsi
tmpfs           3.4G     0  3.4G   0% /sys/firmware
```

**Version**

`main`

**Comment by hectorj2f** [comment]
I can see once goreleaser runs it fills up the whole overlay available space 😱 1

```
**overlay          84G   83G  737M 100% /**
tmpfs            [6](https://github.com/sigstore/cosign/actions/runs/5726129049/job/15515969205?pr=3150#step:7:7)4M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/root        84G   83G  [7](https://github.com/sigstore/cosign/actions/runs/5726129049/job/15515969205?pr=3150#step:7:8)37M 100% /__w
tmpfs           1.4G  1.2M  1.4G   1% /run/docker.sock
tmpfs           3.4G     0  3.4G   0% /proc/acpi
tmpfs           3.4G     0  3.4G   0% /proc/scsi
tmpfs           3.4G     0  3.4G   0% /sys/firmware
```

**Comment by hectorj2f** [comment]
It seems to only happen when building `windows_amd64_v1`.

**Comment by hectorj2f** [comment]
It works now! It seems as once we managed to successfully execute the job by changing some build settings, things got cleanup at a runner level.

**Comment by hectorj2f** [comment]
@haydentherapper I'm gonna remove the execution of the validate release ci job for every PR. 

I tried to only build a single binary (linux/arm64) but the rest of our building scripts use `--platform=all` which will require many more changes. After all this script only checks that the build of the amd64 binary was successful. So I propose to only running for the `release-` branches. Perhaps @cpanato has other ideas to solve the problem.

**Comment by haydentherapper** [comment]
Another idea (thanks @bobcallaway) would be to delete the container before running `validate-release-job`.

If not that, then I think trying to build only a subset of our binaries like you suggested would be a good idea.

**Comment by pwelch** [comment]
@bobcallaway found this example of clearing out packages from the base runners that arent needed for a Go project: https://github.com/GoogleContainerTools/distroless/blob/5f4db907b8106a9ef00e015af15e84f80e8d7c9a/.github/workflows/ci.yaml#L27

(TIL the 14GB includes the base image data)

**Comment by hectorj2f** [comment]
Closing this as solved by https://github.com/sigstore/cosign/pull/3169!
