### ISSUE TITLE
Use TUF mirror to distribute long lived keys

### ISSUE THREAD

**Issue by lcarva** [sigstore/cosign#3155]
**Description**

I would like to use a TUF mirror to distribute the (long-lived) public signing key used in the `cosign verify*` commands, and have cosign use the public key directly from the TUF root. I imagine some sort of syntax like this:
```
cosign verify --key <tuf-root-target>
```

Ideally, there is an option to provide multiple public keys in the TUF root. This would more easily allow a standard key rotation procedure. cosign would then try each key.

Considerations:

1. Should the public key be available on its own TUF root?

**Comment by haydentherapper** [comment]
I'm not sure this should live in Cosign, though I'm happy to be convinced otherwise. I think Cosign, and other sigstore clients, should simply take in a verification key and it's up to the verifier to load it from a secured source. https://github.com/sigstore/cosign/issues/2908 is a similar issue.

**Comment by haydentherapper** [comment]
Closing out, this is not something on our roadmap, but feel free to propose a change if it's something you need.
