### ISSUE TITLE
i can't sign my images with cosign-harbor

### ISSUE THREAD

**Issue by NH1ATT** [sigstore/cosign#3163]
cosign sign --key cosign.key harbor.domain.com/library/nginx@sha256:7..........................................;
Enter password for private key: ....
Error: signing [harbor.domain.com/library/nginx@sha256:7...........................]: accessing image: GET https://harbor.domain.com/v2/library/nginx/manifests/sha256:7.........7: PROJECTPOLICYVIOLATION: The image is not signed in Cosign.
main.go:74: error during command execution: signing [harbor.domain.com/library/nginx@sha256:7...........]: accessing image: GET https://harbor.domain.com/v2/library/nginx/manifests/sha256:.............: PROJECTPOLICYVIOLATION: The image is not signed in Cosign.

**Comment by haydentherapper** [comment]
This error message is not generated by Cosign, but by https://github.com/goharbor/harbor. I would reach out to them.
