### ISSUE TITLE
i can't sign my images 

### ISSUE THREAD

**Issue by NH1ATT** [sigstore/cosign#3173]
cosign sign --key cosign.key cosign docker.io/...../nginx:latest
WARNING: Image reference cosign uses a tag, not a digest, to identify the image to sign.
    This can lead you to sign a different image than the intended one. Please use a
    digest (example.com/ubuntu@sha256:abc123...) rather than tag
    (example.com/ubuntu:latest) for the input to cosign. The ability to refer to
    images by tag will be removed in a future release.

Error: signing [cosign docker.io/...../nginx:latest]: accessing entity: GET https://index.docker.io/v2/library/cosign/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/cosign Type:repository]]
main.go:74: error during command execution: signing [cosign docker.io/....../nginx:latest]: accessing entity: GET https://index.docker.io/v2/library/cosign/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/cosign Type:repository]]

**Comment by falcorocks** [comment]
same here

**Comment by tosone** [comment]
`cosign sign` will upload the sig result to the registry, but you have no permission to this namespace. @NH1ATT 
@falcorocks the same to you.

`cosign sign --upload=false --output-signature=xx.sig docker.io/library/nginx:latest`

Again: `docker.io/library/nginx:latest` replace with `docker.io/library/nginx@sha256:b355b79a3117c4bfa2e8a05d5ed0496a19e542444d5ccf0328632091238a0136`.
