### ISSUE TITLE
Ability to retrieve digest from image

### ISSUE THREAD

**Issue by garethahealy** [sigstore/cosign#3251]
Cosign wants to work against digests and warns users if they use a tag, but I haven't seen any command that returns that information. I know you can use skopeo/crane/docker to retrieve the digest but when running the `cosign` image via CI, that means needing to include extra tooling. It would be nice if I could just grab it from `cosign`.

Which is possible, but requires a bit of `sed`. Currently, I do it via:

```
cosign triangulate quay.io/garethahealy/image-name:latest | sed 's/^.*sha256-//;s/.sig//'
```

I've pushed a commit to my fork showing how I think it could work:
- https://github.com/sigstore/cosign/compare/main...garethahealy:cosign:main

**Comment by garethahealy** [comment]
Same issue: https://github.com/sigstore/cosign/issues/3034

**Comment by haydentherapper** [comment]
Closing as duplicate

**Comment by garethahealy** [comment]
@haydentherapper ; i've not seen an update on the other issue, and since this was closed with a "not planned", can you explain why you wouldn't want to accept the contribution I've proposed?

**Comment by haydentherapper** [comment]
Sorry, the duplicate button shows the issue as not planned. Feel free to submit a pr!
