### ISSUE TITLE
Improve `dockerfile verify`

### ISSUE THREAD

**Issue by BobyMCbobs** [sigstore/cosign#3260]
**Description**

The command `cosign dockerfile verify ./Dockerfile` works great if a Dockerfile contains literal image names but not for anything else.

I'd like the two following methods to be supported
1. resolve from variable
```
ARG IMAGE=myimage:mytag
FROM $IMAGE
```
(ARG or ENV)

2. image in COPY
```
COPY --from=myimage:mytag /etc/passwd /etc/passwd
```

/assign

**Comment by EraKin575** [comment]
I would like to work on this issue

**Comment by BobyMCbobs** [comment]
@EraKin575, I've already assigned myself to this and am working on it.
