### ISSUE TITLE
Support Enterprise vault namespaces

### ISSUE THREAD

**Issue by Dinnerspy** [sigstore/cosign#3308]
**Description**

I'm looking to integrate Cosgin with my enterprise vault as its kms however I noticed it seems to be configured to only work with the root namespace. In my environment variable I set up the standard VAULT_NAMESPACE and cosgin does not seem to be picking it up. I double checked this as it is returning the following paths with error from the root namespace. 
 
https://vault-hostname.com/v1/transit/keys/keyname 

when it should be: 

[https://vault-hostname.com/v1/namespace_name/transit/keys/keyname](https://vault-hostname.com/v1/names[pace/transit/keys/keyname)

It should be a simple change to check for that envirment variable and if it is not there then use the default path. 

https://developer.hashicorp.com/vault/docs/enterprise/namespaces

**Comment by Dinnerspy** [comment]
After doing more digging it seems the change needs to be done in the sigstore repo. Closing this and opening a new issue in that repo.

**Comment by fletort** [comment]
Hello, i have the same problem. I think it is a internal feature that should be added inside the cosign cli, no ?
