### ISSUE TITLE
Cosign keyless image signing with Azure

### ISSUE THREAD

**Issue by andriktr** [sigstore/cosign#3340]
Hi, 
I'm looking for some guidance on how to implement cosign keyless image signing solution using Azure DevOps pipelines as CI/CD solution, Azure ACR as private container registry, Azure key vault as a key store and Azure AD as OIDC issuer.
Also as far as I understand Fulcio and Rekor are also important parts of the keyless image signing flow and can be deployed as private instances. 
What about verification process on k8s side how to make sure that only valid signed images are deployable to the cluster.  
Maybe someone already has something similar implemented in their environment and can share their insights and experience. 

Thank you in advance.

**Comment by haydentherapper** [comment]
Hi, please ask this question on Sigstore's Slack.
