### ISSUE TITLE
Signing with tlog upload is not idempotent

### ISSUE THREAD

**Issue by reedloden** [sigstore/cosign#3356]
**Description**

We sign our images during the final stage of our release. However, because of the sheer amount of things that happen in that "promotion" stage, it is sometimes necessary to re-run it. cosign 1.x didn't have an issue with this, as signatures were not uploaded automatically to the transparency log. However, with cosign 2.x, we're running into an issue due to a signature already existing:

$ `cosign sign --yes --key awskms:///... --recursive public.ecr.aws/foo/bar@sha256:abcdef...`

...
> Signature already exists. Displaying proof
> Error: signing [public.ecr.aws/foo/bar@sha256:abcdef...]: recursively signing: signing digest: unexpected entry returned from rekor server: expected EntryUUID 24296fb24b8ad77aa8f736fc36ff0184b30419c0347d81b22f5d3328592015e2369a8f71bc741bac got UUID 24296fb24b8ad77aa8f736fc36ff0184b30419c0347d81b22f5d3328592015e2369a8f71bc741bac from Tree c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d
> main.go:74: error during command execution: signing [public.ecr.aws/foo/bar@sha256:abcdef...]: recursively signing: signing digest: unexpected entry returned from rekor server: expected EntryUUID 24296fb24b8ad77aa8f736fc36ff0184b30419c0347d81b22f5d3328592015e2369a8f71bc741bac got UUID 24296fb24b8ad77aa8f736fc36ff0184b30419c0347d81b22f5d3328592015e2369a8f71bc741bac from Tree c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d

https://github.com/sigstore/cosign/blob/aaa354d0dfe2ed315d85ca3737cdbb34fe02b95a/pkg/cosign/tlog.go#L207-L224 makes it seem like signing an image multiple times is fine (and it's what I would expect).

**Version**

cosign 2.2.1

**Comment by haydentherapper** [comment]
Lemme dig in, this is definitely a bug.

**Comment by haydentherapper** [comment]
@reedloden Fixed in https://github.com/sigstore/cosign/pull/3371
