### ISSUE TITLE
Dependency license compatibility

### ISSUE THREAD

**Issue by binbin-li** [sigstore/cosign#3377]
**Question**
Hi Ratify is adding [skywalking-eyes](https://github.com/apache/skywalking-eyes) as license checker to its pipeline. And it turns out there are 2 libraries are under incompatible license:
github.com/alibabacloud-go/cr-20160607@v1.0.1
github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475

cr-20160607@v1.0.1 is missing a license but v2 added Apache 2.0 license.
go-metrics is under license `BSD-2-Clause-Views` which is not compatible with Apache 2.0 as mentioned in https://www.apache.org/legal/resolved.html#category-a

It's not a blocking issue, just wonder if you have plan to address the license incompatibility.

**Comment by haydentherapper** [comment]
These are indirect dependencies, please raise this issue with each of these libraries.
