### ISSUE TITLE
Add feature to allow for signing and attestations (attest-blob/sign-blob) against remote blobs/artifacts

### ISSUE THREAD

**Issue by aalsabag** [sigstore/cosign#3380]
**Description**

The ability to sign and attest blobs is a great feature as it allows us to work with objects that are not container images. I would like to be able to sign and attest against remote artifacts that are stored in an artifact repository.

I have a PR raised that addresses this by simply checking to see if the artifactPath passed in through the cli is a uri.

**Comment by haydentherapper** [comment]
Thanks for the suggestion. Would using `curl` or `wget` to download the artifact before signing be sufficient?

**Comment by haydentherapper** [comment]
I'm going to close this out, as piping the results of a curl or wget should be sufficient. Let me know if you have another use-case in mind.

**Comment by aalsabag** [comment]
I'll let you know if I think of something. For now I think downloading the blob beforehand would be sufficient.
