### ISSUE TITLE
understand intended usage of cosign verify --offline flag

### ISSUE THREAD

**Issue by federico-falconieri-form3** [sigstore/cosign#3423]
**Question**

I've signed a container image with the keyless flow, using my own PKI. I'm struggling to understand what is the purpose of the `--offline` flag.
The --help says
```
cosign verify --help | grep offline                                                        
    --offline=false:
        only allow offline verification
```

I want to be able to verify the signature both offline and online, which as far as I understand means:
* **offline**: at signing time, rekor provides a _promise_ of inclusion in the transparency log. This promise is made available in the final signature which gets stored in the OCI registry.  When I run `cosign verify --offline=true ...` I expect that cosign to believe the promise of inclusion but does not verify it. Of course I expect cosign to verify the integrity of the signature. I understand that the point of this is 1) allow offline verification in airgapped environments 2) allow to spare the load on rekor
* **online**: when I run `cosign verify --offline=false ...` I expect cosign to actually verify that inclusion promise by checking rekor. The point of this is that it's more secure. Trust but verify!

However, the offline flag does not seem to make any difference. Cosign says verification is _always_ peformed offline

```
cosign verify XXX --rekor-url=$REKOR_URL --offline=false --certificate-identity=$CERT_IDENTITY --certificate-oidc-issuer=$CERT_OIDC_ISSUER

Verification for XXX --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline # <--- offline!
  - The code-signing certificate was verified using trusted certificate authority certificates
```

So now I'm left wandering:
1. does the `--offline` flag mean what I mentioned above?
2. if so, is this a bug with `--offline` flag, or maybe with the message in the output of `cosign verify`?
3. as I understand currently, the only way to proof inclusion is to actually query rekor with `rekor-cli get --log-index` and then do some `jq` gymnastic to check that content of rekor entry and signature in OCI registry actually match. Is this correct?

**Comment by haydentherapper** [comment]
The bug is in the output message, that's a static message so it doesn't always reflect how verification occurs.

The purpose of the `offline` flag is to prevent falling back to querying Rekor in the event that the provided SignedEntryTimestamp does not verify successfully. If you're in an airgapped environment or simply don't want to query the log during verification, this flag is needed.

Long term, we'd like to remove this flag and expect that verification is always offline with an _inclusion proof_ (which we currently don't persist alongside the _promise_, but will soon).

**Comment by federico-falconieri-form3** [comment]
wonderful @haydentherapper , thank you for taking the time to explain this to me :) So with `--offline=false` rekor is queried. That's great because then we don't need to actually verify inclusion in the log with `rekor-cli`... which is a bit clunky because it requires me to jq the logID from the signature... I leave it to you if you wan to close the issue or maybe relabel it as a bug

**Comment by haydentherapper** [comment]
We should be tracking output message improvements elsewhere. Thanks!
