### ISSUE TITLE
Adding Extension/Custom Fields to slsaprovenance1 Type Not Reflecting in Attested Predicate Data

### ISSUE THREAD

**Issue by SaiJyothiGudibandi** [sigstore/cosign#3433]
I am encountering an issue while attempting to add custom extension fields to the SLSAProvenance1 predicate type, specifically aiming to include a provenance data. Despite following the guidance provided in the documentation her (https://slsa.dev/spec/v1.0/provenance#extension-fields) and experimenting with various methods to incorporate these fields into the data, the changes are not appearing in the attested predicate data.

Is there a specific way or workaround available that would allow for the successful integration of custom fields into the slsaprovenance1 predicate type? 

Any insights or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by viveksahu26** [comment]
Hey @SaiJyothiGudibandi, need small help. I am trying to reproduce this issue but before that I am bit unclear about issue whether it is related to cosign or SLSA.  Could you please elaborate how cosign couldn't help here, what particular use case of cosign were you looking to implement and that doesn't works for you??  Would be a great help to proceed with this issue.

**Comment by haydentherapper** [comment]
Without more details, I'm not sure if this is an issue in Cosign or SLSA. This sounds like an issue with the underlying slsa library or the predicate you're provided is not compatible with slsa v1. Feel free to reopen if you have more details.
