### ISSUE TITLE
`cosign verify` does not honor --rekor-url

### ISSUE THREAD

**Issue by adrielldagasuan** [sigstore/cosign#3436]
**Description**

Summary:
I'm testing a local setup for signing docker images using a local rekor server, a local docker registry, and cosign generated keys but when verifying, it seems to not use the local rekor server as the transaction log.

Setup:
- local rekor-server, using [this docker-compose file](https://github.com/sigstore/rekor/blob/326a677eb44d2078d944834ba2899b2aff4d9ec2/docker-compose.yml).
- local docker registry using the [official image](https://hub.docker.com/_/registry).
- cosign version 2.2.1

NOTE: Code and log blocks below are snippets, containing only the relevant information to the suspected bug.

Actions:
1. Generate key pair using: `cosign generate-key-pair`
2. Push docker image to local registry: `docker push localhost:5000/image:tag`
3. Sign image using private key:
```
cosign sign --key cosign.key -y --rekor-url=http://localhost:3000 localhost:5000/image:tag
tlog entry created with index: 0
Pushing signature to: localhost:5000/image
```

4. Verify that there's a log entry in the local rekor server:
```
curl http://localhost:3000/api/v1/log/entries?logIndex=0
```
5. Verify image using public key
```
cosign verify --key cosign.pub --rekor-url=http://localhost:3000 localhost:5000/image:tag
```
When verifying, it outputs the following error message:
```
Error: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
main.go:69: error during command execution: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
```

So this was frustrating because even adding `--verbose`, it only adds debug information when getting data from the docker registry but not when connecting to the rekor server.

Anyways, I did additional tests and tried using the public rekor server.
```
cosign sign --key cosign.key localhost:5000/image:tag
tlog entry created with index: 56860445
Pushing signature to: localhost:5000/image
```
This created a tlog entry with index in the thousands (which makes sense because it's the public server). And verifying works.
```
cosign verify --key cosign.pub localhost:5000/image:tag

Verification for localhost:5000/image:tag --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
```

But when trying to verify again but this time using the local server (`--rekor-url=http://localhost:3000`), verification passed but I noticed that it was using the public rekor server because the response used a logindex that was for the public server. Other things I noticed. When passing in a nonexistent address for the rekor URL (ie `--rekor-url=http://nonexistent:1234` for `cosign sign`, there is an error saying that it can't connect to the server. But for `cosign verify`, there are no errors. This led me to believe that perhaps the `--rekor-url` config is not being used during verification or something else is happening under the hood.

`cosign sign` pointing to a nonexistent server address (expecting connection errors)
```
❯ cosign sign --key cosign.key --rekor-url=httpasdf://localhost:3000 localhost:5000/image:tag
Error: signing [localhost:5000/image:tag]: recursively signing: signing digest: Post "httpasdf://localhost:3000/api/v1/log/entries": POST httpasdf://localhost:3000/api/v1/log/entries giving up after 1 attempt(s): Post "httpasdf://localhost:3000/api/v1/log/entries": unsupported protocol scheme "httpasdf"
main.go:74: error during command execution: signing [localhost:5000/image:tag]: recursively signing: signing digest: Post "httpasdf://localhost:3000/api/v1/log/entries": POST httpasdf://localhost:3000/api/v1/log/entries giving up after 1 attempt(s): Post "httpasdf://localhost:3000/api/v1/log/entries": unsupported protocol scheme "httpasdf"
```

`cosign verify` pointing to a nonexistent server address (expecting connection errors but none raised)
```
❯ cosign verify --key cosign.pub --rekor-url=httpasdf://localhost:3000 localhost:5000/image:tag
Error: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
main.go:69: error during command execution: no matching signatures: error verifying bundle: verifying bundle: rekor log public key not found for payload
 error verifying bundle: verifying bundle: rekor log public key not found for payload
```

Is this a bug for the `verify` command or am I doing something wrong when verification?

**Version**
Installed using `homebrew`
```
❯ cosign version

GitVersion:    2.2.1
GitCommit:     12cbf9ea177d22bbf5cf028bcb4712b5f174ebc6
GitTreeState:  "clean"
BuildDate:     2023-11-07T12:39:46Z
GoVersion:     go1.21.3
Compiler:      gc
Platform:      darwin/arm64
```

**Comment by viveksahu26** [comment]
Hey @adrielldagasuan, if you use the `--insecure-ignore-tlog=true` flag, it means you're telling cosign to use a local Rekor server that's not secure (using http). Cosign will automatically(or implicity) recognize this insecure local server, so you don't have to specifically(or explicity) mention the Rekor URL for insecure connections.

The command will be like:
```
cosign verify --key cosign.pub --insecure-ignore-tlog=true  localhost:5000/image:tag│ | jq 
```

**Comment by adrielldagasuan** [comment]
Ahh let me try this. Probably something I missed in the docs. I have used the `--insecure-ignore-tlog=true` flag before but didn't for local URLs this has to be specified explicitly.

**Comment by adrielldagasuan** [comment]
@viveksahu26 I don't see `--insecure-ignore-tlog` as a valid flag in my version of `cosign`. Is it the same as `--tlog-upload=false`?

**Comment by haydentherapper** [comment]
Hey, sorry for the delayed response. What you're running into is not that the rekor-url flag is being ignored, it's that Cosign can't find a public key to verify Rekor responses. See [this section of code](https://github.com/sigstore/cosign/blob/402820d97997f3a29f06b99c6fc7b7d78067ce62/pkg/cosign/verify.go#L1068-L1073) if you're interested.

Cosign is preconfigured to trust our public root of trust, which is distributed through [The Update Framework](https://theupdateframework.io/). If you want to use a private instance of Rekor or Fulcio, you need to also configure Cosign with the public key of the log or the root certificate of the CA respectively. Given you're just using keys, I'll just note how to do this for the log. 

You either need to set up your own TUF repository, and configure Cosign to use it with `cosign initialize` ([blog post](https://blog.sigstore.dev/sigstore-bring-your-own-stuf-with-tuf-40febfd2badd/) which contains some details on how to), or you can set `SIGSTORE_REKOR_PUBLIC_KEY` to the file path with the log's key, which you can access with `curl localhost:3000/api/v1/log/publicKey`

**Comment by adrielldagasuan** [comment]
Ahhhh. Thanks for this @haydentherapper ! Now I understood. I thought it was that the public key (used to sign the image) wasn't found in the manifest or something. Never thought it was the public key of the tlog. Setting the env variable worked!
