### ISSUE TITLE
How to use OtherName SAN attribute

### ISSUE THREAD

**Issue by jmpolom** [sigstore/cosign#3465]
**Question**

How do you use the [OtherName SAN](https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md#1361415726417--othername-san) attribute referenced in the Fulcio docs from `cosign sign`? Is this possible? Seems like it is not.

**Comment by haydentherapper** [comment]
First time someone's asked about this! For context, I added support for OtherName SANs a bit ago to support [usernames in Fulcio](https://github.com/sigstore/fulcio/blob/df01ed80f075e585dbd617d175fb029c2b9f8165/docs/oidc.md?plain=1#L270-L284).  For Fulcio-issued certificates, the OtherName SAN contents will be `sub!SubjectDomain` (`!` was chosen as the separator to not confuse this with a valid email address).

It depends how you've configured your Fulcio instance (assuming you're running a local instance, the public instance isn't configured to issue username-bound certs at the moment). `cosign sign` will issue a certificate with the OtherName SAN if you've added a `username` type to Fulcio's configuration. `cosign verify` will extract the OtherName SAN username during verification ([code](https://github.com/sigstore/cosign/blob/e678426b3d524f15cab553e57eb6900f8280fb62/pkg/cosign/verify.go#L303)).

Does that answer your question?

**Comment by jmpolom** [comment]
Mostly yes and a little no. It sounds like I cannot use this at this time as I'm using the public Fulcio instance and not running my own private instance.

> It depends how you've configured your Fulcio instance (assuming you're running a local instance, the public instance isn't configured to issue username-bound certs at the moment).

Is there documentation describing the configuration options for Fulcio along these lines? I have looked and come up empty handed.

**Comment by haydentherapper** [comment]
Correct, the public instance doesn't use this currently since no OIDC issuers that are trusted by the public instance specify usernames.

> Is there documentation describing the configuration options for Fulcio along these lines? I have looked and come up empty handed.

I couldn't find any docs around configuration of the OIDC issuer, only the signing backend. You would specify the "username" type in a json config like https://github.com/sigstore/fulcio/blob/main/config/config.jsn#L6, and specify a "SubjectDomain" (https://github.com/sigstore/fulcio/blob/b202f9cf2797ef30146c75fad86c1e564ba9514e/docs/oidc.md?plain=1#L280) that will be appended to the `sub` in the OIDC token.

**Comment by jmpolom** [comment]
> Correct, the public instance doesn't use this currently since no OIDC issuers that are trusted by the public instance specify usernames.

This is what I seemed to realize after looking into the GH OIDC workflow tokens a bit more. Definitely answers the rest of my question.

Well, good feature maybe it will be more readily useful one day :)
