### ISSUE TITLE
Support signing and verification with cosign keys stored in k8s secrets

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/cosign#347]
We can implement this once https://github.com/sigstore/cosign/pull/345 is merged

**Comment by developer-guy** [comment]
@priyawadhwa are you working on this, if not, we would like to implement this feature with my colleague @Dentrax, we have a cycle for that.

**Comment by dlorenc** [comment]
Go for it! Priya is on vacation for a bit.
