### ISSUE TITLE
Verifying signature of image in golang or java code

### ISSUE THREAD

**Issue by surendrababuravella** [sigstore/cosign#3503]
Hi Team,

We have a product which plays around docker images /oci artifacts. This product has implemented using GOLANG and JAVA. We have started using COSIGN to sign images externally. But currently we are directly processing those images in our product without doing any signature verification. Now we want to implement code to verify signature of every image before processing it.

SO can you please help whether there are any third party libraries which can help to code in GOLANG or JAVA to verify cosign signed image signatures?.. Please let us know if there are any examples documented...

Thanks..

**Comment by hectorj2f** [comment]
@surendrababuravella Have you had a look at sigstore/policy-controller?

**Comment by surendrababuravella** [comment]
Hi @hectorj2f,  Thank you for your quick response.

Our product is a standalone application written in JAVA/GOLANG. It doesn't need Kubernetes. Policy-controller won't be useful here.

We need to add signature validation capability as part of our product by implementing respective code in JAVA/GOLANG. Can you suggest on this please..

**Comment by haydentherapper** [comment]
You can use Cosign as an API, take a look at https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go. The Kyverno project has an example of that. We also have an example of verifying OCI images using our newer sigstore-go library: https://github.com/sigstore/sigstore-go/tree/main/examples/oci-image-verification

The sigstore-java (https://github.com/sigstore/sigstore-java) library does not support OCI images, though you could open an issue there if you wanted to contribute that feature.

**Comment by surendrababuravella** [comment]
Thank You @haydentherapper for your help ..
