### ISSUE TITLE
OSS security index card

### ISSUE THREAD

**Issue by viveksahu26** [sigstore/cosign#3511]
**Description**
Add [Open Source Security index](https://opensourcesecurityindex.io/) badge for cosign project. Basically every year Open Source Security published or releases a list of fastest growing open source security projects.  So, this badge is proof of that. 
Cosign is ranked 59th out of 100 projects. And it is categorized under `Application Security`.

Badge overview:
![image](https://github.com/sigstore/cosign/assets/65091408/26ec36a2-b581-478f-917b-35fc0fe208e0)

**Comment by haydentherapper** [comment]
Thanks for the proposal. I'm not sure the source of this data, so this badge doesn't seem particularly useful.
