### ISSUE TITLE
Cosign Keyless Signing using MS as the OIDC issues

### ISSUE THREAD

**Issue by alecrevangelista** [sigstore/cosign#3529]
**Question**

Hello,

I am interested in signing some JSON artifacts using **Keyless signing**, and was reading the documentation for it over here: https://docs.sigstore.dev/signing/overview/. As per the docs, there are two supported OAuth flows today: the **standard flow** and the **device flow**. 

I have already tried the device flow, and it works when I log in through my personal Google Account. The command I used was: `cosign sign-blob test.json --bundle cosign.bundle`. This opened up my browser window for me to log in, and then after logging in, the JSON was signed.

However I would like to do this automatically (programmatically) on a machine that has no window, so I would like to follow the standard flow. Reading the supported OIDC providers (MS, Google, GIthub), I am trying to do this via MS. Also reading the `cosign sign-blob` [docs](https://fig.io/manual/cosign/sign-blob), there seems to be an option to pass in the `--identity-token` flag. I am able to generate an ID token from MS, but the problem I am having with MS is that the `audiences` claim in the token must contain `sigstore`. There doesn't seem to be a way to customize the aud claim?

The setup i did was:

1. Login to my company's MS Azure
2. Navigate to Microsoft Entra ID
3. Create an Application
4. Ran this cmd to get the ID token:

```
curl -L "https://login.microsoftonline.com/<company_name>.onmicrosoft.com/oauth2/v2.0/token" \
-H "Content-Type: application/json" \
-H "Cookie: fpc=Al-***; stsservicecookie=***; x-ms-gateway-slice=***" \
-F "client_id=\"<clientId>\"" \
-F "scope=\"https://graph.microsoft.com/.default\"" \
-F "client_secret=\"<secret>\"" \
-F "grant_type=\"client_credentials\""
```

We are not super tied to MS if there is an easier way to achieve keyless signing through cosign programatically. 

Is there maybe a way to do something like this but for AWS? This is the example used in the [Cosign Overview Doc](https://docs.sigstore.dev/signing/overview/):

```
$ cosign sign --identity-token=$(
    gcloud auth print-identity-token \
        --audiences=sigstore \
        --include-email \
        --impersonate-service-account my-sa@my-project.iam.gserviceaccount.com) \
    gcr.io/user-vmtest2/demo
```

Any help would be much appreciated, 

Thanks

**Comment by viveksahu26** [comment]
What did you get on following Device flow method using MS account ?

**Comment by alecrevangelista** [comment]
I get the following:

![Screen Shot 2024-02-12 at 6 59 23 AM](https://github.com/sigstore/cosign/assets/42983560/6fc0c8e8-88bf-4735-8ea1-c4d29da2a220)

**Comment by haydentherapper** [comment]
Hey @alecrevangelista, it looks like our client secret expired for the Microsoft integration. We're taking a look now.

**Comment by thisiskarthikj** [comment]
@haydentherapper Thank you. Please let us know as soon as you get a chance to rotate the secrets. is "audiences claim in the token must contain sigstore" a requirment ? Because as @alecrevangelista  pointed out there is no way to do that currently in Microsoft AD / EntraID.

**Comment by haydentherapper** [comment]
Yes, the audience must contain "sigstore", that's a requirement of the OpenID Connect spec. I'm not familiar with Microsoft's login process, though I would assume there is some way to configure audience.

**Comment by bobcallaway** [comment]
this should be fixed now (secrets have been rotated and manually verified in both staging and production)

**Comment by alecrevangelista** [comment]
Thanks for updating the secrets, I am able to do the **Device flow method** using a MS account. However this is still manual and I would like to follow the **standard flow** because I want to perform signing automatically on some machine (i.e no one there to open the browser as with the device flow). Is there any guidance on how I should configure my MS Entra ID Application? Or how I can get started with MS in general?

Appreciate the help

**Comment by haydentherapper** [comment]
Cosign has "providers" (https://github.com/sigstore/cosign/tree/main/pkg/providers) that can pick up the identity token from various environment variables or files on disk. This can be used in automated CI environments. I'm not familiar with MS Entra though so I can't provide help there.

**Comment by vineetguptadev** [comment]
@haydentherapper  Is there any example I can refer to for github ? I use ECR to host my images and helm chart , but just now we started to see our pipeline failing. we simply used 
`cosign sign -y <image digest with git ref>`

For verification we used 
`cosign verify  --certificate-identity '${{ github.server_url }}/${{ github.repository }}/.github/workflows/main.yaml@${{ github.ref }}'  --certificate-oidc-issuer https://token.actions.githubusercontent.com ${{ secrets.COSIGN_AWS_REGISTRY }}/docker/test:$VERSION` .

We are now failing with 
```
Retrieving signed certificate...
Successfully verified SCT...
Error: signing [***/docker/test@]: parsing reference: could not parse reference: ***/docker/test@
main.go:74: error during command execution: signing [***/docker/test@]: parsing reference: could not parse reference: ***/docker/test@
```

Can I please get some insights ?
