### ISSUE TITLE
Fetch TSA certificates from TUF targets when available

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#3563]
**Description**

The sigstore/sigstore TUF client has been updated to support the ["TSA" usage type](https://github.com/sigstore/sigstore/blob/364b1acc28de3ea95178e82d0b365036d60c6eb1/pkg/tuf/usage_type.go#L29). We currently require the TSA cert chain to be [provided by flag](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify/verify_blob.go#L118-L141). We can also support reading the cert chain from either an environment or the TUF targets, to be more in line with how Fulcio certs or Rekor keys can be provided on verification. See [RekorPubKeys](https://github.com/sigstore/cosign/blob/main/pkg/cosign/tlog.go#L122) as an example for how to support this. Ideally we can refactor all places where we read in the TSA cert chain via flag into a single function that reads from either a flag, env var, or TUF.

Note that as described in https://github.com/sigstore/scaffolding/issues/1001, the usage type will be deprecated in the near future, but given the simplicity of adding this feature, it's worthwhile to do now.

**Comment by ianhundere** [comment]
@haydentherapper i opened a draft PR for this, didn't write a tsalog_test, but wanted to get this 👀 first.
