### ISSUE TITLE
Allow provisioning key-pair to a GitHub organisation's secrets

### ISSUE THREAD

**Issue by biehl1** [sigstore/cosign#3566]
Cosign generate-key-pair is able to provision secrets on a github project:
```
# generate a key-pair in GitHub
cosign generate-key-pair github://[OWNER]/[PROJECT_NAME]
```

It would be great if it was possible to generate such secrets at 'Owner' level (e.g. a GH organization):
```
cosign generate-key-pair github://[OWNER]
```

Relevant sources:
https://github.com/sigstore/cosign/blob/main/pkg/cosign/git/github/github.go

**Comment by cpanato** [comment]
that sounds great, i can do that

**Comment by biehl1** [comment]
Ok, that was fast one   :) thanks guys
