### ISSUE TITLE
"cosign verify-blob" or "cosign verify" with local certificate and chain always asks for oidc provider 

### ISSUE THREAD

**Issue by fernandokarnagi** [sigstore/cosign#3572]
**Description**
 When invoking "cosign verify-blob" or "cosign verify" with local certificate and chain, the cli always asks for cert identity and oidc provider.

```
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
```

Found the code here [certificate flag](https://github.com/sigstore/cosign/blob/7a2d50b08700dadb4842b0ea4538a6430087bb54/cmd/cosign/cli/options/certificate.go#L95)

Is it a bug?

**Version**
v2.2.3

**Comment by haydentherapper** [comment]
Working as intended, a certificate must contain an identity. If you are not using Fulcio, which issues identity certificates, you can extract the key with something like https://smallstep.com/docs/step-cli/reference/certificate/key/ and provide that instead.
