### ISSUE TITLE
Signature Verification

### ISSUE THREAD

**Issue by suryabaiarava** [sigstore/cosign#3585]
**Description**

am using azure key vault to manage keys and when i try to use AKV to sign and verify the container image/blob it is working as expected.
But when i try to download the public key locally and verify it is throwing below error Please assist me on this part.

**Syntax:**
$ cosign public-key --key <aks>://<key name> > kms.pub
$ cosign verify --key kms.pub gcr.io/user-vmtest2/demo

**Error:**
Error: crypto/rsa: verification error
main.go:74: error during command execution: crypto/rsa: verification error

**Version**

GitVersion:    v2.2.3
GitCommit:     493e6e29e2ac830aaf05ec210b36d0a5a60c3b32
GitTreeState:  clean
BuildDate:     2024-01-31T17:54:40Z
GoVersion:     go1.21.6
Compiler:      gc
Platform:      linux/amd64

**Comment by haydentherapper** [comment]
Likely a dup of https://github.com/sigstore/sigstore/issues/1528, let me know if this does not cover the issue.

**Comment by suryabaiarava** [comment]
Hi @haydentherapper  can you please provide confirmation that this is the bug exist in the tool and still it is not resolved? Because as per this blog https://docs.sigstore.dev/verifying/verify/#retrieving-a-public-key i dont see any statment that it is not compatible with AKS KMS? or other way what is the solution for sign,verify if we are using AKS KMS?

$ cosign public-key --key <some provider>://<some key> > kms.pub
$ cosign verify --key kms.pub gcr.io/user-vmtest2/demo

**Comment by akashsinghal** [comment]
@haydentherapper would you be able to confirm if there's a workaround for this issue. I'm facing the same problem.
Is the only resolution to use a non RSA key when signing/verifying with azure key vault?
