### ISSUE TITLE
Cosign targets Go 1.21, but uses 1.22 only dependency `github.com/buildkite/agent/v3@v3.62.0`

### ISSUE THREAD

**Issue by cardil** [sigstore/cosign#3608]
**Description**

Cosign declares itself to be buildable with Go 1.21:

https://github.com/sigstore/cosign/blob/5d60a9a063a4c7c47dd63f4de43e951b55de24d8/go.mod#L3

However, it refers to a dependency `github.com/buildkite/agent/v3@v3.62.0`, which [is Go 1.22 only](https://github.com/buildkite/agent/blob/a67f3a1566fe3df450705fb98fec9f63300eceb4/go.mod#L3).

This causes problems for any package that imports Cosign, as you may see build errors, when running on Go 1.21.

My IDE fails with this command:

```
$ go list -json -m -u -mod=readonly all
go: loading module retractions for github.com/buildkite/agent/v3@v3.62.0: module github.com/buildkite/agent/v3@v3.66.0 requires go >= 1.22 (running go 1.21.4)
```
You could see the referral with:
```
$ go mod graph | grep github.com/buildkite/agent/v3
github.com/sigstore/cosign/v2@v2.2.3 github.com/buildkite/agent/v3@v3.62.0
```

**Version**

I'm using the latest released package: `github.com/sigstore/cosign/v2@v2.2.3`

**Comment by lmarchione-r7** [comment]
I'm getting the same error. Trying to build cosign 2.2.3 on Go 1.20. Do I need to upgrade to Go 1.21?

```
12:45:35  /go/pkg/mod/github.com/buildkite/agent/v3@v3.62.0/api/retryable.go:8:2: package slices is not in GOROOT (/usr/local/go/src/slices)
```

**Comment by haydentherapper** [comment]
1.21 is required, but we haven't moved to 1.22 yet.
