### ISSUE TITLE
latest tag not set automatically for v2 releases in GCR

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/cosign#3621]
**Description**

**Version**

I had noticed previously that when we cut a v2 release, the latest tag is not set automatically. https://github.com/sigstore/cosign/issues/3620 noted that after releasing the backport v1 release yesterday, the latest tag was set on the v1 release. We should a) figure out why the v2 releases aren't getting tagged as latest automatically and b) make sure that when we cut a v1 release, we add documentation to manually move the latest tag back to v2 or remove the code from the release-1.13 branch to update the tag.

**Comment by haydentherapper** [comment]
Confirmed this is still happening, I had to manually set latest for https://console.cloud.google.com/gcr/images/projectsigstore/global/cosign@sha256:bed7ba33a8610c1607c16dee696f62bad168814016126abb9da01e9fb7cb2167/details?project=projectsigstore

**Comment by cpanato** [comment]
i will take a look at this today
