### ISSUE TITLE
OIDC provider debugging

### ISSUE THREAD

**Issue by wlynch** [sigstore/cosign#3727]
**Description**

When trying to run cosign (particularly on a non-local workstation) it would be nice to have a command to confirm the OIDC provider behavior of what is/isn't enabled and in what order they are evaluated in.

```sh
$ cosign debug providers
filesystem: false
envvar: false
github-actions: false
buildkite-agent: false
spiffe: false
google-workload-identity: true
google-impersonate: false
```

This should be pretty easy to add - we would only need to expose the providers info + add a new subcommand. (I'm happy to make a PR for this)

**Comment by cpanato** [comment]
Please do
