### ISSUE TITLE
v1.0.0 Release

### ISSUE THREAD

**Issue by dekkagaijin** [sigstore/cosign#374]
Tracking issue for enhancements and fixes which should make it into 1.0.0. Open for comment!

- [ ] Sign releases with the TUF-based root of trust
- [x] Docs for `pkg`
- [ ] Code samples for `pkg`

**Comment by dlorenc** [comment]
A couple quick things we haven't tracked elsewhere:

- document the library extensively and footgun proof it. Anything dealing with unverified data should be private or clearly marked as unsafe.
- define what's in "experimental" clearly
- sign releases with our new root

**Comment by dekkagaijin** [comment]
Going to kick off a 3-week period for comment before releasing 1.0 on July 28

**Comment by lukehinds** [comment]
please also include https://github.com/sigstore/cosign/issues/87

this way cosign can be used (albeit experimental) against other fulcio roots (and not just the public instance)

I am working on this now, but figuring out a approach, if maintainer already has an idea how they want it done, please go ahead.

**Comment by cpanato** [comment]
we can close this and plan v1.1.0

**Comment by dekkagaijin** [comment]
Congrats and thank you, all
