### ISSUE TITLE
TUF key verification fails, even though identity verification validates

### ISSUE THREAD

**Issue by nipil** [sigstore/cosign#3746]
I am trying to verify the cosign binary using keys, following the [instructions](https://docs.sigstore.dev/system_config/installation/#verifying-with-key). I have built a small Dockerfile to test the process and i run it with Podman. 

Even if my orders of operation is wrong (i verified-blob before verifying with keys) i wanted to make sure my files were ok (the verify-blob pass) even if my key verification all fail.

There is either something i missed in the instructions, or something is not working as intended for key verification, or the instructions need updates.

Thanks in advance for any feedback, and sorry in advance if it is a user-error !
Nicolas

**Comment by nipil** [comment]
Here is my test image script.
Build it with : `podman build -t cosign-key-test .`

The unexpected result is that all run complete,
but each validation in the last one fails.

```
# syntax=docker/dockerfile:latest
FROM docker.io/library/debian:bookworm-slim

RUN \
apt-get update && \
apt-get -qq install -y --no-install-recommends curl ca-certificates golang && \
apt-get clean

RUN \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_2.2.4_amd64.deb && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_2.2.4_amd64.deb-keyless.pem && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_2.2.4_amd64.deb-keyless.sig && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64 && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64-keyless.pem && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64-keyless.sig && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_checksums.txt && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_checksums.txt-keyless.pem && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_checksums.txt-keyless.sig && \
curl -L -O https://github.com/sigstore/cosign/releases/download/v2.2.4/release-cosign.pub && \
for F in *.sig *.pem; do base64 -d $F > $F.decoded; done && \
chmod +x cosign-linux-amd64

RUN \
go install github.com/theupdateframework/go-tuf/cmd/tuf-client@latest

RUN \
./cosign-linux-amd64 verify-blob cosign-linux-amd64 --certificate cosign-linux-amd64-keyless.pem.decoded --signature cosign-linux-amd64-keyless.sig.decoded --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com && \
./cosign-linux-amd64 verify-blob cosign_2.2.4_amd64.deb --certificate cosign_2.2.4_amd64.deb-keyless.pem.decoded --signature cosign_2.2.4_amd64.deb-keyless.sig.decoded --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com && \
./cosign-linux-amd64 verify-blob cosign_checksums.txt --certificate cosign_checksums.txt-keyless.pem.decoded --signature cosign_checksums.txt-keyless.sig.decoded --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com

RUN \
curl -O https://raw.githubusercontent.com/sigstore/root-signing/main/ceremony/2022-10-18/repository/5.root.json && \
$(go env GOPATH)/bin/tuf-client init https://tuf-repo-cdn.sigstore.dev 5.root.json && \
$(go env GOPATH)/bin/tuf-client get https://tuf-repo-cdn.sigstore.dev artifact.pub > artifact.pub

RUN <<EOF
openssl dgst -sha256 -verify artifact.pub -signature cosign-linux-amd64-keyless.sig.decoded cosign-linux-amd64
openssl dgst -sha256 -verify artifact.pub -signature cosign_2.2.4_amd64.deb-keyless.sig.decoded cosign_2.2.4_amd64.deb
openssl dgst -sha256 -verify artifact.pub -signature cosign_checksums.txt-keyless.sig.decoded cosign_checksums.txt
EOF
```

**Comment by haydentherapper** [comment]
Do you have an error message?

**Comment by nipil** [comment]
Here is the final output :

```
root@86c3921385b6:/# openssl dgst -sha256 -verify artifact.pub -signature cosign-linux-amd64-keyless.sig.decoded cosign-linux-amd64
Verification failure
root@86c3921385b6:/# openssl dgst -sha256 -verify artifact.pub -signature cosign_2.2.4_amd64.deb-keyless.sig.decoded cosign_2.2.4_amd64.deb
Verification failure
root@86c3921385b6:/# openssl dgst -sha256 -verify artifact.pub -signature cosign_checksums.txt-keyless.sig.decoded cosign_checksums.txt
Verification failure
```

No error message, no crash, just a failed verification. That is why i provided you with the Docker recipe to reproduce it, because it may not be linked to a bug, but to a misunderstood or misdocumented walkthough.

**Comment by haydentherapper** [comment]
Ah, I see the issue. You need to download the non-keyless sig, like `https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-darwin-arm64.sig`. `keyless-sig` means that it's a Sigstore signature and needs to be verified by Cosign since it's signed with an ephemeral key, with the certificate from the `pem` file. The `.sig` signatures are signed with the artifact key.

I followed the exact steps listed on the documentation and verification worked.

**Comment by nipil** [comment]
Oooooh. Ok, now i get it.

So i have to do DEB packages in three phases :

Preliminary check :

1. i first needed to get a cosign raw **binary**
2. and i need to get the **non**-keyless sig _for the binary_
3. then locally verify the binary using openssl

Package check :

5. then download the deb package
6. and the **keyless**-signature _for the deb file_
7. then verify the deb signature _using cosign binary_ (previously verified)

Target goal :

8. install verified deb package
9. remove all temporary files _including the transient cosign binary_

What tripped me was that i expected any "binary" package (raw, deb, rpm, etc.) to be provided with **non**-keyless sig, so that you was trying to only do steps 1/2/3 and 8 (working on the deb).

May i suggest that you provide/generate non-keyless sig for any form of cosign release ? As i am quite a newbie on this topic, my suggestion might not be relevant, so feel free ot ignore it.

Anyway, thank you for your help, and have a nice day
Nicolas

**Comment by haydentherapper** [comment]
All of our Cosign releases should have a non-keyless sig so that the Cosign release can be verified without Cosign. Once you have a verified Cosign release, you can then verify subsequent Cosign releases using the keyless signature.
