### ISSUE TITLE
fix golangci-lint issues in the test/ directory

### ISSUE THREAD

**Issue by dmitris** [sigstore/cosign#3760]
**Description**

Current `golangci-lint` issues from `golangci-lint run --build-tags e2e ./test`: https://gist.github.com/dmitris/5b43918c553946a3b77247622d63e277
need to fix at least some of them - those that are "reasonable" to fix (ex. I would pass on the `errcheck` issues - `"Error return value of [...] is not checked"`.

**Comment by cpanato** [comment]
thanks, i will work on those, maybe we can also enable this to run on ci

**Comment by dmitris** [comment]
for CI, it would be good to add a `.golangci.yml` file and disable there the "noisy" linters (such as `errcheck`) which we don't want to enforce.

**Comment by cpanato** [comment]
i think we want the `errcheck` even if that is kind noisy

**Comment by dmitris** [comment]
> i think we want the `errcheck` even if that is kind noisy

but then we wouldn't be able to break the builds on new golangci-lint issues, right? Unless we either fix or `//nolint:errcheck` the "preexisting conditions"
