### ISSUE TITLE
Firm up the spec around our bundle

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#381]
I think the bundle format has changed a bit recently @asraa added SET verification in #371, we're also working on better timestamp protocols.

We should take a pass at updating the spec a bit, including info on how to verify each one of these elements.

**Comment by asraa** [comment]
> @asraa added SET verification in #371

Bundle was already doing this!

But yes, speaking of this -- do we want to move SignedEntryTimestamp to a signed note formatted timestamp when this is done?
