### ISSUE TITLE
Cosign with AWS ECR 

### ISSUE THREAD

**Issue by mkinage** [sigstore/cosign#383]
We are working on configuring Docker trust using cosign with AWS ECR. I am able to sign Docker image but getting the below error while running a Docker.
Error: remote trust data does not exist for does not have trust data for awsaccno.dkr.ecr.us-west-2.amazonaws.com/testapp
Please let me know if I missed anything,

**Comment by cpanato** [comment]
hello @mkinage, can you provide the command that you are running and maybe the full output of the execution?

thanks!

**Comment by mkinage** [comment]
1.	Cosign installed using the below step
go install github.com/sigstore/cosign/cmd/cosign@latest

2.	Generate the key pair 
cosign generate-key-pair

3.	Sign the Docker image 
cosign sign -key cosign.key awsaccid.dkr.ecr.us-west-2.amazonaws.com/dockerimagename:1.0.111

4.	Verify Docker image
cosign verify -key cosign.pub awsaccid.dkr.ecr.us-west-2.amazonaws.com/ dockerimagename:1.0.111

All the above steps are working.

5.	Run the Docker 
export DOCKER_CONTENT_TRUST=1
docker run  -m 2098m \
> --restart on-failure -e "SET_CONTAINER_TIMEZONE=true" \
> -e CLASSPATH="$CLASSPATH" -e JAVA_OPTS="$OPTS" -Pd -p 2020:8080 --name dockerimagename awsaccid.dkr.ecr.us-west-2.amazonaws.com/dockerimagename:1.0.111
docker: Error: remote trust data does not exist for awsaccid.dkr.ecr.us-west-2.amazonaws.com/dockerimagename: awsaccid.dkr.ecr.us-west-2.amazonaws.com does not have trust data for awsaccid.dkr.ecr.us-west-2.amazonaws.com/devopstestbootbe.


Please find the steps I have performed. 

Thanks,

**Comment by dlorenc** [comment]
Cosign is not actually compatible with Notary/Docker Content Trust, so this is by design.

Could you explain more about your use case? Are you trying to prevent deployment into specific environments?

**Comment by mkinage** [comment]
We have requirement to enable docker signing and run only signed images on the server. Can we achieve this without Notary / Docker content Trust. 
Appreciate your help.

**Comment by 06kellyjac** [comment]
If you're using kubernetes you can try @dlorenc's admission controller https://github.com/dlorenc/cosigned

For other setups you'll probably need to set up your own checks and balances

**Comment by mkinage** [comment]
Thank you for the link. We are not running kubernetes. 

Appreciate if you can provide any link or documentation to set up with docker.

**Comment by 06kellyjac** [comment]
I can't find much but your best bet is probably going to be writing a docker engine plugin https://docs.docker.com/engine/extend hopefully you could verify the image and then prevent it from being used before it actually runs the container (IDK if that's possible through the plugin system).

Or you could have a program that watches docker for running containers, verifies their image, then kills them if they're not verified but that could have a container run for a couple of seconds before it's actually killed

**Comment by mkinage** [comment]
Hi All,
Thank you very much for your prompt response. 

Our use case is, we want to prevent our containers getting modified outside of our CD pipeline and only our signed container through pipeline can be deployed. since docker notary  is in commericial version, we are looking for open source free solution for same.

Below is the error we are getting by disabling Docker content trust,
docker run  -m 2098m --restart on-failure -e "SET_CONTAINER_TIMEZONE=true" -e CLASSPATH="$CLASSPATH" -e JAVA_OPTS="$OPTS" -Pd -p 2020:8080 --name dockerimagename awsaccid.dkr.ecr.us-west-2.amazonaws.com/dockerimagename:$TAG
Unable to find image 'awsaccid.dkr.ecr.us-west-2.amazonaws.com/dockerimagename:sha256-0ff118710bb3f6afasfsdfsdfdsfdddfdfd453a8dd2ac21.sig' locally
sha256-0ff118710bb3f6afasfsdfsdfdsfdddfdfd453a8dd2ac21.sig: Pulling from dockerimagename
0ff118710bb3: Extracting [==================================================>]     277B/277B
docker: failed to register layer: Error processing tar file(exit status 1): unexpected EOF.

**Comment by 06kellyjac** [comment]
If it's trying to pull something ending with `.sig` I can only assume that's part of docker content trust signature verification, you might still have it enabled in your daemon config?
Unless that is part of the `$TAG` var and you're referring to an image that doesn't exist?

You can use notary with registries other than comercial docker such as the harbor registry which is apache 2.0 licensed:
https://goharbor.io/docs/1.10/install-config/run-installer-script/
https://github.com/goharbor/harbor

But again notary is a different project to the efforts of sigstore/cosign

**Comment by mkinage** [comment]
Thank you for the update. 
I will check both points.

**Comment by mkinage** [comment]
I found when I am trying to sign image the sign going in to tag and our original tag which is build number getting removed. Is there any way we can add a tag with sign. 
Pushing signature to: awsaccid.dkr.ecr.us-west-2.amazonaws.com/ dockerimagename:sha256-0ff118710bb3f6afasfsdfsdfdsfdddfdfd453a8dd2ac21.sig

**Comment by dlorenc** [comment]
Hey @mkinage!

Yup - you can use the "-a" flag to add annotations into the signed payload. Something like:

cosign sign -a build=number $image 

Then that key/value pair gets signed too. You can select on that during verification too:

cosign verify -a build=number -key key $image

**Comment by mkinage** [comment]
Thank you very much for the update.
I have tried to do the above mentioned steps, I am able to push and verify image. How can I run the docker with tag.
Appreciate if you can provide steps or documentation to run container.

**Comment by mkinage** [comment]
It is working with the provided solution. Thank you very much.

**Comment by omerfsen** [comment]
+1

**Comment by tanvp112** [comment]
`... How can I run the docker with tag...`

hi @mkinage, can you elaborate how you achieve the run (presumably with the sha and tag)?

**Comment by ckingbailey** [comment]
@mkinage how did you enforce signature verification on/before running a Docker container? Did you follow @06kellyjac's [suggestion](https://github.com/sigstore/cosign/issues/383#issuecomment-865957513) to have a program listen for Docker run events, verify the image, and kill the container if verification fails? I'm trying to do exactly that with a Lambda, but I'm unable to `docker login` on the Lambda so then cosign can't access the registry to verify the image.

Curious if anyone else has had success enforcing Docker signing on ECR/ECS with Cosign, and what their setup is.

**Comment by dlorenc** [comment]
We have a few guides on EKS but I'm not sure how to do this on ECS. Do you want to open a separate issue and we can figure it out?

**Comment by ckingbailey** [comment]
@dlorenc separate issue opened https://github.com/sigstore/cosign/issues/1212
