### ISSUE TITLE
Signed container images push to GCP Artifact Registry are unsuable

### ISSUE THREAD

**Issue by lucstjean-ssc** [sigstore/cosign#3929]
**Question**
I am signing a container image with cosign and pushing it to the Artifact Registry, but I cannot pull the signed image or use it with Cloud Run.

GitVersion:    v2.4.1
GitCommit:     9a4cfe1aae777984c07ce373d97a65428bbff734
GitTreeState:  clean
BuildDate:     2024-10-03T17:01:50Z
GoVersion:     go1.22.7
Compiler:      gc
Platform:      linux/amd64 

docker pull gives this error:
unsupported media type application/vnd.dev.cosign.simplesigning.v1+json

Trying to start a container in Cloud Run with the signed images gives me this error:
Revision 'container-00001-9vh' is not ready and cannot serve traffic. Container import failed

I tried using COSIGN_DOCKER_MEDIA_TYPES=1 and COSIGN_EXPERIMENTAL=1, but nothing worked.

**Comment by bobcallaway** [comment]
What are you using as the reference to the image?

**Comment by lucstjean-ssc** [comment]
I am using the Digest to sign the container image:

cosign sign --key cosign.key northamerica-northeast1-docker.pkg.dev/gcp-project/my-docker-repo/mycontainer@$DIGEST -y

Deploying to Cloud Run using the signed image:

Example:
gcloud run deploy myrunservice \
--image=northamerica-northeast1-docker.pkg.dev/gcp-project/my-docker-repo/mycontainer:sha256-bb12e4f26c51bab9932c033654551a305db15cafa8c2601531352da17f2a7130.sig \
--region=northamerica-northeast1 \
--project=gcp-project

**Comment by bobcallaway** [comment]
Take the “.sig” off of the reference in the “gcloud run” command.

**Comment by lucstjean-ssc** [comment]
I get an error that the image is not found when removing the ".sig" from the command.

**Comment by bobcallaway** [comment]
sorry, forgot you need to fix the `@` too:

`--image=northamerica-northeast1-docker.pkg.dev/gcp-project/my-docker-repo/mycontainer@sha256:bb12e4f26c51bab9932c033654551a305db15cafa8c2601531352da17f2a7130`

**Comment by lucstjean-ssc** [comment]
Thanks, Bob. I was under the impression that I had to reference the signed container image.

**Comment by bobcallaway** [comment]
> Thanks, Bob. I was under the impression that I had to reference the signed container image.

Nope, the signature is stored as a separate OCI artifact.
