### ISSUE TITLE
Cosign: /usr/bin/cosign: cannot execute: required file not found

### ISSUE THREAD

**Issue by Gennady-tech** [sigstore/cosign#3948]
I am building kaniko two docker files

`time /kaniko/executor \`
          `--context "${CI_PROJECT_DIR}" \`
          `${DOCKER_BUILD_ARGS} \`
          `--dockerfile "${CI_PROJECT_DIR}/Dockerfile-swarm" \`
          `--destination "${IMAGE_UNSTABLE_TAG_VERSION}" \`
         ` --destination "${IMAGE_UNSTABLE_TAG_HASH}"`
       ` echo "${COSIGN_PK}    ${IMAGE_UNSTABLE_TAG_VERSION}"`
     `   cosign sign --key ${COSIGN_PK} ${IMAGE_UNSTABLE_TAG_VERSION}`
   `     time /kaniko/executor \`
     `     --context "${CI_PROJECT_DIR}" \`
        `  ${DOCKER_BUILD_ARGS} \`
 `         --dockerfile "${CI_PROJECT_DIR}/Dockerfile-k8s" \`
       `   --destination "${IMAGE_UNSTABLE_K8S_TAG_VERSION}" \`
       `   --destination "${IMAGE_UNSTABLE_K8S_TAG_HASH}"`

when signing an image I get an error 
`cosign sign --key ${COSIGN_PK} ${IMAGE_UNSTABLE_K8S_TAG_VERSION}`
`/bin/bash: line 389: /usr/bin/cosign: cannot execute: required file not found`

how to fix please tell me?

I also receive
`error pushing image: failed to push to destination: HEAD unexpected status code 412 Precondition Failed (HEAD responses have no body, use GET for details)`

**Comment by haydentherapper** [comment]
This isn't an issue with Cosign. Your path seems to be missing the cosign binary.

**Comment by Gennady-tech** [comment]
yes but not quite like that. library is missing
`bash: /usr/bin/cosign: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory`

**Comment by crispysipper** [comment]
This likely isn't a problem with cosign - I'm having a similar and very weird problem within a Gitlab-CI job

```
  /opt/kaniko/executor \
    --context "${CI_PROJECT_DIR}" \
    --dockerfile "${CI_PROJECT_DIR}/$[[ inputs.dockerfile ]]" \
    --tar-path "artifacts/${nameTag}.tar" \
    --destination "${tag}" \
    --no-push 
  skopeo copy docker-archive:${nameTag}.tar oci-archive:${nameTag}.tar
  
  line 204: /usr/bin/skopeo: cannot execute: required file not found
```

I am using a custom kaniko image (meaning I copied the binaries from the GCR image into a utility image) and skopeo is also installed on it.  I've debugged this for hours and still not exactly sure why this behavior occurs.  From what I can tell, the `skopeo` command is acting like it is being executed inside the same container as the Dockerfile and as a result cannot locate it.  It's like the build isn't exiting or something.  Probably the weirdest issue I've come across in my time.  

Even a simple `skopeo -v` results in the same behavior.

If I take `RUN` commands out of the dockerfile, all works fine
Debug your job by running a `cat /etc/os-release` in place of your cosign command - you may be surprised what you see.
