### ISSUE TITLE
Cosign flag --No

### ISSUE THREAD

**Issue by Gennady-tech** [sigstore/cosign#3952]
how to use --No flag in cosign?

`cosign sign --key COS alpine:3.20 -N`

```
Error: unknown shorthand flag: 'N' in -N
main.go:74: error during command execution: unknown shorthand flag: 'N' in -N
```

**Comment by haydentherapper** [comment]
There's no `no` flag, there's a `yes` flag if you're skipping confirmations.

**Comment by Gennady-tech** [comment]
i am finally solution 
cosign sign  --tlog-upload=false --key  COS alpine:3.20
