### ISSUE TITLE
proposal: cmd: add sign-catalog & verify-catalog, for all images in the registry

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#410]
Let's assume that we are already using gcr.io to keep our container images.

We know that `gcr.io` is based on [Registry API v2](https://docs.docker.com/registry/spec/api/), which means that we can use the `v2/_catalog` endpoint to get all the repositories that we already have in the container registry.

```shell=bash
$ TOKEN=$(gcloud auth print-access-token)
$ curl --silent --show-error -u_token:"$TOKEN" -X GET "https://gcr.io/v2/_catalog" | jq
{
  "repositories": [
    "developerguy-311909/falco-event-listener-355c83b3413baa4dc0f62f21c3a83388",
    "developerguy-311909/hello-artifact",
    "developerguy-311909/hello-k8s-manifest-sigstore",
    "developerguy-311909/hello-world",
    "developerguy-311909/hello-world-cloud-run-7180d673dcdbbeb522ccafd97f570269"
  ]
}
```

So, we can use this kind of information to sign & verify all the images belongs to the repositories at once.

#### Risk and Mitigations

* If you have a huge amount of repositories, this process might be cumbersome. So maybe, we may want to use some kind of paging system like sign and verify the first 100 repositories at once until the user won't provide a flag like --size.
* User may want to sign and verify some specific tag of the images within the repository, so we have to provide a flag to support that kind of situation.

**Comment by joaodrp** [comment]
Keep in mind that the `_catalog` endpoint is _far_ from being widely supported across registry providers, and in fact it's no longer part of the [OCI Distribution spec](https://github.com/opencontainers/distribution-spec), so this could lead to a poor/broken UX.

**Comment by dlorenc** [comment]
Yeah - it's unfortunate but probably not worth trying just yet.

**Comment by developer-guy** [comment]
thank you so much for the explanations, at least I learned something new through this PR.
