### ISSUE TITLE
Expose OIDC values as flags

### ISSUE THREAD

**Issue by lukehinds** [sigstore/cosign#461]
Currently oidc and fulcio connectivity is hard coded:

https://github.com/sigstore/cosign/blob/5879961e2d5c17b67188a7d7520320022958eea5/pkg/cosign/fulcio/fulcio.go#L45-L53

Expose these as flags, so that users can also try out keyless against their own infra.

**Comment by lukehinds** [comment]
To add, it would be nice to get this into 1.0 , as sigstore the hard way uses cosign to demo keyless.

**Comment by dlorenc** [comment]
There's an env var for fulcio currently, we could also add a flag. We don't have anything for the oidc one, we need to add that.

**Comment by lukehinds** [comment]
resolved here https://github.com/sigstore/cosign/pull/462
