### ISSUE TITLE
Document Package Managers!

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#467]
We're in Arch and Nix. We should show how to install cosign with these!

**Comment by cpanato** [comment]
should we make for brew as well?

**Comment by dlorenc** [comment]
The more the merrier!

**Comment by cpanato** [comment]
now we have brew as well: https://github.com/sigstore/homebrew-tap

**Comment by cpanato** [comment]
will document all during next week

/assign

**Comment by endorama** [comment]
PR is ready and waiting for a review.
