### ISSUE TITLE
Feature: Add support for custom attestation predicate types

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#472]
Right now we hardcode a specific one for cosign. We should add a flag to select a different one, and then have an index of "well-known" predicates that can be unmarshalled correctly/validated into a go struct

**Comment by developer-guy** [comment]
The documentation for the "well-known" precidates within the in-toto's attestation spec can be found by following the link:

https://github.com/in-toto/attestation/blob/main/spec/README.md

**Comment by developer-guy** [comment]
there is also another discussion going on about another type of predicate for vulnerability scans.
https://github.com/sigstore/cosign/issues/442
