### ISSUE TITLE
Binary release not working on alpine based images

### ISSUE THREAD

**Issue by angelbarrera92** [sigstore/cosign#494]
Hi!

I am trying to automate the singning of a container image in a pipeline. It runs inside an alpine container image and the error reported is:

```bash
/bin/sh: cosign: not found
```

To reproduce the issue follow these steps:

```bash
$ docker run -it --rm alpine:3 /bin/sh
Unable to find image 'alpine:3' locally
3: Pulling from library/alpine
5843afab3874: Pull complete 
Digest: sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0
Status: Downloaded newer image for alpine:3
/ # wget -q -O /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v0.6.0/cosign_linux_amd64_0.6.0_linux_amd64
/ # chmod +x /usr/local/bin/cosign
/ # cosign
/bin/sh: cosign: not found
/ # apk add pcsc-lite-libs
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/1) Installing pcsc-lite-libs (1.9.1-r0)
OK: 6 MiB in 15 packages
/ # cosign
/bin/sh: cosign: not found
/ # 
```

I think is missing a OS dependency... How can i figure out which one is missing?

**Comment by angelbarrera92** [comment]
"Solved" installing also `libc6-compat`.

```bash
$ apk add --no-cache pcsc-lite-libs libc6-compat
```

So maybe it could be a good idea building the release binaries with the `CGO_ENABLED=0` flag. What do you think?

**Comment by cpanato** [comment]
yep the release 0.6.0 for linux need this extra dependency, which is removed and the release 1.0.0 will not break this :( sorry for that

you also can use the image available: `gcr.io/projectsigstore/cosign:v0.6.0@sha256:2303322158802ec0452758578ac80801a3754ee9cb19c128fc5d1b2ec32fa2d2`
