### ISSUE TITLE
cosign binary sig verify instructions should be present

### ISSUE THREAD

**Issue by lukehinds** [sigstore/cosign#506]
The release page and [installation section](https://github.com/sigstore/cosign#releases) should  give users details on how to verify sigs (using openssl, and not cosign validating itself)

What do they verify with? Against the binary, the cosign_checksums.txt, the hash for the binary in cosign_checksums.txt?

**Comment by dlorenc** [comment]
cc @cpanato

**Comment by dlorenc** [comment]
Added a section on the release page:
![image](https://user-images.githubusercontent.com/1714486/127495601-4fb6bf4e-b6f3-43ea-a603-d2234fc647ee.png)


We had this back on the 0.1 release, but forgot to copy it forward!

**Comment by lukehinds** [comment]
> Added a section on the release page:
> ![image](https://user-images.githubusercontent.com/1714486/127495601-4fb6bf4e-b6f3-43ea-a603-d2234fc647ee.png)
> 
> We had this back on the 0.1 release, but forgot to copy it forward!

awesome, thanks dan!

**Comment by anish-yadav** [comment]
Error Verifying Data
139669014983104:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
139669014983104:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:290:Type=ECDSA_SIG

getting this error while trying to verify the data

**Comment by dlorenc** [comment]
Could you include the full command you tried?

**Comment by anish-yadav** [comment]
@dlorenc is their something wrong that i am doing.
what I want is to sign the images (docker) using cosign but verify using openssl

**Comment by anish-yadav** [comment]
@dlorenc 
`
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 233,
    "digest": "sha256:3b25a088710d03f39be26629d22eb68cd277a01673b9cb461c4c24fbf8c81c89"
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.descriptor.v1+json",
      "size": 217,
      "digest": "sha256:0e79a356609f038089088ec46fd95f4649d04de989487220b1a0adbcc63fadae",
      "annotations": {
        "dev.sigstore.cosign/signature": "5uNZKEP9rm8zxAL0VVX7McMmyArzLqtxMTNPjPO2ns+5GJpBeXg+i9ILU+WjmGAKBCqiexTxzLC1/nkOzD4cDA=="
      }
    }
  ]
}
`
So you mean I need to use this signature 5uNZKEP9rm8zxAL0VVX7McMmyArzLqtxMTNPjPO2ns+5GJpBeXg+i9ILU+WjmGAKBCqiexTxzLC1/nkOzD4cDA==
do a base64 decode and check it with whatever the output of cosign generate $IMAGE?
