### ISSUE TITLE
1.0.1 tag but no corresponding release

### ISSUE THREAD

**Issue by 06kellyjac** [sigstore/cosign#514]
**Question**

Why is there a 1.0.1 tag but no corresponding release?

**Comment by dlorenc** [comment]
cc @dekkagaijin 

The changes were only to the internal pkg structure, designed to make the code a little easier to use as a library. The tag was to make it so go would import this version, but there should be no functional difference to the binary. We should probably just release binaries again anyway though for consistency.

**Comment by 06kellyjac** [comment]
Cool, that answers my question :+1:

**Comment by dekkagaijin** [comment]
Yup, just wanted `go mod` to pick up the PRs which pruned the surface of `pkg` ASAP. Functionality of the binaries weren't modified
