### ISSUE TITLE
Unable to add multiple signature layers using Vault KMS

### ISSUE THREAD

**Issue by mrjoelkamp** [sigstore/cosign#547]
**Description**

It looks like there is a bug in the read, modify, write process when using Vault as the KMS. 
`cosign sign -key hashivault://key repo_path/image:tag`

I've ensured that registry immutability is turned off and have used both AWS ECR and Docker Hub registries for troubleshooting.

Here is a summary of what I have tested:
- Cosign signature manifest is successfully created using Vault if no signature currently exists in the repo for the specified image
- Using a different Vault key to apply another signature to the manifest does not update the signature manifest
- Using a local key `cosign sign -key cosign.key ...` will successfully add signature layers an existing Vault key signature manifest
- Creating a signature manifest first with a local key then signing again with Vault key results in no changes

This makes me believe that there must be a bug somewhere in the read/modify/write process when using Vault as a KMS.

Looking at the debug output I do notice that there isn't any `HTTP 201 Created` output at the very end of the signing process when using Vault to add an additional signature to an existing manifest. So maybe it just isn't running the push process?

**Comment by rjbrown57** [comment]
I can confirm I'm also seeing this behavior

**Comment by dlorenc** [comment]
Hmm, my only guess here is that our "duplicate signature detector" isn't working correctly with vault. 

Just to confirm, are these completely different vault keys? One should not verify for the other? I'm not a vault expert, is there anything special you did to set this up, or just the standard vault setup?

@developer-guy @Dentrax any guesses? I think you're more experienced with vault than I am.

**Comment by Dentrax** [comment]
Thanks for the reporting this! We can get to it; I think it's uncovered use-case from the cosign side.

@mrjoelkamp Would you mind adding some _steps to reproduce_ command list here?

**Comment by mrjoelkamp** [comment]
@dlorenc To confirm they are different keys. I ran `cosign generate-key-pair -kms hashivault://key1` and again for `key2` and attempted to sign, in two operations, using both keys. In addition to that, if I signed the image with a local key, say `cosign.key`, generated using `cosign generate-key-pair` locally, sign the image, and try to add a signature to that newly signed image using Vault KMS with `cosign sign -key hashivault://key1 [image]` it would not add the signature. 

Nothing special here, just the standard Vault setup using they built in local `-dev` option to run a local server. I also tried with my hosted Vault server as well.

**Comment by Dentrax** [comment]
Oh, just find the issue, i guess. This happening because of our [duplicate detecting](https://github.com/sigstore/cosign/blob/0d93915ab1a53ffb4d4a1a7263a3faa0623a1bf4/pkg/cosign/remote/remote.go#L123-L125) logic.

```bash
$ crane manifest furkanturkal/busybox:sha256-1775bebec23e1f3ce486989bfc9ff3c4e951690df84aa9f926497d82f2ffca9d.sig | jq
```

```json
{
  "layers": [
    {
      "digest": "sha256:2bf4e3bcb4d5e236810a4b1bc0e5ee190bc1fc15acae24cb9f27d2732b518bff",
      "annotations": {
        "dev.cosignproject.cosign/signature": "MEUCID5EIAmCQNaL7ZYF/Fi4rEgoPHSbE7JA/Ox2eYMHz7loAiEAz6GMhUE7Q7SCQlyIh73YrfD3troJdvvG0thYuysBgN4="
      }
    }
  ]
}
```

As far as I can see, we do not allow uploading new _layer_ since we already have calculated `digest`.

If we run the following command:
```bash
$ cosign sign -key cosign.key furkanturkal/busybox:0.4.0
```

...we do not break the `LayerLoop()` function loop here, since we got the `err != nil`.

```
if err := dupeDetector.VerifySignature(bytes.NewReader(uploadedSig), bytes.NewReader(payload)); err == nil {
  // An equivalent signature has already been uploaded.
  return uploadedSig, nil
}
```

But we are falling in `return` and break the loop if we use remote `hashivault://key` provider. 🤔

**Comment by dlorenc** [comment]
Did we fix this one?
