### ISSUE TITLE
Signing with 3rd party tool

### ISSUE THREAD

**Issue by zosocanuck** [sigstore/cosign#548]
Hi,

I'm attempting to sign with another tool and using the output of:

`cosign generate xxx/yyy `to produce the JSON payload.

Shoud I be sending the entire payload for signature?

If so I then attach the signature using:

cosign attach signature -signature xyz xxx/yyy

The end result is when I attempt to verify I get:

```
error: no matching signatures:
failed to verify signature
 failed to verify signature
 failed to verify signature
 failed to verify signature
 failed to verify signature

```

cosign version is v1.0.0

**Comment by dlorenc** [comment]
Could you share the full command you used to sign the image? Depending on what it is, cosign might not be able to directly verify it. You'd have to use `cosign download signature`, similar to `cosign attach signature` to fetch them then verify again with that tool.

**Comment by zosocanuck** [comment]
I'm using a REST API to sign payloads, and the backend system is performing EcdsaSha256 for signatures.  I assume cosign verify also does EcdsaSha256?

**Comment by dlorenc** [comment]
That's correct - it uses ECDSA with the P256 curve, and the SHA-256 hash. Have you been able to verify the signatures manually with something like openssl?

**Comment by zosocanuck** [comment]
Yes, I'm using a commercial tool to sign and verify successfully.

**Comment by dlorenc** [comment]
I wrote up a gist yesterday on how to sign with openssl and verify with cosign, does this help at all? https://gist.github.com/dlorenc/919210e3e5531c50b573467b8c252533

**Comment by zosocanuck** [comment]
Yes, this was helpful.  Closing this issue for now as I need to investigate why a 3rd party utility is not producing compatible signatures.
