### ISSUE TITLE
Include a cosign custom and independent Kubernetes admission controller to verify images

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#550]
**Question**

I believe sigstore should include under his own organization an implementation of a cosign admission controller for Kubernetes. This idea does not aim to replace any other possible implementation of verifiers or admission controllers that exist out there. The intention is to have a custom and independent admission controller that simply verifies Kubernetes resources using cosign. The community could maintain this cosign implementation under sigstore organization, and thereby eases its maintenance and testing as part of every release.

The initial idea would be to reuse https://github.com/dlorenc/cosigned implementation and upgrade it following common and best practices when developing a controller for Kubernetes. 

What do you think about it ?

**Comment by dlorenc** [comment]
Thanks for filing! Ref #196 as well.

I'm open to moving that code over here if there's demand for it! I started it as a learning project and then kept it separate because I didn't want to slow down support for cosign in other full-featured policy systems like Gatekeeper or kyverno, but I think we're past that point now.

So, +1 on moving it in if people are interested in using i!

**Comment by hectorj2f** [comment]
Thanks @dlorenc.

Yes. Even if anyone can still use the implementations from Gatekeeper, Kyverno or Connaisseur. I believe there is a benefit having a single-purpose admission controller that adapts to the on-going cosign development and lives under the sigstore umbrella.

**Comment by dlorenc** [comment]
@developer-guy what do you think here? I think it would be easiest to keep in the same repo as cosign long term if there's interest.

**Comment by developer-guy** [comment]
> I believe there is a benefit having a single-purpose admission controller that adapts to the on-going cosign development and lives under the sigstore umbrella.

Yeah, I agree with @hectorj2f, we should definitely move the cosigned project into the sigstore organization and start maintaining it from there, that would be awesome and we (w/@Dentrax) would love to get involved in it because we really like to work with Kubernetes extension points like AdmissionWebhooks. 

> I think it would be easiest to keep in the same repo as cosign long term if there's interest.

Yeah, makes sense 🤝

**Comment by dlorenc** [comment]
OK, SGTM! Want to start moving code over @hectorj2f?

**Comment by hectorj2f** [comment]
@dlorenc Good news 🎉 !. Yes, it sounds good to me. 

I would move your code to cosign repository under a gitmodule. So we could start to add enhancements/improvements once all the cosigned foundation is in there.

**Comment by dlorenc** [comment]
Ugh, git submodules always cause me trouble. I'll try to get it merged in one shot to avoid complications.

**Comment by hectorj2f** [comment]
@dlorenc i am working on a PR, i did added to the current cosign code without having a new gomodule.

**Comment by hectorj2f** [comment]
I might get it ready for a review tomorrow.

**Comment by dlorenc** [comment]
Great! I opened #558 to start to make it easier to add new maintainers. When you're ready, send a PR there as well to get yourself added!

**Comment by hectorj2f** [comment]
I migrated the code with some changes and additions. I believe we need to clarify the release process and how to inject it into the current one. 
https://github.com/sigstore/cosign/pull/565 (the chart would live under `helm-charts` if everyone is happy with that).
https://github.com/sigstore/helm-charts/pull/9

**Comment by developer-guy** [comment]
> (the chart would live under helm-charts if everyone is happy with that).

that would be great, I really want to get involved in it. 🙏🤝

**Comment by dlorenc** [comment]
Closing, we're here!
