### ISSUE TITLE
Dev releases marked as stable releases

### ISSUE THREAD

**Issue by alexellis** [sigstore/cosign#585]
**Description**

Hi, we are offering cosign as a download in [arkade](https://arkade.dev), a Kubernetes marketplace.

The dev releases are being marked as "stable releases", but if they were marked as pre-release, then GitHub's API would show us the latest v1.0 etc release to download.

Most projects don't mark dev or preview / RC releases as full releases. It's a checkbox in the UI, I wonder what your thoughts are?

As it is, we'd need to hard-code a cosign version because GitHub's API can't determine which is the stable release.

Thanks,

Alex

**Comment by dekkagaijin** [comment]
@cpanato we should probably mark them as pre-releases, then, to avoid conflicts with the Go toolchain and the main binary/package releases

**Comment by cpanato** [comment]
@dekkagaijin @dlorenc how about we have a dedicated repo for the Helm Charts?
then we can add rekor helm chart, fulcio helm chart, and others together with the cosigned.

WDYT?

**Comment by dlorenc** [comment]
That works!

**Comment by cpanato** [comment]
@dlorenc i will ping you in slack to talk about and to create the repo 🎸

**Comment by cpanato** [comment]
done! we can close this

**Comment by cpanato** [comment]
move to here: https://github.com/sigstore/helm-charts

PR: https://github.com/sigstore/helm-charts/pull/10
