### ISSUE TITLE
Verify SCTs

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#591]
Fulcio now returns SCTs as a header: https://github.com/sigstore/fulcio/pull/163

Let's verify those in cosign when getting a cert!

**Comment by dlorenc** [comment]
cc @priyawadhwa you were looking at this kind of right?

**Comment by priyawadhwa** [comment]
Yah, this was the last thing we needed for bundling to be complete!

We can verify the SCT when we get it, add it to the bundle, and verify again whenever `cosign verify` gets run?
