### ISSUE TITLE
Support deployment lifecycle of an environment/image

### ISSUE THREAD

**Issue by deedubs** [sigstore/cosign#595]
I would like to be able to answer the questions:

1. When was this container image sha256 deployed to production and when was it retired?
2. What images have been deployed to staging in the last 5 days?
3. What image was running in QA last Tuesday at 4:45 PM GMT?

## Use case 1

I discover a vulnerability in a container image, I want to know when and where the code was ever deployed.

## Use case 2

I discover anomalous activity on a container orchestration platform and want a report of the images deployed at the time.

**Comment by dlorenc** [comment]
Nice! Thanks for getting it started, and these questions you'd like to answer are the perfect way to think about attestation schemas.

For an "environment", do you think a simple name like "prod" or "qa" is enough? Or do we need a way to reflect more details?

**Comment by deedubs** [comment]
I think we'd need some more context, I'm thinking situations like multiple regions, partial rollouts that were aborted, etc

**Comment by dlorenc** [comment]
Yeah... Any other ideas? We could wrap it up in a URI `acme.com/<environment>/<region>/<service>` or maybe just use a set of labels?

**Comment by deedubs** [comment]
I think I like the idea of a URI! 

It will let users bring their own org structure as well as it could reference an entry with additional details / context of the env itself.
