### ISSUE TITLE
cmd/verify: allow pass by url for signature flag

### ISSUE THREAD

**Issue by Dentrax** [sigstore/cosign#608]
**Description**
Currently, `-signature` flag only supports [filepath](https://github.com/sigstore/cosign/blob/54c956cf8bd38769a322d73f6da3866684716572/cmd/cosign/cli/verify_blob.go#L157-L177). Would it be good practice to pass a URL for this flag? i.e., GitHub download link:

```bash
$ cosign verify-blob -key https://raw.githubusercontent.com/foo/bar/master/cosign.key -signature https://github.com/foo/bar/releases/download/v0.1.0/bar_0.1.0_Darwin-x86_64.sig 
```

**Comment by dlorenc** [comment]
SGTM
