### ISSUE TITLE
Allow sbom signing and verification during attach and download

### ISSUE THREAD

**Issue by samj1912** [sigstore/cosign#610]
**Description**

It would be great is `cosign attach sbom` and `cosign download sbom` allowed for signing and verification of the related sbom.

Example - 

`cosign attach sbom -key <key> sbom.json` (Signs the sbom and uploads the signature to image:<sha256>.sbom.sig)

`cosign download sbom -key <key> sbom.json` (Checks if the signature exists and is valid before downloading)

Open questions - 

1. How to disable/enable signing/verification
2. Initial signing modes to support

Implementation -

Was thinking of reusing the `SignCmd` and calling it from `attach` and similarly for `verify` (`Exec`) and `download`. (We could initially support keypair signing and only pass those options in and later add others?)

**Comment by dlorenc** [comment]
Some ideas:

`cosign attach sbom` would sign by default, reusing the same flags and behavior as `cosign sign`. We'd add a `--skip-sign` flag to just do the upload.

`cosign download sbom` would then also verify by default. `--skip-verify` could then disable verification.

Or we keep the commands separate, but add a helper flag to sign:

```
cosign attach sbom <image>
cosign sign <image> --attachment=sbom
```

**Comment by samj1912** [comment]
Looking at the current code, I think it might be easier and lead to less duplication if we do the latter.

**Comment by ShubhamPalriwala** [comment]
Hey, I am looking to implement this. Is there any documentation for this? I couldn't find much as of now.
Any help would be appreciated
