### ISSUE TITLE
curl is a insecure pattern for downloading dependencies

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/cosign#620]
curl is an insecure pattern for downloading dependencies

https://github.com/sigstore/cosign/blob/79fa380eddb8ffeecbb1a2e7658bf6a614d1c027/Makefile#L61

https://about.codecov.io/security-update/

One of the recommended approaches to solving this issue is using something like `tools.go` https://github.com/ossf/scorecard/blob/main/tools.go where the external tools are tracked and are part of the go.mod which provides specific SHA. Also having a make target like this to install these tools https://github.com/ossf/scorecard/blob/f55b86d6627cc3717e3a0395e03305e81b9a09be/Makefile#L36

**Comment by dlorenc** [comment]
Is the makefile target used anywhere? Can we just delete it? 

I don't like tools.go because it pollutes the dependency tree.

**Comment by naveensrinivasan** [comment]
> Is the makefile target used anywhere? Can we just delete it?
> 
> I don't like tools.go because it pollutes the dependency tree.

Why not have a separate go.mod for tools similar to this https://github.com/sigstore/rekor/tree/main/hack/tools?
