### ISSUE TITLE
Unpinned dependencies in GitHub workflow

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/cosign#621]
These files have unpinned dependency https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.
The yaml files use the version tag which is something that can be moved which poses a security risk. 

  ```
   "Warn: unpinned dependency detected (job 'build'): .github/workflows/build.yaml:30",
        "Warn: unpinned dependency detected (job 'build'): .github/workflows/build.yaml:31",
        "Warn: unpinned dependency detected (job 'build'): .github/workflows/build.yaml:32",
        "Warn: unpinned dependency detected (job 'build'): .github/workflows/build.yaml:44",
        "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:34",
        "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:38",
        "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:46",
        "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:59"
```

**Comment by dlorenc** [comment]
Let's just delete the codeql one, I'm still unaware of any value added by it and it's not worth the maintenance/risk.

Good catch on build.yaml!

**Comment by naveensrinivasan** [comment]
> Let's just delete the codeql one, I'm still unaware of any value added by it and it's not worth the maintenance/risk.
> 
> Good catch on build.yaml!

Codeql has the ability to check for risk of script injections https://github.com/ossf/scorecard/issues/987
