### ISSUE TITLE
Can cosign be used for signing Windows kernel drivers?

### ISSUE THREAD

**Issue by DavidBerdik** [sigstore/cosign#633]
**Question**
Can cosign be used for signing Windows kernel drivers? I am trying to figure out if it can be, but have not had much luck with doing so.

**Comment by dlorenc** [comment]
Hi @DavidBerdik!

Sorry, no. Cosign can't sign kernel drivers yet. You'll need to use the standard Microsoft tooling and CAs. Getting sigstore trusted by these would be great eventually but we're not there yet :(

**Comment by DavidBerdik** [comment]
Alright, thanks for letting me know! I look forward to the day when it is supported and using leaks or buying $1000 certs is not necessary. 🙂
