### ISSUE TITLE
Can Cosign be used to sign a Windows / Mac Application

### ISSUE THREAD

**Issue by manngo** [sigstore/cosign#642]
**Question**

Sorry if this is a bit naive, but I’m looking for a code signing solution to avoid the Windows Defender alert. Is this the sort of thing that Cosign can do? Is it also suitable for Mac applications?

**Comment by dlorenc** [comment]
Hey!

Not a naive question at all, this is a very complicated topic. You could certainly sign an application with cosign today, but Windows defender wouldn't trust it. The same for Mac applications. We'd like to get trusted by them eventually but aren't there yet.

**Comment by manngo** [comment]
Thanks. It’s back to looking for another solution then.
