### ISSUE TITLE
Add SPIFFE/SPIRE Support for Ambient Credential Detection

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#645]
Similar to #644, but look for a SPIRE socket and try to retrieve an SVID over the runtime API with the sigstore audience.

cc @developer-guy @Dentrax this one could be fun :)

**Comment by colek42** [comment]
@dlorenc @developer-guy,  I am interested about this one as well.  It is on our backlog.

**Comment by dlorenc** [comment]
Go for it!

**Comment by developer-guy** [comment]
yes please go ahead @colek42, we really need you for this issue but please let me know if I can help somehow because this topic is something that I don't know about, but I'm really curious about it also. 🤔🔮🤝

**Comment by dlorenc** [comment]
Yay!
