### ISSUE TITLE
Separate cosigned into a different repository/reduce dependencies 

### ISSUE THREAD

**Issue by samj1912** [sigstore/cosign#651]
**Description**

cosign currently houses an admission controller (cosigned) which includes quite a few k8s related dependencies in the project go.mod. This inflates the dependency tree by quite a bit when trying to import cosign as a library. Even though it may not impact the output binaries, it does impact the development and dependency resolution of the projects that try to include cosign. This also includes dependency conflicts that require manual replace statements in downstream repositories like https://github.com/pivotal/kpack/pull/817#discussion_r699617291

Given that cosign as a library provides such critical functionality, it would be great if we could keep the dependencies to a minimum required.

**Comment by dlorenc** [comment]
I hope we can fix this without splitting repositories. If we make sure the packages are setup correctly and well separated it should be possible to depend on cosign without the cosigned deps.

**Comment by samj1912** [comment]
+1 if we can find a way to reduce cosign dependencies without separating cosigned that would be a win-win :)

**Comment by samj1912** [comment]
Related slack thread https://sigstore.slack.com/archives/C01PZKDL4DP/p1631407770175900?thread_ts=1631407770.175900&cid=C01PZKDL4DP

**Comment by hectorj2f** [comment]
The main reason to keep the dependencies together is to easily maintain and test any change. If we move it to a separate subfolder that would work.

**Comment by dlorenc** [comment]
Are the dependencies still a problem here?

**Comment by hectorj2f** [comment]
We've discussed again this topic and came to the conclusion that we prefer to keep fewer repositories since maintenance (dependencies, testing, ...) gets to be a headache over time.

Closing this issue for now!. @samj1912 Feel free to re-open it.
