### ISSUE TITLE
Run Allstar across sigstore

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/cosign#678]
**Description**
This is not specific to cosign and but an issue across Sigstore. 

Run AllStar https://github.com/ossf/allstar across Sigstore to improve the security posture. 

https://twitter.com/infernosec/status/1437647160154071045

**Comment by naveensrinivasan** [comment]
cc @dlorenc

**Comment by dlorenc** [comment]
Let's do it!

**Comment by naveensrinivasan** [comment]
@jeffmendoza can you help with this?

**Comment by znewman01** [comment]
I believe this is fixed by https://github.com/sigstore/.allstar

Right @cpanato ?

**Comment by tannerjones4075** [comment]
What is the status of this issue? It seems that it was fixed. Should it be closed?
