### ISSUE TITLE
clean and copy commands only handle signatures

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#700]
**Description**

I think these should probably handle `.att` (attestations) as well.

Clean: https://github.com/sigstore/cosign/blob/a868d651df462ec38b152bf56eff877918c55229/cmd/cosign/cli/clean.go#L59
Copy: https://github.com/sigstore/cosign/blob/a868d651df462ec38b152bf56eff877918c55229/cmd/cosign/cli/copy.go#L75

**Comment by dlorenc** [comment]
Yup! We discussed this here I think: #618. Not sure if anyone is working on it.

**Comment by dlorenc** [comment]
Clean now handles the rest, not sure about copy. cc @developer-guy

**Comment by developer-guy** [comment]
yeah that's right @dlorenc, here is a PR for the clean command to support other types (attestations, sboms.)

https://github.com/sigstore/cosign/pull/1430

Let's do the same for copy 🤩

**Comment by developer-guy** [comment]
#1430
#1493 

both above will this issue.
