### ISSUE TITLE
Recommendation: Move cosign to cobra. 

### ISSUE THREAD

**Issue by n3wscott** [sigstore/cosign#706]
**Description**

`ffcli` seems like an ok prototype tool, but it lacks several features that we could take advantage of, like tab support or rich input validation. Anyone opposed to using something more standard for interactive CLIs like Cobra?

I can make a follow up PR for what I am thinking using `sget`.

**Comment by dlorenc** [comment]
+1. @ahmetb wanted to do this awhile ago too

**Comment by n3wscott** [comment]
I created https://github.com/sigstore/cosign/pull/709 to show what I am thinking on moving to cobra in terms of shape. 3 main things to point out:

1. the `cmd/cli` code is to define the flags and cli interface.
2. the cli delegates to an instance object built up in the cli interpreter and is then executed via `Do(ctx)`
3. The code in `pkg/sget` holds all of the logic to do the `sget` task, and knows nothing of the cli. This allows the logic command to be vendored and used down stream without mixing the cli and the task it is doing.

**Comment by n3wscott** [comment]
I am basing this off https://github.com/n3wscott/cli-base and https://github.com/kubernetes-sigs/zeitgeist/tree/master/buoy among other things.

**Comment by cpanato** [comment]
+1

**Comment by n3wscott** [comment]
There is a little wrinkle. `ffcli` supports non-POXIS standard single dash word flags and under POXIS, this is not allowed. See the fix required for `sget`: https://github.com/sigstore/cosign/pull/724.

This means we would have to change all of the flags for `cosign` to POXIS standard flags.

See https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
