### ISSUE TITLE
Create a command to resolve image tags to digests in Dockerfiles

### ISSUE THREAD

**Issue by dekkagaijin** [sigstore/cosign#707]
e.g. `cosign dockerfile resolve`

As part of fixing https://github.com/sigstore/cosign/issues/648, we should create a surface which resolves _mutable_ image tags into _immutable_ image digests. Ideally it would be able to both a) update the Dockerfile in place and b) output an updated Dockerfile to stdout

**Comment by developer-guy** [comment]
hello, short notice, we'll be working on this with @Dentrax FYI. 🙋🏻‍♂️
