### ISSUE TITLE
--key arg accepts both file and value, leads to confusing error

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#71]
I was just trying:

```
cosign verify -key cosign.pub dlorenc/signed-container:v0.0.1
error: illegal base64 data at input byte 6
```

but it turned out there's no `cosign.pub` on my disk, so it performed fallback to parsing `cosign.pub` value  as b64, which led to a confusing error message.

1. This sort of fallback behavior defeats principle of least astonishment.
2. Users can provide values as fds e.g. `--key <(echo "...")` that we can read as files.

So this sort of fallback is unpredictable. Happy to send a PR to fix if 👍🏼.

**Comment by ahmetb** [comment]
Another reason why fallback is bad here: GCP `kms.NewKeyManagementClient()` method returns an error if it cannot establish network connection to the server. But we return any `err` from `kms.Get` as "this is not a KMS reference".

So even if I provide the right `-key gcpkms://...` reference, due to my network connection, we'll proceed to parse it as as a file, and because it doesn't exist, we'll proceed to parse it as base64 string.

**Comment by ahmetb** [comment]
I'll add another issue that I observed right now, `-key` argument accepts `gcpkms://` values, but some commands like `sign` or `verify` also have `-kms` argument that indicates KMS should be used.

However, these two are identical right now:

- `cosign verify -key "$KMSREF" [...]`
- `cosign verify -kms "$KMSREF" [...]`

**Comment by ahmetb** [comment]
@dlorenc what do you think?

**Comment by dlorenc** [comment]
This one has been fixed!
