### ISSUE TITLE
ux: required arguments cause "help requested" error

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#72]
e.g. this command is trying to tell me `either -key or -kms` is required:
```
cosign verify gcr.io/ahmetb-demo/ytdl:latest
USAGE
  cosign verify -key <key> <image uri>

FLAGS
  -a ...              extra key=value pairs to sign
  -check-claims true  whether to check the claims found
  -key ...            path to the public key
  -kms ...            verify via a public key stored in a KMS
error: flag: help requested
```

**Comment by dlorenc** [comment]
I think @priyawadhwa fixed this one:

$ ./cosign sign ghcr.io/dlorenc/signed-container
error: either local key path (-key) or KMS path (-kms) must be provided, not both

**Comment by dlorenc** [comment]
Actually nope, it was @chrnorm! Thanks!

https://github.com/sigstore/cosign/pull/125
