### ISSUE TITLE
Installing cosign from solutions in #588

### ISSUE THREAD

**Issue by syhv-git** [sigstore/cosign#720]
I was running into the same issue as described in #588 and I was able to install cosign with the command fix 
```
go install github.com/sigstore/cosign/cmd/cosign@main
```
 however after the installation ended, I tried running cosign and got `cosign: command not found`

I then tried to follow the fix #716 but I kept getting this error
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
```

My system is relatively new, running Ubuntu(my knowledge of Ubuntu is also relatively new), and I don't quite understand what's going wrong. Also, in my `~/go/bin/` directory I have `cosign` so I don't understand how the command is not found.

**Comment by syhv-git** [comment]
After taking a break for a little and coming back, I copied the cosign executable to `/bin/` and I got it to work. I'd assume the error I received from running #716 solution is because I already have cosign installed even if it didnt execute the cosign command prior to copying the executable to bin. I feel dumb but also learning a lot. Sorry if I wasted anyone's time.

**Comment by dlorenc** [comment]
No worries! Thanks for explaining how you fixed this. It might help someone else some day!
