### ISSUE TITLE
release sget

### ISSUE THREAD

**Issue by rgreinho** [sigstore/cosign#725]
## Description

`sget` is mentioned several times throughout the documentation, but the binary is nowhere to be found.

### Possible solutions

1. Update the release process to build and publish `sget` along `cosign` releases
2. If there was a specific reason why the `sget` binary was not directly available, updating the docs with some instructions would be a good compromise.

**Comment by dlorenc** [comment]
This should be safe to release I think!

**Comment by rgreinho** [comment]
Copy that! I will start working on updating the release process.
