### ISSUE TITLE
ux: consider adding EXAMPLES section to commands

### ISSUE THREAD

**Issue by ahmetb** [sigstore/cosign#73]
Several flags like `-kms` are currently hard to infer how to use without exploring docs or source code.

Having EXAMPLES in each cmd would help with CUJs. Might need to shoehorn into Description, or use `cobra` library to properly do it.

**Comment by dlorenc** [comment]
+1!

**Comment by dlorenc** [comment]
Only a few left:

- download
- upload
- triangulate
