### ISSUE TITLE
Publish Linux/arm64 releases

### ISSUE THREAD

**Issue by howardjohn** [sigstore/cosign#743]
**Description**

Currently Linux amd64 is published, and Darwin arm64 and amd64. It would be great to have Linux arm64 binaries as well.

**Comment by howardjohn** [comment]
Actually I am a bit confused as it shows up here: https://github.com/sigstore/cosign/blob/be8a0f82b5520fc7d59361336ab579231c56aa49/.goreleaser.yml#L26-L37 but not in https://github.com/sigstore/cosign/releases/tag/v1.2.1

**Comment by mattmoor** [comment]
> It would be great to have Linux arm64 images as well

Do you mean binaries or **images**?

Reading again I see `darwin` -> you probably mean binaries!


I'm not sure cosign has fully switched to goreleaser yet, but now that goreleaser has cosign integration, I think it's on @dlorenc radar.

**Comment by howardjohn** [comment]
I was looking for binaries, made a typo in the description. Images would be great as well (if not already present?), but not my primary concern currently

**Comment by cpanato** [comment]
We added that recently and it is not released yet, will be available in the next release most likely (v1.3.0)

**Comment by dlorenc** [comment]
This is done now!
