### ISSUE TITLE
Build fails (macOS)

### ISSUE THREAD

**Issue by JayBrown** [sigstore/cosign#79]
Cloned the repo, but `go build -o cosign ./cmd` after `cd ~/Developer/GitHub/cosign` failed with `no Go files in ~/Developer/GitHub/cosign/cmd`. Am I doing something wrong?

(macOS 11.2.3)

**Comment by ahmetb** [comment]
It seems the build directory has changed, try `./cmd/cosign` as the last argument.

**Comment by JayBrown** [comment]
Thank you. Works great actually. Can only do `sign-blob` and `verify-blob`, of course, but it does remind me a bit of minisign. 👍 🎉
