### ISSUE TITLE
Initial release plans for cosign

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#82]
I ***reeallly*** want to try to sign the first release of cosign, with cosign, if we can figure out a way that makes sense.

I think we'll have to do it manually, since we won't have a signed release to use in automation yet though. Thankfully we can skip some of the issues with reproducible builds.

Here's a rough plan:

The trick is that we can use Go to build a reproducible binary.

- Setup github actions to build and publish a cosign binary on each commit to main
  - cosign builds should be reproducible, with some care.
  - We'll make these build logs public, showing the sha of each binary we build.

- One or more of us will generate keys specific to this initial release.
  - The more the merrier!
  - We can commit these public keys to a file here in the repo.
- We can pick a commit to tag our initial release at.
- We'll have several of us build our own versions of cosign from it, and check the SHAs against the ones from the GitHub action. We can publish those in an issue.
- If they match, we can tag the release. We'll then sign the first binaries and git tag (v0.1.0)!
- We'll publish the signatures in Rekor and in the GitHub release.
- The keys to verify the release will be included **in the git repo at the matching commit**!

After this, we can change our automation to use it's own public/private key-pair (also stored in this repo), and the last signed cosign binary release (v0.1.0) in CI to sign continuous builds. Signatures can get published to Rekor, the build log, and wherever we host the binaries.

Actual tagged releases will also be signed by the automation, and one or more maintainers. We'll sign the git commits as well as the resulting binaries. These can get published to the GitHub release. These public keys (and their mapping to maintainers) will also be stored in the repo.

We can write a verification script to help people verify.

**Comment by ahmetb** [comment]
> Setup github actions to build and publish a cosign **binary** on each commit to main

Won't this make the repo quite difficult for new contributors trying to clone? Since we wouldn't want to rewrite the history in the future in a project like this, I think this is something to avoid?

**Comment by dlorenc** [comment]
> Won't this make the repo quite difficult for new contributors trying to clone? Since we wouldn't want to rewrite the history in the future in a project like this, I think this is something to avoid?

Sorry! I think that wasn't clear. How about: "publish a binary to <SOMEWHER> after each commit to main"?

Not things back into main :) I mean we should publish CI builds somewhere (GCS, Github artifacts) after each build.

**Comment by dlorenc** [comment]
All done here! Release 2 coming soon :)
