### ISSUE TITLE
Support GitHub and GitLab services for generate-key-pair

### ISSUE THREAD

**Issue by Dentrax** [sigstore/cosign#838]
**Description**

Consider the following example:
```
$ cosign generate-key-pair -kms github://repository/project
$ cosign generate-key-pair -kms gitlab://repository/project
```

What these providers going to do is that simply calling `secret` API to _create_ or _update_ the generated _private key_ in the secret variables. Something like: `[UPSERT] /repos/:owner/:repo/actions/secrets` into `$COSIGN_PRIVATE_KEY` variable.

GitHub: https://docs.github.com/en/rest/reference/actions#secrets
GitLab: https://docs.gitlab.com/ee/api/project_level_variables.html

**P.S:** I am not so sure if we should call `GitHub` and `GitLab` as a KMS provider. What about `-git` flag?

^ @developer-guy @erkanzileli 🤗

**Comment by dlorenc** [comment]
I like it!

**Comment by hectorj2f** [comment]
+1 😄
