### ISSUE TITLE
`cosigned` rejections should include image name

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#873]
**Description**

Today the errors from `cosigned` look something like:
```
admission webhook "cosigned.sigstore.dev" denied the request: validation failed: invalid image signature: spec.containers[0].image, spec.containers[1].image, spec.containers[2].image, spec.containers[3].image
```

It would be nice if these also contained the unsigned digest, which feels more useful (especially when this is bubbling through higher-level abstractions like Tekton).

**Comment by hectorj2f** [comment]
Sounds good to me. I can fix that in a quick PR.

**Comment by hectorj2f** [comment]
@mattmoor Let me know if that works https://github.com/sigstore/cosign/pull/875, or we prefer a one-liner err msg instead.
