### ISSUE TITLE
Come up with a good integration testing story for OIDC

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#88]
We should have a way to run e2e tests that doesn't require clicking in the browser...

**Comment by chrnorm** [comment]
@dlorenc if it is helpful: I have previously had a good experience using [Playwright](https://github.com/microsoft/playwright) testing against Auth0 OAuth2.0 flows. Playwright handles jumping through multiple domains as part of an OAuth2.0 flow. I imagine a nice way to run e2e would avoid the browser altogether though to avoid flakiness.

Have you considered [ory/hydra](https://github.com/ory/hydra) or similar to spin up an OIDC server? It looks like it could be run as a Docker container in a CI pipeline and automated (has Go SDK) or deployed to staging infrastructure. This would avoid the need to run tests directly against Gmail or similar and might be a bit easier to automate.

**Comment by dlorenc** [comment]
Oh nice! Thanks for the pointers.

The only other idea I had so far is a "mock" fulcio server that expects a hardcoded identity token and returns a self-signed cert.

Then we could stub out the place where we open the browser to instead push through that flow.
