### ISSUE TITLE
Cosign YubiKey integration broken

### ISSUE THREAD

**Issue by jkjell** [sigstore/cosign#887]
https://github.com/sigstore/cosign/blob/42ec945a84b2f772471037d815288dd85d04922e/cmd/cosign/cli/sign/sign.go#L274

It appears that we're closing the key before using it to sign (I think the defer close got refactor for a higher level function previously).  I'm not sure the best approach to solve this, either open the key again before signing?  Or move the open/close of the YubiKey somewhere else.  Thoughts?

**Comment by jkjell** [comment]
Commenting that line out allowed the signing to work properly.

**Comment by dlorenc** [comment]
Yeah I've verified this.

This one might be tricky to fix. Let me play around with it...
