### ISSUE TITLE
Consider following CII Best Practices

### ISSUE THREAD

**Issue by erkanzileli** [sigstore/cosign#914]
**Description**

> The Linux Foundation (LF) [Core Infrastructure Initiative (CII) Best Practices](https://bestpractices.coreinfrastructure.org/en) badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices.

According to my cosign fork's [assessment](https://bestpractices.coreinfrastructure.org/en/projects/5325#) there are things to do.

cc: @Dentrax @developer-guy

**Comment by haydentherapper** [comment]
Cleaning up old issues: This is likely out of date at this point. Feel free to do another assessment if you'd like! At a glance, we should most of these best practices.
