### ISSUE TITLE
Gem signing

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#92]
Gems support a certs/ directory inside the gem, and a gemspec can point to the cert chain to use for verification.

https://github.com/djberg96/net-proto
https://guides.rubygems.org/security/

We could generate a cert, get it into the directory and configure the fulcio chain all at the same time!

**Comment by lukehinds** [comment]
Do you think this might be better implemented in the kitchen sink CLI sigstore/sigstore client (unless that is you're jut raising here to track)?

**Comment by dlorenc** [comment]
Yeah, should probably be somewhere else!

**Comment by lukehinds** [comment]
we have this now, so you could close this if you like https://github.com/sigstore/ruby-sigstore
