### ISSUE TITLE
option to replace attestations

### ISSUE THREAD

**Issue by JimBugwadia** [sigstore/cosign#923]
**Description**

Provide a way to replace (vs. append) attestations.

Currently the same attestation type can be appended multiple times. A proposal is to support a `--replace` which would change the behavior to replace an attestation of the same type instead of appending it to the existing list of attestations.

Slack discussion at: https://sigstore.slack.com/archives/C01PZKDL4DP/p1633463916305100.

**Comment by JimBugwadia** [comment]
Thanks, @dlorenc! Please assign to me and I will work on a PR.

**Comment by developer-guy** [comment]
amazing thought @JimBugwadia, we (w/@dentrax @erkanzileli) are available for a while, so, we can work on this issue if you let us do that 🤩

**Comment by JimBugwadia** [comment]
@developer-guy  please proceed, thanks!
