### ISSUE TITLE
Brainstorming: How would the "server" command fit in? (cosign as a Service)

### ISSUE THREAD

**Issue by Dentrax** [sigstore/cosign#925]
_The idea behind this is inspired by @developer-guy from the [container-image-sign-and-verify-with-cosign-and-opa](https://github.com/developer-guy/container-image-sign-and-verify-with-cosign-and-opa), which simply exposes 2 endpoints called `/sign` and `/verify`._

---

**Description**

Let's assume we have the `server` command in cosign as follows:

```bash
# By default, it looks current directory for "cosign.pub" and "cosign.key"
$ cosign server

# We can pass multiple "-kms" flags too!
$ cosign server -kms hashivault://key1 -kms k8s://foo/key2
```

The idea here is that slightly same with aforementioned repository. We expose 2 endpoints:

```
[POST] /sign
[POST] /verify

BODY: 
{ 
 "input": [ 
   {
    "image": "gcr.io/foo/bar:v1.0",
    "kms": "k8s",
    "key":  "key2",
   },
   {
    "image": "gcr.io/foo/baz:v2.0",
    "kms": "hashivault",
    "key":  "key1",
   }
  ]
}
```

_Please assume we are using HTTPS connection here._

**30,000-Foot View Use Case**

![usecase](https://user-images.githubusercontent.com/16493751/138071485-78c42939-2ef5-48e2-9c26-7f23e6aa1329.png)

For further details, we can throw a detailed proposal for this if you liked or interested in this idea.

**Comment by dlorenc** [comment]
This is now merged in over at https://github.com/sigstore/cosign-gatekeeper-provider!
