### ISSUE TITLE
How do folks deal with different registries for attestations in things like cosigned?

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#927]
**Question**

Since it's possible to use a different registry for adding SBOM and other attestations to a an image, it would appear that for any given image, verifying attestations these could need to fetched from a different repo. I'm curious how folks are thinking about how to configure things like cosigned webhook to handle this.

My knee jerk reaction is that we should probably have a ConfigMap where this is controlled from and my gut feeling is that a simple prefix matches might go a long way, but would love to hear how folks are dealing with this, or am I just imagining problems?

**Comment by mattmoor** [comment]
I'd guess there are similar problems for *producing* attestations with Chains, so cc @mlieberman85 @priyawadhwa

**Comment by mlieberman85** [comment]
This is a good question. I would push for downloading all associated attestations and potentially materials along with the image into any repo you have, but that might not be viable in a lot of situations.

**Comment by JimBugwadia** [comment]
Here is a related issue and discussion in the Kyverno repo: https://github.com/kyverno/kyverno/issues/2294

The policy rule definition allows specifying an COSIGN_REPOSITORY for each matching image pattern:

```sh
kubectl explain policy.spec.rules.verifyImages

KIND:     Policy
VERSION:  kyverno.io/v1

RESOURCE: verifyImages <[]Object>

DESCRIPTION:
     VerifyImages is used to verify image signatures and mutate them to add a
     digest

     ImageVerification validates that images that match the specified pattern
     are signed with the supplied public key. Once the image is verified it is
     mutated to include the SHA digest retrieved during the registration.

FIELDS:
   attestations <[]Object>
     Attestations are optional checks for signed in-toto Statements used to
     verify the image. See https://github.com/in-toto/attestation. Kyverno
     fetches signed attestations from the OCI registry and decodes them into a
     list of Statement declarations.

   image        <string>
     Image is the image name consisting of the registry address, repository,
     image, and tag. Wildcards ('*' and '?') are allowed. See:
     https://kubernetes.io/docs/concepts/containers/images.

   key  <string>
     Key is the PEM encoded public key that the image or attestation is signed
     with.

   repository   <string>
     Repository is an optional alternate OCI repository to use for image
     signatures that match this rule. If specified Repository will override the
     default OCI image repository configured for the installation.
```

**Comment by vaikas** [comment]
@mattmoor @JimBugwadia @mlieberman85 I'm closing this since I feel like with the ClusterImagePolicy this has been sufficiently addressed. Please reopen if you think there's still something missing.
