### ISSUE TITLE
Shouldn't we validate signatures on SBOM download?

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#928]
**Question**
While I started playing around a bit with #919 and trying to wrap my head around the codebase more and seeing how various pieces do what they do, I noticed that here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/download/sbom.go#L63

It _looks_ like to me that we do not verify signatures like we do for the verify-attestations loop. I was sort of kind of expecting one or two things:
 * sbom to call this method
 * sbom to do the sig validation

So, just curious while I'm ramping up before going too deep in the rabbit hole :)

Also, just curious about why in order to get the attestation vs sbom there's two different commands overall (download sbom vs. verify-attestations). As a user I was kind of expecting there to be a way to download the sbom and any other attestations kind of like this:
cosign download sbom ...
cosign download attestation ...

Especially since the only difference would be changing this here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/download/sbom.go#L42

To (not suggesting it belongs in this cmd, but functionality wise): 
```
		ociremote.WithSignatureSuffix(ociremote.AttestationTagSuffix))
```

**Comment by dlorenc** [comment]
This was correct historically.

It felt weird to combine "upload and sign" into one operation. Attest can be used for that, but the attestation spec AND the sbom specs were both new so it seemed weird to require using the combination of both at the same time.

**Comment by hectorj2f** [comment]
This issue is been discussed in https://github.com/sigstore/cosign/issues/1742. Closing it as it is now a duplicate.
