### ISSUE TITLE
use justfile instead of Makefile via just CLI tool

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#940]
**Description**

@lukehinds recently mentioned this project on Twitter. There is a new project called [just](https://github.com/casey/just) which is an alternative to `make`. Evet `sigstore/sget` project now is using `justfile`, thanks to @Dentrax, please [see](https://github.com/sigstore/sget/commit/38dad5eee2d616e02723efe5681def657a661a4a) for more detail. So, I'm proposing the same for the `cosign` project.

**Comment by znewman01** [comment]
I'm going to close this out unless Make is causing problems; it seems to be working fine (if it ain't broke, don't fix it)
