### ISSUE TITLE
RFC: Release cosigned artifacts with cosign releases?

### ISSUE THREAD

**Issue by n3wscott** [sigstore/cosign#952]
**Description**

I would like to do the work on releasing the `cosigned` webhook config (with signed image) independent of the helm chart.

I would like to know if anyone has a good reason for all the configuration options inside the helm chart? We can also ship the helm chart alongside the resolved release manifests without issues, it just means we will have two paths to install the webhook.

**Comment by dlorenc** [comment]
I think @k4leung4 just did this one in #1414
