### ISSUE TITLE
generating SBOMs for both cosign and cosigned projects and sign them

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#959]
**Description**

we (w/@dentrax) thought that there are no SBOMs files generated and signed for both `cosign` and `cosigned` projects, so we're proposing to generate, sign them right after generating them via cosign's private key, and attach them to the proper registry. I'd like to list the tools that can help us to do that:

* https://github.com/anchore/syft
* https://github.com/anchore/sbom-action
* https://github.com/CycloneDX/gh-gomod-generate-sbom
* https://github.com/spdx/spdx-sbom-generator
* https://github.com/tern-tools/tern
* https://github.com/CycloneDX/cyclonedx-cli
* https://github.com/kubernetes/release/tree/master/cmd/bom

as an example the `Kyverno` project is already doing this:

👀 github.com/kyverno/kyverno/pull/2438/

cc: @luhring @puerco @cpanato @nishakm

**Comment by VinodAnandan** [comment]
We have helped with the SBOM generation for Kyverno, Trivy, gosec, Buildpack, etc. The following Github action is utilised to generate the SBOM, https://github.com/CycloneDX/gh-gomod-generate-sbom . It is simple and straightforward and generates an accurate SBOM with a dependency graph. @nscuro has already addressed @dlorenc's concern ( https://github.com/CycloneDX/cyclonedx-gomod/issues/20 ) related to the accuracy of SBOM. The team is happy to address any further concerns and provide any help with the SBOM generation.

Cc: @nscuro, @stevespringett, @coderpatros, @DarthHater, @tricky42, @knqyf263, @masahiro331, @samj1912, @natalieparellano, @ShubhamPalriwala, @JimBugwadia, @ccojocar, @mmorel-35

**Comment by nscuro** [comment]
As cosign uses goreleaser, https://github.com/goreleaser/goreleaser/issues/2597 (and consequently https://github.com/goreleaser/goreleaser/pull/2618) may be relevant.

**Comment by developer-guy** [comment]
kindly reminder @dlorenc

**Comment by mattmoor** [comment]
For `cosigned` we added support for producing sboms with ko, so once we cut a new ko release we should get that for free (same with the `cosign` images we build with `ko`).

**Comment by developer-guy** [comment]
oh, that's so nice, would you mind sharing the PR on the ko side?

**Comment by mattmoor** [comment]
There were a few, but this connects a few of the dots: https://github.com/google/ko/pull/511

It's merged at HEAD.  Please try it out and report any issues!

**Comment by developer-guy** [comment]
We (w/@dentrax) would like to add CycloneDX support as well. May we do this? Because the CycloneDX community provides great go modules that we can use for this.

* https://github.com/CycloneDX/cyclonedx-go

**Comment by developer-guy** [comment]
works like a charm @mattmoor 🤩
![Screen Shot 2021-12-06 at 20 02 20](https://user-images.githubusercontent.com/16693043/144889378-71f067a7-6dff-4bbb-b6f4-cdc42c0483a4.png)

**Comment by developer-guy** [comment]
Also, cosign supports `text/spdx+json` mediaType for SBOMs based on SPDX format. Maybe we can add this support too, WDYT @mattmoor? Is it worth it?

**Comment by mattmoor** [comment]
@developer-guy works for me!  cc @imjasonh

**Comment by imjasonh** [comment]
> works like a charm @mattmoor 🤩

Just a nit: `ko build --sbom` builds and pushes with an SBOM, and `ko deps --sbom=spdx` generates one on-demand from the binary in the image.

You should try `ko build --sbom=spdx` and `cosign download sbom ...` on the pushed image to verify that the SBOM was built and pushed and attached how `cosign` expects to find it.

**Comment by developer-guy** [comment]
what about making ko compliant with CycloneDX format, and also supporting `text/spdx+json` mediaType, I'd love to do that btw, I can create separate issues for that.

**Comment by mattmoor** [comment]
SPDX was always just a starting point.  I think we'd love to have CycloneDX support as well.
