### ISSUE TITLE
Cosign webhook requires kubernetes version at least 1.20

### ISSUE THREAD

**Issue by blackcat-lin** [sigstore/cosign#962]
**Description**

Try to install cosign webhook on EKS 1.19 cluster and got below error:

{"severity":"EMERGENCY","timestamp":"2021-10-28T15:56:03.638407106Z","logger":"cosigned","caller":"sharedmain/main.go:273","message":"Version check failed","commit":"eb051f6","error":"kubernetes version \"1.19.13-eks-8df270\" is not compatible, need at least \"1.20.0-0\" (this can be overridden with the env var \"KUBERNETES_MIN_VERSION\")","stacktrace":"knative.dev/pkg/injection/sharedmain.CheckK8sClientMinimumVersionOrDie\n\tknative.dev/pkg@v0.0.0-20211004133827-74ac82a333a4/injection/sharedmain/main.go:273\nknative.dev/pkg/injection/sharedmain.MainWithConfig\n\tknative.dev/pkg@v0.0.0-20211004133827-74ac82a333a4/injection/sharedmain/main.go:177\nknative.dev/pkg/injection/sharedmain.MainWithContext\n\tknative.dev/pkg@v0.0.0-20211004133827-74ac82a333a4/injection/sharedmain/main.go:131\nmain.main\n\tgithub.com/sigstore/cosign/cmd/cosign/webhook/main.go:60\nruntime.main\n\truntime/proc.go:255"}

**Comment by hectorj2f** [comment]
@blackcat-lin This is a known limitation that comes from knative as reported in here https://github.com/knative/docs/pull/4362. I am closing the issue now, as it is a limitation.
