### ISSUE TITLE
Use two dashes (e.g., "--name") for multi-letter options (e.g., --key not -key)

### ISSUE THREAD

**Issue by david-a-wheeler** [sigstore/cosign#97]
I suggest using two dashes to start multi-letter options. E.g., use "--key" not "-key".

Usually an option with more than one letter is preceded by "--". E.g., "--key" not "-key". That way, you can have single-letter options combined into a single argument, and multi-letter options are clearly distinct. Then you can support, e.g., "-k" for a key option name as well as "--key".

**Comment by david-a-wheeler** [comment]
P.S. you can maintain backwards compatibility by interpreting "-k" as "--key", and treating "-e" and "-y" as no-ops.

**Comment by dlorenc** [comment]
This has been fixed!
