### ISSUE TITLE
Have ko publish multi-arch builds, drop Dockerfile

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#974]
**Description**

@dekkagaijin pointed me at: https://github.com/sigstore/cosign/blob/fbe6fabcf3dbad1f94e1fd50d3bbe157c180b5be/.goreleaser.yml#L162-L232

We can just publish images like we do for `/ci/`, but with `--platform=all` to build for ~5 architectures.

There are examples of doing this as part of a release workflow with goreleaser here: https://github.com/mattmoor/mink/blob/master/.github/workflows/release.yaml (attaching the release yaml to the release @n3wscott 👀 )

**Comment by mattmoor** [comment]
cc @dlorenc @cpanato

**Comment by mattmoor** [comment]
One thing @dlorenc brought up that might be problematic with `ko` is the piv-key stuff, which uses cgo

**Comment by cpanato** [comment]
@mattmoor @dlorenc the idea is to use ko and drop goreleaser for building the images? and how about the binaries?

we can drop goreleaser and use a make/bash that builds everything and push to github.

we just need to decide how we move forward and I can implement the changes


> One thing @dlorenc brought up that might be problematic with ko is the piv-key stuff, which uses cgo

for this we are only building the binaries not images

**Comment by cpanato** [comment]
ignore the issue link, copy/paste issues

**Comment by dlorenc** [comment]
Done in #984!
