### ISSUE TITLE
cosign doesn't provide an option to set timeout on rekor upload

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/cosign#990]
I am trying to `cosign sign-blob` and run into a timeout issue 
```
use /home/runner/work/scorecard/scorecard/dist/scorecard-linux-arm64: Post \"https://rekor.sigstore.dev/api/v1/log/entries\": context deadline exceeded\n": exit status 1|

```
After some investigation, it looks like the code doesn't provide an option 
https://github.com/sigstore/cosign/blob/ae36ba5bd7fd839e6dceccfa2a27455572e8a3dc/pkg/cosign/tlog.go#L76

but `rekor` has that option https://github.com/sigstore/rekor/blob/0c2b37c15bbaf80a1c32d47b63956c5d499a6f2c/pkg/generated/client/entries/create_log_entry_parameters.go#L51

`func NewCreateLogEntryParamsWithTimeout(timeout time.Duration) *CreateLogEntryParams`

**Comment by cpanato** [comment]
this is something we face before, but I'm not sure if we fix it @lukehinds did you make a PR for this fix?

**Comment by naveensrinivasan** [comment]
If not I am open to fixing this. We need in Scorecard. Thanks

**Comment by naveensrinivasan** [comment]
Fixed by https://github.com/sigstore/cosign/pull/1020
