### ISSUE TITLE
Transfer of ownership for rekor-installer GA (GitHub Action)

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#992]
**Description**

We (w/@dentrax @erkanzileli) created a repository for installing the `rekor-cli` via GitHub Action, and we can move this GA to under the `sigstore` organization as an official repository if you like it :point_down:

* https://github.com/developer-guy/rekor-installer
* https://github.com/developer-guy/rekor-installer/runs/3989660891?check_suite_focus=true

We talked a bit about it. Here is the slack conversation: 💬 https://sigstore.slack.com/archives/C01PZKDL4DP/p1635093195061800

@dlorenc gives us a hint, "should we bundle these all up into one action?" so I opened this issue to discuss a bit.

Waiting for your feedback !! 🙋🏻‍♂️ 🥳

**Comment by dlorenc** [comment]
I like the idea of one action. Curious about what others think though!

**Comment by cpanato** [comment]
i support this as well

**Comment by luhring** [comment]
I think this makes sense!

One thought though — do we intend to add **other kinds of actions besides installing**? For example, a cosign action that signs things?

I ask because another pattern we've started seeing in the GitHub Actions ecosystem is to group actions logically by **high-level task**. We followed this when building the Syft GitHub action just recently:

`anchore/sbom-action` — performs the entire, end-to-end flow of creating an SBOM and uploading it for you.

But we also have _inner actions_ that aid in the overall flow with independently useful functions.

`anchore/sbom-action/download-syft` — installs Syft. (might be similar to the current Sigstore installer actions)

`anchore/sbom-action/publish-sbom` — handled publishing of the SBOM after it's generated.

>do we intend to add other kinds of actions besides installing?

If the answer is "no", then disregard this whole comment, I don't think it applies!

**Comment by dlorenc** [comment]
> For example, a cosign action that signs things?

I tried to get this to work originally but found it too hard to pass around things like the image name and credentials to automatically sign things. I'd love to make it more automatic, but settled on just installing at first as the lowest common denominator.

**Comment by cpanato** [comment]
> > For example, a cosign action that signs things?
> 
> I tried to get this to work originally but found it too hard to pass around things like the image name and credentials to automatically sign things. I'd love to make it more automatic, but settled on just installing at first as the lowest common denominator.

i will work in more automatic things, I have some ideas :) will work on this for cosign this week

**Comment by developer-guy** [comment]
kindly ping @cpanato

**Comment by cpanato** [comment]
that is in my backlog :)

**Comment by developer-guy** [comment]
is there anything that I can help with?

**Comment by developer-guy** [comment]
I can transfer it if you want btw or I can add you as an owner of the repo

**Comment by developer-guy** [comment]
maybe we can create something like `sigstore-installer`, and it can accept a parameter to get a tool name that people want to install such as `cosign, rekor-cli, etc`, and also version. The implementation will look like the following:

```shell
uses: sigstore/sigstore-installer@latest
with:
  tool: "cosign"
  version: 'v1.3.1' # optional
```

WDYT?

**Comment by cpanato** [comment]
> I can transfer it if you want btw or I can add you as an owner of the repo

you need to transfer to @dlorenc he is admin of the org

**Comment by developer-guy** [comment]
I've recently transferred another repo, so, I can do it, I think, I have the right permissions to be able to do it.

**Comment by dlorenc** [comment]
> maybe we can create something like `sigstore-installer`, and it can accept a parameter to get a tool name that people want to install such as `cosign, rekor-cli, etc`, and also version. The implementation will look like the following:

I like it. We could default to everything @ latest or let people specify a set of specific ones and versions.

**Comment by haydentherapper** [comment]
Cleaning up old Cosign issues: We don't see enough usage of rekor-cli to need a dedicated GitHub Action in the Sigstore org, so I'll close this out. We can revisit if there is interest.
